### ISSUE TITLE
Incorrect documentation and missing typescript definition change within pr #98 

### ISSUE THREAD

**Issue by Dreaded-Gnu** [photonstorm/phaser-ce#101]
* An error in the documentation
* An error in the TypeScript defs

The typescript definition file is out of date. With pull request #98 the game object factory method `weapon` has been extended by parameter "bulletClass", which is currently missing within the definition file.

Further more the added documentation seems to be wrong. Shouldn't it be Phaser.Bullet instead of object at `src/gameobjects/GameObjectFactory.js` line 66?
```javascript
    * @param {object} [bulletClass] - The Class of the bullets that are launched by this Weapon

    * @param {Phaser.Bullet} [bulletClass] - The Class of the bullets that are launched by this Weapon
```

When you need help there, I would provide a quick pull request for this issue later this day.

- [x] Fix documentation for parameter bulletClass at `Phaser.GameObjectFactory#weapon`
- [x] Extend typescript definition file to contain additional optional parameter for ` Phaser.GameObjectFactory#weapon`

**Comment by samme** [comment]
`{object}` does look wrong to me but Weapon#bulletClass and Group#classType are already described the same way. It should be `{function}` (a constructor).

I'll update the docs for classType and friends. Go ahead with the typescript fix, thanks.
