### ISSUE TITLE
cursor: default

### ISSUE THREAD

**Issue by IVA-apps** [photonstorm/phaser-ce#110]
Hello!

After the focus is lost from the Phaser.button, the cursor is set as "default", but should be "inherit"

**Comment by samme** [comment]
Hi @IVA-apps. Why is `inherit` preferred?

**Comment by IVA-apps** [comment]
1. It stands as the default when creating the Game. It is logical that after the "hover button", the past value should return, and not the new one.
2. inherit in DOM is replaced with values from CSS, but "div="style:default;"" remains as the browser cursor (NOT CSS, ONLY DOM style... is priority)

Example:
In CSS there is a my cursor, the game works, but after the cursor over on the button and is removed from it, it will be replaced by the usual cursor, not the previous one at the start.

**Comment by samme** [comment]
The game is actually created with no value for `cursor`, but it's set to `inherit` when regaining focus or shutting down a state (which is common). It's a little odd.

I think I'll change both `default` and `inherit` to no value so it's uniform. `cursor` is an inherited property so it will work the same.

**Comment by IVA-apps** [comment]
"Inherit" - refers to the styles of the parent
And "default" is the style itself, it's a simple cursor!

That is, when you install "default", you break the developer settings in CSS

Create any game with a button, before that, load your css file with the settings, for example, html {cursor: move;} After that, move the cursor over the button and remove. You will see that now the cursor does not "move", but became simple ("default")

**Comment by IVA-apps** [comment]
![2017-04-06 02_42_23](https://cloud.githubusercontent.com/assets/24360456/24731441/b3a86c08-1a72-11e7-9d72-20255366499f.gif)

**Comment by IVA-apps** [comment]
Thank you!

**Comment by samme** [comment]
<http://codepen.io/samme/pen/LWoPzR>

**Comment by IVA-apps** [comment]
The cursor is still replaced on "default", but should listen to the PARENT!

In the example, I specified the cursor in css as MOVE, after blur it is replaced on "default", but it crash the CSS style!

Should be:
Start game: cursor: "" or inherit
Hover button: cursor: pointer
Blur button: cursor: "" or inherit (NOT "default")

![2017-04-06 22_54_33](https://cloud.githubusercontent.com/assets/24360456/24773173/ca9df220-1b1c-11e7-9f60-1dec1a23eca5.gif)

**Comment by samme** [comment]
Patch is in #124.

<http://codepen.io/samme/pen/LWoPzR> demonstrates the issue (unpatched).

**Comment by IVA-apps** [comment]
Oh, sorry!
Thank you, Samme!
