### ISSUE TITLE
Canvas blend mode compatibility not properly being detected

### ISSUE THREAD

**Issue by mikewesthad** [photonstorm/phaser-ce#130]
I opened up a project that relies on canvas's multiply blend mode and noticed that it suddenly wasn't working anymore. After digging around a bit, it looks like most canvas blend modes aren't working in CE in the latest Chrome & FF on Windows 10. (Note: canvas blend modes work fine in Phaser 2.6.2. WebGL blend modes appear fine in CE.)

Here's a codepen example (linked against 2.7.5 via jsdelivr): http://codepen.io/mikewesthad/pen/JWQmdV. Two images are being drawn. The first with the default blend mode (source-over), and the second with multiply. The second image gets drawn with source-over instead of multiply.

What I see:
![image](https://cloud.githubusercontent.com/assets/1131802/24829947/ac636922-1c41-11e7-8903-8c6b7dee4aeb.png)

What I should see:
![image](https://cloud.githubusercontent.com/assets/1131802/24829949/b98fc17c-1c41-11e7-8dd5-6758e8a071bf.png)

I tried extracting the code that checks whether multiply blend mode is available ([source](https://github.com/photonstorm/phaser-ce/blob/29bc2b2d76f432a34fdb36ecc8ee634e0d8fdaf0/src/utils/Device.js#L776)) and checking it in that codepen test. It appears to properly detect that multiply blend mode is available. A weird quirk - if I force the compatibility check before creating the images, the blend mode seems to work fine... So, do the base64 images need to use `onload` before they can get pixels and properly check compatibility?

**Comment by samme** [comment]
<http://codepen.io/samme/pen/gmNJar?editors=0010>

![blendmodes-chrome](https://cloud.githubusercontent.com/assets/435681/24833505/a2a1780a-1c7f-11e7-953a-5bc1dc361412.png)

**Comment by mikewesthad** [comment]
Ah, nice visual @samme.

I think my hunch is correct - base64 images aren't loaded synchronously in all browsers. See this codepen: http://codepen.io/mikewesthad/pen/zZgovJ?editors=0010. It uses the Phaser code for checking for multiply blend mode in two ways: checking immediately and checking after img,onload events fire. The image pixels aren't available immediately in the latest Chrome/FF (though they are in Edge), so the multiply check fails unless it is done asynchronously.

I don't have time right now to look into a fix, but I imagine it requires waiting for img.onload events in Device.js and then tweaking `initialized` & `onInitialized` so that they allow the canvas check to be carried out asynchronously.

**Comment by samme** [comment]
In Safari `device.canUseMultiply` is also false on first load (or force reload), true after.

**Comment by samme** [comment]
#137 skips the pixel test and just checks if the browser accepts the `multiply` keyword.

If anyone has IE <= 11, please try it and verify that `game.device.canUseMultiply` is false (like before).
