### ISSUE TITLE
Why use the game instance instead of the Phaser object itself?

### ISSUE THREAD

**Issue by Arcanorum** [photonstorm/phaser-ce#131]
* A problem with my own code/the API

Why does the API use references to the running game instance, instead of the main Phaser object when calling methods like those found in Math, Util, Arcade, etc.?

Not sure if this is something that will only really ever affect me, but I'm making a multiplayer game, and I'd like to use some of the handy methods of Phaser, so I've included Phaser on the server, but I'm NOT creating a game instance, as I'm handing my own updates, physics etc, and don't need rendering.

For example, I'd like to be able to use:
`Phaser.Physics.Arcade.prototype.velocityFromAngle(40, 50);`
and use the velocities it returns to move my game object (that isn't using Arcade, it's separate from Phaser), I get the error:
`Uncaught TypeError: Cannot read property 'math' of undefined`
Which is to be expected, as velocityFromAngle is trying to access math from this.game, but I don't have, and don't want to have, a game instance running.
```javascript
velocityFromAngle: function (angle, speed, point) {

    if (speed === undefined) { speed = 60; }
    point = point || new Phaser.Point();

    return point.setTo((Math.cos(this.game.math.degToRad(angle)) * speed), (Math.sin(this.game.math.degToRad(angle)) * speed));
                                            ^Cant find math, no game instance.

},
```

Whereas if I replace occurrences of `this.game.math` with `Phaser.Math`, it works.

**Comment by Arcanorum** [comment]
Appears I can't get access to the Phaser object on the server (NodeJS) by simply installing it and using `require('phaser-ce/build/phaser')` as it gives errors about wanting to set up a canvas element and start PIXI and stuff... ;/

**Comment by samme** [comment]
It's definitely unnecessary there. Are there other places?
