### ISSUE TITLE
Phaser.BitmapData.generateTexture() initially generates 0x0 textures

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser-ce#136]
This Issue is about

* A bug in the API (maybe)

The problem can be found in this piece of code:
```
var game = new Phaser.Game();

function Boot() {
    this.create = function (game) {
        var bmd = game.add.bitmapData();
        bmd.fill(255, 255, 255, 1);
        bmd.generateTexture("texture");

        var sprite = game.add.sprite(0, 0, "texture");
        console.log("sprite size:", sprite.width, sprite.height);
    };
}

game.state.add("boot", Boot);
game.state.start("boot");
```
I believe the bug is either in Phaser or the browser. Chrome 57.0.2987.133 (64-bit) and Firefox 52.0.2 (32-bit) have the problem, while Edge doesn't seem to have it. I tested with the latest CE version.

In the snippet I provided, I just create a BitmapData object, fill it with white and generate a texture from it to use for a Sprite. When you first open the game, it logs `sprite size: 0 0`. When you refresh a couple of times, it starts to work and logs `sprite size: 256 256`. If you navigate to a new page and return back or just open a new tab with the game, the problem occurs again. With so little code, I believe the problem lies somewhere in Phaser (doubtful) or in the browsers.

I tried generating the texture in `preload()`, while creating the Sprite in `create()`, I tried using `BitmapData.resize()` and a bunch of other stuff. The problem persists. I tested it in the [sandbox](https://phaser.io/sandbox) too. You can copy-paste the code there and see the problem for yourself. When you put the code from my `create()` in the sandbox's `create()` and click play, it logs wrong and nothing appears. If you click `update`, a white square can be seen and the logs are alright.

**Comment by samme** [comment]
<http://codepen.io/samme/pen/bBQqaV>

Related:

- [BitmapData.generateTexture Firefox](http://www.html5gamedevs.com/topic/25548-bitmapdatageneratetexture-firefox/)
- [Potential sprite cross-browser rendering bug when using graphic objects](http://www.html5gamedevs.com/topic/27880-potential-sprite-cross-browser-rendering-bug-when-using-graphic-objects/)
- [BitmapData.generateTexture doesn't work first time in Safari](http://www.html5gamedevs.com/topic/20258-bitmapdatageneratetexture-doesnt-work-first-time-in-safari/)

**Comment by samme** [comment]
<https://bugs.chromium.org/p/chromium/issues/detail?id=514206>

> As concluded in <https://code.google.com/p/chromium/issues/detail?id=469131> data URI image resources should be loaded async to avoid instances of "flash of broken image" in the test case in that bug.
>
>On top of that:
> * Blink is the only engine that loads data URI resource synchronously
> * This is contrary to what the spec says

**Comment by samme** [comment]
I think this can make even the built-in `__default` and `__missing` images invalid during first load.

**Comment by samme** [comment]
https://github.com/samme/phaser-ce/commit/1bf7ca70be9e45308a4761417caf520e0fb786ac
