### ISSUE TITLE
Release 2.7.6?

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#142]
We have some good bug fixes, especially re. Chrome 57.

<https://github.com/photonstorm/phaser-ce/milestone/1>

**Comment by samme** [comment]
1. [ ] Make sure the version number is increased, in line with semver policies, in the following files:
    - [ ] <https://github.com/photonstorm/phaser-ce/blob/master/package.json>
    - [ ] <https://github.com/photonstorm/phaser-ce/blob/master/src/Phaser.js>

2. [ ] Make sure that you have added details of the new version to the README.md and CHANGELOG.md. This should include a summary of changes made in the version. You can usually obtain this from the commit / PR history. It's nice to credit who made the changes by linking to their GitHub user ID, but isn't a requirement.
    - [ ] <https://github.com/photonstorm/phaser-ce/blob/master/README.md#change-log>
    - [ ] <https://github.com/photonstorm/phaser-ce/blob/master/CHANGELOG.md>

3. [ ] From the root repo folder, run `grunt jshint` and make sure there are no jshint errors. If there are, please fix them, or request that the original author of the code does so.

4. [ ] Once jshint passes run `grunt release`, sit back, and wait. It will build all of the versions of Phaser required, update the doc files, TypeScript defs and lots more.

5. [ ] Commit all of the new files and make sure to include a clear message in your commit saying you want this release pushed to npm. Be sure to tag me when doing this, i.e. `Phaser CE Version 2.7.6. Please publish to npm @photonstorm` - I'll see it, and then publish as soon as I can (often the same day).

**Comment by photonstorm** [comment]
Sure thing, happy to publish this if you are?

**Comment by samme** [comment]
I'll go through the checklist and then tag you in a PR. Thanks!
