### ISSUE TITLE
Unable to apply lineStyle to a triangle

### ISSUE THREAD

**Issue by alexus85** [photonstorm/phaser-ce#146]
This Issue is about  **not being able to specify a lineStyle for a Polygon.**

*  Probably a problem with my own code (?):
  * **Phaser version(s):** 2.7.5
  * **Live example**: 
    -- not working - probably cause `lineStyle `is defined (?) -> https://jsfiddle.net/wjec8xye/5/
    -- working - no `lineStyle `specified - https://jsfiddle.net/wjec8xye/4/
  * **What should happen:** It should fill the generated shape and apply lineStyle .
  * **What happens instead:** It doesn't seem to work unless I remove the lineStyle.

**Comment by samme** [comment]
Should be `g.lineStyle( 1, 0xff0000 )`
