### ISSUE TITLE
Phaser-Spine scalex/scaley bug

### ISSUE THREAD

**Issue by shibekin69** [photonstorm/phaser-ce#149]
Hi, can anyone help with this? I'm posting here because the Spine devs don't have plans on supporting a Phaser-specific version, just their generic Spine-TS JS implementation. 

**THE PROBLEM:**
Using Phaser 2.7.3 with Phaser-Spine. we're trying to hunt down what's causing a scale-x-only or scale-y-only transform bug, and if the problem is only Spine-related, or Phaser-related, or both.

**DETAILS:**
What happens is, if you animate one of the bones to have a scalex or scaley only transformation, it should look skewed accordingly, like stretching a rubberband in one direction. What happens instead is that, the other axis is also affected and making the images shift, too.

**POSSIBLE SOLUTION AND LOCATION OF PROBLEM:**
@AleBles has identified a possible solution, but in my test case, it doesn't seem to work.

https://github.com/orange-games/phaser-spine/pull/50

In phaser-spine.js, it's on line 3072. Originally it looks like this:

    slotContainer.scale.x = bone.getWorldScaleX();
    slotContainer.scale.y = bone.getWorldScaleY();

@AleBles 's change:
    slotContainer.scale.x = bone.getWorldScaleY() * bone.worldSignX;
    slotContainer.scale.y = bone.getWorldScaleX() * bone.worldSignY;

Please see attached test case of a flower-like pattern of rectangle boxes rotated 8-way and scaled only on one axis. There's 4 of them, 1 for each quadrant surrounding the root point at 0,0.

**WHAT IT SHOULD LOOK LIKE (USING THE SPINE EDITOR PREVIEW):**

![test](https://cloud.githubusercontent.com/assets/12507139/24986706/6ec60160-202e-11e7-8a1f-8901e017588f.gif)

**WHAT IT LOOKS LIKE ON PHASER (MANUALLY MADE A GIF WITH ONLY 3 FRAMES, USED PRINT SCREEN):**

![testerror](https://cloud.githubusercontent.com/assets/12507139/24987050/4a281d78-2030-11e7-9cba-c2eb0bf9349e.gif)

**MINIMUM TEST CASE (WITH INDEX.HTML):**

[phaserscaledebug.zip](https://github.com/photonstorm/phaser-ce/files/918305/phaserscaledebug.zip)

**OBSERVATIONS**

In my minimum test case, if you comment out the animation:

scaledebugsp.setAnimationByName(0, 'animation', true);

and access the following in the Google Chrome Developer console: 

scaledebugsp.skeleton.findBone('diag315_q1')

If you manipulate the property scaleX or scaleY, you'll see that the transformation affects the other axis.

You can also see that certain rectangles are not affected much, like those pointing 0 and 180 degrees (horizontal).

**Comment by RollinSafary** [comment]
i can suggest you to use phaser spine ts branch with npm install, i use that branch and it works better than the master branch
