### ISSUE TITLE
Correct way of adding typescript def files in version ce ?

### ISSUE THREAD

**Issue by appsolutegeek** [photonstorm/phaser-ce#16]
Hi,

I am using webpack with expose-loader to have Phaser etc available on the global scope. Things are working well, I decided to upgrade to phaser-ce and the only way I could get my IDE (webstorm) to recognise that Phaser was actually a type was doing the following in MY tsconfig.json file

```
  "include": [
    "**/Game.ts",
    "../node_modules/phaser-ce/typescript/phaser.d.ts"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
```

Now it does work but says there are Multiple Options i.e. phaser.d.ts and phaser.comments.d.ts and phaser_box2d.d.ts.

I was wondering if I was doing the above correctly ?

I of course decided to remove the Includes section above but then that fails probably due to the fact that I have the exclude node_modules so the types are never being picked up.

I am using typescript 2.1 and decided to try and use the typeRoots but this also failed

`    "typeRoots" : ["../node_modules/phaser-ce/typescript"]`

I am little confused of how to proceed do I leave the     "../node_modules/phaser-ce/typescript/phaser.d.ts"  inside the include section of the tsconfig.json ? It just feels kind of wrong.

Also even if I use this way then 'Phaser' seems to show Multiple Implementations for Phaser

Any help or info really appreciated

Thanks

**Comment by rroylance** [comment]
In your tsconfig.json you need to add the following;
```javascript
{ 
...
    "files": [
        "./node_modules/phaser-ce/typescript/phaser.comments.d.ts",
        "./node_modules/phaser-ce/typescript/pixi.comments.d.ts",
        "./node_modules/phaser-ce/typescript/p2.d.ts"
    ]
}
```

**Comment by samme** [comment]
Closing this, but if any relevant Phaser docs are incorrect/incomplete, please add an issue.
