### ISSUE TITLE
Safari Audio Bug and IE FullScreen API Bug

### ISSUE THREAD

**Issue by all-scripts** [photonstorm/phaser-ce#164]
Safari Browser 5.1.7 (7534.57.2)
--------------------------------------------------------------------
The problem with Safari the audiofiles dont loading and then i get the error that the key dont found in the cache. All another Browser works (Firefox, Chrome, Opera, Internet Explorer)

Internet Explorer 11.0.9600.18524 Updateversion 11.0.37
-------------------------------------------------------------------- 
The problem with IE (Fullscreen) the Phaser says Phaser.ScaleManager: requestFullscreen failed or device does not support the Fullscreen API

The device Supports Fullscreen the Browser to because this works (Firefox, Chrome, Opera, Safari) only with the IE is the problem.
 
inside the game when i go of Settings an Select Fullscreen i get the error in IE:
 
http://shop.als-dev.de/HTML5games/GoldenKnight3/test.html
 
when i use a code outside the phaser with the button (outside top) the fullscreen works.

**Comment by samme** [comment]
> The problem with Safari the audiofiles dont loading and then i get the error that the key dont found in the cache. All another Browser works (Firefox, Chrome, Opera, Internet Explorer)

What happens at <http://phaser.io/examples/v2/audio/play-music>?

**Comment by all-scripts** [comment]
Hallo samme,

its the same:

TypeError: 'undefined' is not an object (evaluating 'editor.$blockScrolling = Infinity')
embed.php:6Viewport argument key "minimal-ui" not recognized and ignored.
d:-1Ressource wurde als Schrift interpretiert, aber mit MIME-Typ application/font-woff übertragen.
d:-1Ressource wurde als Schrift interpretiert, aber mit MIME-Typ application/font-woff übertragen.
d:-1Ressource wurde als Schrift interpretiert, aber mit MIME-Typ application/font-woff übertragen.
d:-1Ressource wurde als Schrift interpretiert, aber mit MIME-Typ application/font-woff übertragen.
d:-1Ressource wurde als Schrift interpretiert, aber mit MIME-Typ application/font-woff übertragen.
d:-1Ressource wurde als Schrift interpretiert, aber mit MIME-Typ application/font-woff übertragen.
data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZpZXdCb3g9IjAgMCAxNiAxNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSIjRTY0MjQxIj48cGF0aCBkPSJNOC4yOTIgMTEuODUyYy4zMDYgMCAuNDUtLjEyNi40MzItLjQ2OGwtLjE2Mi0yLjEwNiAxLjg1NCAxLjE3Yy4yNy4xOC40NjguMTI2LjYxMi0uMTQ0bC4zNi0uNzJjLjE0NC0uMjcuMTI2LS40NS0uMTk4LS41OTRsLTEuODcyLS44NjQgMS44NzItLjg4MmMuMzA2LS4xNDQuMzQyLS4zMjQuMTk4LS41OTRsLS4zNi0uNzAyYy0uMTQ0LS4yNy0uMzI0LS4zMjQtLjYxMi0uMTQ0bC0xLjg3MiAxLjE4OC4xOC0yLjI4NmMuMDE4LS4zMjQtLjEwOC0uNDUtLjQzMi0uNDVoLS43NzRjLS4zMjQgMC0uNDUuMTA4LS40MzIuNDVsLjE2MiAyLjM0LTEuOTI2LTEuMjQyYy0uMjctLjE4LS40NS0uMTI2LS42MTIuMTYybC0uMzYuNjg0Yy0uMTYyLjI4OC0uMTA4LjQ1LjE5OC41OTRsMS44NzIuODgyLTEuODcyLjg2NGMtLjMwNi4xNDQtLjM0Mi4zMDYtLjE5OC41OTRsLjM2LjcwMmMuMTQ0LjI4OC4zNDIuMzQyLjYxMi4xNjJsMS45MDgtMS4yNDItLjE0NCAyLjE3OGMtLjAxOC4zMjQuMTA4LjQ2OC40MTQuNDY4aC43OTJ6Ii8+PC9nPjwvc3ZnPgo=:-1Ressource wurde als Bild interpretiert, aber mit MIME-Typ image/svg+xml übertragen.
phaser.2.6.2.min.js:12Phaser v2.6.2 | Pixi.js v2.2.9 | Canvas | HTML Audio | http://phaser.io
phaser.2.6.2.min.js:20Phaser.Cache.getSound: Key "boden" not found in Cache.
phaser.2.6.2.min.js:20Phaser.Cache.isSoundDecoded: Key "boden" not found in Cache.
phaser.2.6.2.min.js:20Phaser.Cache.isSoundDecoded: Key "boden" not found in Cache.
phaser.2.6.2.min.js:20Phaser.Cache.getSound: Key "boden" not found in Cache.
phaser.2.6.2.min.js:21TypeError: 'null' is not an object (evaluating 'this.game.cache.getSound(this.key).isDecoding')

dont load nothing i test all with many different audio formats like mp3 / ogg / m4a ...
 
Kai Ripp
marketing@all-scripts.de
18.04.2017 


----- Folgende Nachricht wurde empfangen ----- 


Absender: samme 
Empfänger: photonstorm/phaser-ce 
Zeit: 2017-04-18, 01:53:02
Betreff: Re: [photonstorm/phaser-ce] Safari Audio Bug and IE FullScreen APIBug (#164)
The problem with Safari the audiofiles dont loading and then i get the error that the key dont found in the cache. All another Browser works (Firefox, Chrome, Opera, Internet Explorer)
What happens at http://phaser.io/examples/v2/audio/play-music?


**Comment by samme** [comment]
It plays correctly in my Safari.

What shows in Safari's Network pane?

**Comment by all-scripts** [comment]
Hallo samme,


mhh i get the safari from there: http://www.chip.de/downloads/Safari_27264736.html
i dont found an more aktuell safari for windows. what version do you use?

on the network pane i cant see any audio file.
 
Kai Ripp
marketing@all-scripts.de
18.04.2017 


----- Folgende Nachricht wurde empfangen ----- 


Absender: samme 
Empfänger: photonstorm/phaser-ce 
Zeit: 2017-04-18, 02:41:59
Betreff: Re: [photonstorm/phaser-ce] Safari Audio Bug and IE FullScreen APIBug (#164)
It plays correctly in my Safari.
What shows in Safari's Network pane?


**Comment by samme** [comment]
> <http://shop.als-dev.de/HTML5games/GoldenKnight3/test.html>

1. You should load assets through `preload`, not `create`.
2. You should load audio like

   ```
   this.load.audio('sfx', ['sfx.mp3', 'sfx.ogg']);
   ```

**Comment by samme** [comment]
> The problem with IE (Fullscreen) the Phaser says Phaser.ScaleManager: requestFullscreen failed or device does not support the Fullscreen API

The browser can ignore/deny a fullscreen request, which will make it fail.

What does IE do on <http://phaser.io/examples/v2/display/fullscreen>?

**Comment by all-scripts** [comment]
Hallo samme,

The complete stage is for loading is a preloader stage.

But nothing to see with this because the original phaser demo dont work on my Safari Browser.

i look for devices and load files where is compatible for better performance.
 
Kai Ripp
marketing@all-scripts.de
18.04.2017 


----- Folgende Nachricht wurde empfangen ----- 


Absender: samme 
Empfänger: photonstorm/phaser-ce 
Zeit: 2017-04-18, 05:07:34
Betreff: Re: [photonstorm/phaser-ce] Safari Audio Bug and IE FullScreen APIBug (#164)
http://shop.als-dev.de/HTML5games/GoldenKnight3/test.html
You should load assets through preload, not create.
You should load audio like
this.load.audio('sfx', ['sfx.mp3', 'sfx.ogg']);



**Comment by all-scripts** [comment]
Hallo samme,

on my ie the same error comes:

Phaser.ScaleManager: requestFullscreen failed or device does not support the Fullscreen API

but you can see on my demo that the button outside works for fullscreen.

 
Kai Ripp
marketing@all-scripts.de
18.04.2017 


----- Folgende Nachricht wurde empfangen ----- 


Absender: samme 
Empfänger: photonstorm/phaser-ce 
Zeit: 2017-04-18, 05:12:20
Betreff: Re: [photonstorm/phaser-ce] Safari Audio Bug and IE FullScreen APIBug (#164)
The problem with IE (Fullscreen) the Phaser says Phaser.ScaleManager: requestFullscreen failed or device does not support the Fullscreen API
The browser can ignore/deny a fullscreen request, which will make it fail.
What does IE do on http://phaser.io/examples/v2/display/fullscreen?


**Comment by samme** [comment]
In <http://shop.als-dev.de/HTML5games/GoldenKnight3/src/game.js> the 'safari' check is backwards: Safari should get mp3, not ogg.

I don't have Safari 5 so I can't reproduce the problem in <http://phaser.io/examples/v2/audio/play-music>. If you want to debug it try stepping through Phaser.Loader#loadAudioTag.

IE11 seems to allow fullscreen only via certain events: https://github.com/photonstorm/phaser/issues/1098

**Comment by all-scripts** [comment]
Hallo samme,

width safari i test with different audio formats first with mp3 later with ogg and with m4a too, nothing from this works and all what i can see is that safari 5.1.7 is the last desktop version where exists (for windows)


mhh okay why ie dont accept fullscreenmode from phaser i dont know i only know inside the phaser dont work the button outside works.
 
Kai Ripp
marketing@all-scripts.de
18.04.2017 


----- Folgende Nachricht wurde empfangen ----- 


Absender: samme 
Empfänger: photonstorm/phaser-ce 
Zeit: 2017-04-18, 18:17:43
Betreff: Re: [photonstorm/phaser-ce] Safari Audio Bug and IE FullScreen APIBug (#164)
In http://shop.als-dev.de/HTML5games/GoldenKnight3/src/game.js the 'safari' check is backwards: Safari should get mp3, not ogg.
I don't have Safari 5 so I can't reproduce the problem in http://phaser.io/examples/v2/audio/play-music. If you want to debug it try stepping through Phaser.Loader#loadAudioTag.
IE11 seems to allow fullscreen only via certain events: photonstorm/phaser#1098


**Comment by samme** [comment]
<http://phaser.io/examples/v2/audio/play-music> works in my Safari (v10) but <http://shop.als-dev.de/HTML5games/GoldenKnight3/test.html> doesn't, so I think you're seeing different issues.

When I run <http://shop.als-dev.de/HTML5games/GoldenKnight3/test.html> in Safari the OGG files are added but never loaded because they fail the canPlayAudio check. MP3 files never get added or loaded.

If you still think it's a bug, try to make a minimal test case.

As for the IE11 fullscreen behavior, there doesn't seem to be anything Phaser can do about it. Try the advice in photonstorm/phaser#1098.

**Comment by photonstorm** [comment]
> mhh i get the safari from there: http://www.chip.de/downloads/Safari_27264736.html
> i dont found an more aktuell safari for windows. what version do you use?

Safari for Windows is unsupported by Phaser. It hasn't been updated by Apple in many, many years, and does not support Web Audio, WebGL or lots of the other things Phaser needs. No-one uses Safari for Windows, and it should not be used for testing either, as it is not a replacement for Safari on OS X.

Safari cannot play OGG files. You should use m4a files for Safari.
