### ISSUE TITLE
Error in phaser.comments.d.ts: Phaser.GameObjectFactory#graphics

### ISSUE THREAD

**Issue by Cryt1c** [photonstorm/phaser-ce#167]
According to the documentation http://phaser.io/docs/2.4.6/Phaser.GameObjectFactory.html#graphics the parameter of graphics(x, y, group) should all be optional however in the phaser.comments.d.ts only the group parameter is marked as such.

If you want I can create a pull request to fix this.

`graphics(x: number, y: number, group?: Phaser.Group): Phaser.Graphics;`
should be
`graphics(x?: number, y?: number, group?: Phaser.Group): Phaser.Graphics;`

**Comment by samme** [comment]
Sure, go ahead with a PR.

**Comment by Cryt1c** [comment]
I found more mismatches of the same type for the functions:
image()
rope()
sprite()
text()
graphics()

and creature() is not even in the typing. I might create a PR for this too later on.

PR is incoming but I have a problem with Webstorm. It always deletes the trailing whitespaces from empty block comment lines. Any ideas how to prevent this?

**Comment by samme** [comment]
Make sure you edit [typescript/phaser.d.ts](https://github.com/photonstorm/phaser-ce/blob/master/typescript/phaser.d.ts) and not **typescript/pixi.comments.d.ts**, which is built automatically.

It's fine if the trailing whitespace is removed from comment blocks.

**Comment by Cryt1c** [comment]
I actually wanted to change typescript/phaser.comments.d.ts is this also built automatically?
If then I guess that I just have to run the grunt script to create this file right?

**Comment by Cryt1c** [comment]
I only fixed the issue in typescript/phaser.d.ts for now. Should I do it in typescript/phaser.comments.d.ts too?

**Comment by photonstorm** [comment]
You don't need to manually edit the comments file, just edit phaser.d.ts then use the tsdoc grunt script to build the rest.

**Comment by Cryt1c** [comment]
Alright, I have created the phaser.comments.d.ts using the tsdoc grunt script and commited it too. Thanks for the support!
