### ISSUE TITLE
maxParallelDownloads with HTTP/2

### ISSUE THREAD

**Issue by goldfire** [photonstorm/phaser-ce#170]
I'm wondering why `maxParallelDownloads` is set to such a low limit and can't be changed to be higher than 12. Most browsers now have a limit of 17+ and if you are using HTTP/2 then you can download all of the assets in parallel. So, limiting the number that are downloading in parallel could slow things down fairly significantly unless I'm not understanding the loader correctly.

**Comment by photonstorm** [comment]
Because when the Loader was created we were targeting IE9 (remember that one?) and Android 2, and beyond 4 concurrent downloads would screw them up nicely. It would be trivial to remove the limit entirely, just be aware of repercussions further down the food chain.

**Comment by samme** [comment]
We could certainly raise it to 6, which is the most common browser limit per-host.

**Comment by goldfire** [comment]
I still think there should be a way for the user to remove if they wish to. We are targeting strictly HTTP/2 compliant browsers, and so a limit will just slow our loading down. I get that there is a need to maintain support for older browsers (sadly, I do remember IE9 😆 ), but with widely adopted HTTP/2 support it makes sense to allow other options too.

**Comment by photonstorm** [comment]
I'm sure @samme would gladly merge a PR that offered this change, and retained backward compatibility by default.

**Comment by samme** [comment]
Currently Phaser clamps `maxParallelDownloads` in [1, 12] so a user can do

```javascript
game.load.maxParallelDownloads = 12;
```

We could remove the upper limit of the clamp, keep the current default (4), and advise users to be careful with large values.

**Comment by goldfire** [comment]
@samme Yes, that would make sense to me. I could do a PR for that if needed, although I'm not sure how/where you want to communicate that.

**Comment by samme** [comment]
You can add to the description (JSDoc) in [maxParallelDownloads](https://photonstorm.github.io/phaser-ce/Phaser.Loader.html#maxParallelDownloads). Guess we should remove `@protected` also.

We still need the lower limit so you could clamp between [1, Infinity] or just use `Math.max(1, maxParallelDownloads)`.

**Comment by samme** [comment]
Added in #177
