### ISSUE TITLE
Issue with Bitmap fonts and accented characters

### ISSUE THREAD

**Issue by jansensan** [photonstorm/phaser-ce#176]
Note: This is a port from [issue 2940](https://github.com/photonstorm/phaser/issues/2940). I tested as suggested with the latest release of Phaser CE, which did not fix this issue.

Issue: A bug in the rendering of accented characters of a Bitmap font
Phaser version: 2.7.7
Demo: https://github.com/jansensan/test-phaser-bitmap-font/tree/phaser-ce

There is an issue with certain punctuation characters and accented characters when using Bitmap font:

![image](https://github.com/jansensan/test-phaser-bitmap-font/blob/master/src/assets/issue-screenshot.png?raw=true)

As demonstrated from the image above, many characters are not rendered properly:
- Punctuation: ×÷±–…“”‘’
- Accented A's: àáâäåãāæ ÀÁÂÄÅÃĀÆ
- Accented E's: èéêëėęē ÈÉÊËĖĘĒ
- Accented I's: ìíîï ÌÍÎÏ
- Accented O's: òóôöøõōœ ÒÓÔÖØÕŌŒ
- Accented U's: ùúûüū ÙÚÛÜŪ
- Accented Y's and C's: ÿŸ çÇ

While it is not a guarantee against human error, I have spent a lot of time to ensure this issue does not stem from my code.

- Ensured the font data XML is set to UTF-8
- Wrapped offending characters in `<!CDATA[[]]>`
- Tested the mapping of each characters

This leads me to believe the issue is with the rendering of the characters in the library. However, is it because:

- Accented characters are simply not supported?
- There is a specific way to declare accented characters to display them in Bitmap font?
- An actual omission in the library surrounding those characters?
- Magic?

Thanks for any help you can provide.

**Comment by samme** [comment]
Here's a comparison using `String.fromCharCode`: 
![chicago](https://cloud.githubusercontent.com/assets/435681/25248607/b05832b6-25c3-11e7-9168-daef675c8042.png)

**Comment by jansensan** [comment]
@samme Thanks for posting this. Originally, I thought it was ridiculous to consider using `String. fromCharCode`, as it would be overcomplicated to always split dialogs and other strings into each characters.

However, your image showed some of the characters I couldn't (albeit with some minor visual issues), so I thought there was another way. I tried `String. fromCharCode` and still got an issue, but when I `console.log` the string, the same issue was present.

So it turns out there were two issues:
- minor mis-mapping of characters and their position in the PNG
- the HTML document was missing  `<meta charset="UTF-8">`

![phaser-ce-accented-characters](https://cloud.githubusercontent.com/assets/1410355/25451072/f6428cfc-2a8e-11e7-95b2-4b1cf04b83da.png)

This issue can be closed, as it was actually an error 18. Thanks for taking the time to look into it.
