### ISSUE TITLE
Exception calling PIXI.WebGLGraphics.renderGraphics

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser-ce#178]
I'm receiving automated exception reports and this one is daily frequent:
https://github.com/photonstorm/phaser-ce/blob/master/src/pixi/renderers/webgl/utils/WebGLGraphics.js#L49

Referencing webGL.data causes a TypeError exception (Cannot read property 'data' of undefined).

OS/Browser: Windows 10 with Edge or Chrome, Android 4 with Chrome

**Comment by samme** [comment]
Any idea how it could be reproduced? <https://samme.github.io/phaser-examples-mirror/display/graphics.html> works for me in WebGL mode.

**Comment by vpmedia** [comment]
I could not reproduce the issue yet, anyway I've created a pull request introducing a simple conditional check for the exception cause.
