### ISSUE TITLE
Enable Travis CI builds

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser-ce#183]
It would be useful to have automated builds / tests using Travis CI (.travis.yml is already in place).
It's only required to go to https://travis-ci.org/profile than `Sync account` and finally enable the switch of `photonstorm/phaser-ce`.
I think this is something that @photonstorm can do.

**Comment by samme** [comment]
Is there a way we can run automated tests with a `<canvas>` (still required in HEADLESS mode)? I always got stuck on that part.

**Comment by vpmedia** [comment]
I think with Chrome 59 it's possible with cross-platform headless mode, but I'm not sure.
https://www.chromestatus.com/features/5678767817097216

**Comment by Dreaded-Gnu** [comment]
You might use something like node-canvas, when you want to have the canvas within automated tests.
