### ISSUE TITLE
Image class has animation component

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser-ce#185]
This Issue is about an error in the documentation or in the API (should be decided).

At the page https://phaser.io/docs/2.6.2/index#display for the `Image` class it states:

> A lighter Game Object with a texture and input, but no physics or animation handlers.

But the class documentation at https://phaser.io/docs/2.6.2/Phaser.Image.html states that the `Image` class has a `Phaser.Component.Animation` component.
Also if I check the source code I can see the animation component included.

In my opinion the image class should not include animation.

**Comment by samme** [comment]
I think anything that uses [loadTexture](https://photonstorm.github.io/phaser-ce/Phaser.Component.LoadTexture.html#loadTexture) actually needs the Animation component. It seems to handle frame assignment.

I think in earlier versions Phaser.Image and Phaser.Sprite were more different than they are now.
