### ISSUE TITLE
Killed entity still runs update. Allow group option to change behavior.

### ISSUE THREAD

**Issue by vantreeseba** [photonstorm/phaser-ce#187]
A bug in the API
Phaser version(s): all
Live example: https://codepen.io/anon/pen/rmjVrK
What should happen: Killed entities should not be updated.
What happens instead: Killed entities are updated.

Suggested fix:  Add an option (shouldNotUpdateKilledEntities) to groups to allow users to choose the behavior of entities that are not alive.

The onKilled and onRevive events should be able to handle setting any timers/tweens to fade out corpses/allow resurrection effects and etc.

**Comment by photonstorm** [comment]
This is done by design. If changed it would be a significant alteration, so definitely place it behind a (defaulted off) flag).

**Comment by samme** [comment]
I can add, but I'll probably use `exists` rather than `alive` because `exists` is less ambiguous for non-Sprites.

**Comment by goldfire** [comment]
I agree that there's use-cases either way, so it should certainly be an option so the developer can choose. Defaulting to the current behavior obviously makes sense.

**Comment by samme** [comment]
Pending a code change, you can use

```javascript
Phaser.Group.prototype.update = function() {
  var child, i;
  i = this.children.length;
  while (i--) {
    child = this.children[i];
    if (child.exists) {
      child.update();
    }
  }
};
```

The [docs](https://photonstorm.github.io/phaser-ce/PIXI.Sprite.html#exists) could also clarify the current behavior.

**Comment by vantreeseba** [comment]
This is awesome! Thanks so much.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/gxbZOP>
