### ISSUE TITLE
Error with Phaser SoundManager in IOS 10.3.1

### ISSUE THREAD

**Issue by drewk2525** [photonstorm/phaser-ce#189]
This Issue is about (SoundManager in IOS 10.3.1)

* A bug in the API: It seems that with IOS 10.3.1, when Phaser is waiting for input event to unlock the sound system, it will freeze and throw an error when the touch even is fired.
  * Phaser version(s): V 2.0.4
  * Live example: http://bunny-defender.herokuapp.com/
  * What should happen: When clicking on the screen, the game should play a sound and start.
  * What happens instead: An error is thrown in console
The code base for the example can be found here: https://github.com/eiffelqiu/bunny-defender

I tried to get a smaller version of the code to narrow down a bit exactly where this is happening, but I've been unable to to isolate the error, though this sample is still quite small and simple.

The error I'm seeing is:
TypeError: this._unlockSource.noteOn is not a function. (In 'this._unlockSource.noteOn(0)', 'this._unlockSource.noteOn' is undefined)  unlock — phaser.js 45464
onTouchStart --- phaser.js:22989
_onTouchStart --- phaser.js:22931

This issue seems to occur in IOS 10.3.1 (maybe also 10.3.0) and is independent of the browser being used.  I have been unable to replicate this in any other environments.  There are more details in my post here: http://www.html5gamedevs.com/topic/29846-input-events-in-ios-103/

Please let me know if there is anything else I can do to help with this.

**Comment by samme** [comment]
> The `noteOn()`/`noteGrainOn()`/`noteOff()` methods were the original way to start/stop output in these nodes, and in the newer versions of the specification, the `noteOn()` and `noteGrainOn()` methods were consolidated into a single `start()` method, and the `noteOff()` method was renamed to the `stop()` method.

[Porting webkitAudioContext code to standards based AudioContext](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Porting_webkitAudioContext_code_to_standards_based_AudioContext)

**Comment by samme** [comment]
Not an issue in Phaser CE (or 2.6.2, probably). Just update your Phaser.

**Comment by photonstorm** [comment]
@drewk2525 sorry Drew, I feel a bit guilty because it was my suggestion to open the issue here. I assumed you were using the latest version of Phaser, in which case the error you were getting was certainly a result of the iOS update changing something - however Phaser 2.0.4 is _really_ old. Update it to 2.6.2, or a CE release, and it'll work fine.

**Comment by samme** [comment]
No worries here 😄
