### ISSUE TITLE
Sound duration is zero after loaded and decoded

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser-ce#19]
*Description*
After loading an MP3 sound and waiting for decodedCallback than getting the sound duration returns zero (0) value.

*Affected source*
https://github.com/photonstorm/phaser-ce/blob/v2.7.3/src/sound/Sound.js
(I think the issue covers the same case as handled with CocoonJS, take a look at line 704)

*Environment:*
Phaser: 2.7.3-CE
OS: Windows 7
Browser: Firefox 51 (64-bit)

*Code example*

> preload

    function preload() {
        game.stage.backgroundColor = '#85b5e1';
        game.load.baseURL = 'http://examples.phaser.io/assets/';
        game.load.crossOrigin = 'anonymous';
        game.load.audio('audio_test', 'audio/tommy_in_goa.mp3');
    }

> create

    var audio;
    function create() {
        audio = game.add.audio('audio_test');
        game.sound.setDecodedCallback(['audio_test'], function() {
            console.log(audio.duration);  // BUG: sound  duration is zero (0)!
            audio.play();
            audio.stop();
            console.log(audio.duration);  // BUG solution: sound duration is > 0
        }, this);
    }

http://phaser.io/sandbox/LDjSQJNv

**Comment by vpmedia** [comment]
I forgot to mention the calling `play()` before getting the duration results correctly with the sound duration value.

**Comment by photonstorm** [comment]
Yes, the duration isn't available until after the sound buffer is created (which only happens when you press play). It's not available until that point when using the audio tag either. I guess if you genuinely need it in advance you could create a buffer, load the sound into it, get the duration then delete the buffer again. Still won't work with the audio tag though :(

**Comment by vpmedia** [comment]
Thanks for the response, I think I'll pre-generate the durations into a JSON file.
