### ISSUE TITLE
P2 body and sprite's image appear in different position when i'm using camera

### ISSUE THREAD

**Issue by MarcosGil93** [photonstorm/phaser-ce#192]
This is the code where I initialize the sprite and what's happends on the screen. I try setting offset, but only works if the sprite keeps static.

I have another game, with the same code but without camera, and works correctly.

![initializeball](https://cloud.githubusercontent.com/assets/22937985/25524334/6df23910-2c0a-11e7-8dfa-7c2e2de9f8eb.JPG)
![ballposition](https://cloud.githubusercontent.com/assets/22937985/25524339/7091aa84-2c0a-11e7-84be-eeb1a4ac9bf9.JPG)

**Comment by gaurav-dixitv** [comment]
I suspect this is because you are scaling the camera. Perhaps, try #88 (or setting the `game.camera.scale.setTo(1,1)`).
