### ISSUE TITLE
Calling setUserScale inside setResizeCallback results in an infinite loop

### ISSUE THREAD

**Issue by LandonSchropp** [photonstorm/phaser-ce#197]
Phaser version(s): 2.7.7
Live example: https://codepen.io/LandonSchropp/pen/vmeZXr

### What Should Happen

The documentation for `Phaser.ScaleManager.USER_SCALE` states:

> The game Display is scaled according to the user-specified scale set by setUserScale. This scale can be adjusted in the resize callback for flexible custom-sizing needs.

I'd like to do some custom resizing, and `setResizeCallback` seems to be the say to do it. So I added this to my `create` function:

```
game.scale.scaleMode = Phaser.ScaleManager.USER_SCALE;
      
game.scale.setResizeCallback(() => {
  console.log("RESIZING!");
  game.scale.setUserScale(1.5, 1.5, 0, 0);
});
```

I would expect this to get called when the viewport is resized, adjust the to 1.5 times the default size and then be done.

### What Actually Happens

The resize callback gets caught in an infinite loop. Calling `game.scale.setUserScale(...)` triggers the resize callback, which calls `setUserScale` again, and so on.

### Other Notes

You guys are awesome! Thanks for taking a look.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/VbMWXG>

**Comment by samme** [comment]
This seems to be how it's intended to work, but it's very strange. It does the same thing at least back to v2.4.4.

**Comment by jdnichollsc** [comment]
I'm getting this wrong behavior

@samme but in the docs says: `This is the appropriate place to call setUserScale if needing custom dynamic scaling.`
Check here: https://phaser.io/docs/2.4.4/Phaser.ScaleManager.html#setResizeCallback
What do you think?
