### ISSUE TITLE
emitter setXSpeed/setYSpeed does not work

### ISSUE THREAD

**Issue by xenyou** [photonstorm/phaser-ce#20]
This Issue is about (delete as applicable)

* A bug in the API (always say which version you're using!)

this code does not work correctly. 
particles can not move anywhere. (works in phaser 2.6.2)
```
        this.waterParticle = game.make.bitmapData(2, 2);
        this.waterParticle.rect(0, 0, 2, 2, '#ff0000');
        this.waterParticle.update();

        this.emitter = game.add.emitter(200, 200, 500);
        this.emitter.makeParticles(this.waterParticle);
        this.emitter.setXSpeed(-100, -250);
        this.emitter.setYSpeed(-100, 100);
        this.emitter.setAlpha(0.2, 1);
        this.emitter.flow(500, 20, 2, -1, true);
```

**Comment by xenyou** [comment]
version is 2.7.3

**Comment by samme** [comment]
Works for me: <http://codepen.io/samme/pen/mRKrmG>

**Comment by xenyou** [comment]
Thanks for verifying it.
Hmm, I actually use this template.

https://github.com/lean/phaser-es6-webpack

So maybe this template or I made some mistake.
I'll close this issue.
