### ISSUE TITLE
CE COMPLETELY breaks game.add.text

### ISSUE THREAD

**Issue by WVI** [photonstorm/phaser-ce#208]
This Issue is about
  * Phaser version(s): CE 2.7.8

The Phaser.Text constructor calls setStyle. Here's a snippet of setStyle on 2.6.0: (sorry about the broken code tags, not sure what's up there)

`
   if (update === undefined) { update = false; }

    style = style || {};
    style.font = style.font || 'bold 20pt Arial';
    style.backgroundColor = style.backgroundColor || null;
    style.fill = style.fill || 'black';
    style.align = style.align || 'left';
    style.boundsAlignH = style.boundsAlignH || 'left';
    style.boundsAlignV = style.boundsAlignV || 'top';
    style.stroke = style.stroke || 'black'; //provide a default, see: https://github.com/GoodBoyDigital/pixi.js/issues/136
    style.strokeThickness = style.strokeThickness || 0;
    style.wordWrap = style.wordWrap || false;
    style.wordWrapWidth = style.wordWrapWidth || 100;
    style.maxLines = style.maxLines || 0;
    style.shadowOffsetX = style.shadowOffsetX || 0;
    style.shadowOffsetY = style.shadowOffsetY || 0;
    style.shadowColor = style.shadowColor || 'rgba(0,0,0,0)';
    style.shadowBlur = style.shadowBlur || 0;
    style.tabs = style.tabs || 0;
`
This mistake appears in CE 2.7.8:

`
   if (update === undefined) { update = false; }

    var newStyle = Object.assign({}, style);
    newStyle.font = style.font || 'bold 20pt Arial';
    newStyle.backgroundColor = style.backgroundColor || null;
    newStyle.fill = style.fill || 'black';
    newStyle.align = style.align.toLowerCase() || 'left'; // Cannot read property 'toLowerCase' of undefined
    newStyle.boundsAlignH = style.boundsAlignH.toLowerCase() || 'left'; // Cannot read property 'toLowerCase' of undefined
    newStyle.boundsAlignV = style.boundsAlignV.toLowerCase() || 'top'; // Cannot read property 'toLowerCase' of undefined
    newStyle.stroke = style.stroke || 'black'; //provide a default, see: https://github.com/GoodBoyDigital/pixi.js/issues/136
    newStyle.strokeThickness = style.strokeThickness || 0;
    newStyle.wordWrap = style.wordWrap || false;
    newStyle.wordWrapWidth = style.wordWrapWidth || 100;
    newStyle.maxLines = style.maxLines || 0;
    newStyle.shadowOffsetX = style.shadowOffsetX || 0;
    newStyle.shadowOffsetY = style.shadowOffsetY || 0;
    newStyle.shadowColor = style.shadowColor || 'rgba(0,0,0,0)';
    newStyle.shadowBlur = style.shadowBlur || 0;
    newStyle.tabs = style.tabs || 0;
`

The property won't ever be set to the value after || because it'll hang on reading from undefined. Any game with a Text object in it without a preset style will crash.

**Comment by mikkoh85** [comment]
I guess this is about the same thing. Chrome giving this error at console: 
`
ERROR TypeError: Cannot read property 'toLowerCase' of undefined
    at Phaser.Text.setStyle (phaser.js:55800)
    at new Phaser.Text (phaser.js:55679)
    at Phaser.GameObjectFactory.text (phaser.js:47330)
    at Object.webpackJsonp.210.SimpleGame.create (game.ts:40)
`

**Comment by samme** [comment]
Fixed in #206
