### ISSUE TITLE
 ScaleManager Issues with Google Fonts

### ISSUE THREAD

**Issue by ldd** [photonstorm/phaser-ce#21]
For reference, I posted this [in the forums](http://www.html5gamedevs.com/topic/28180-scalemanager-issues-with-google-fonts/)

I am using the latest phaser ce build, phaser 2.7.3. My target browser is desktop Chrome
 (I don't care much for any other browser, mobile platform, etc)

Explanation of my issue: I have a text, at position (0,0) [Therefore, no possibility of it no being a whole number, etc]. It is not scaling properly. 

=> Minimal fiddle testcase showing my problem: http://jsfiddle.net/1g3cj8md/

=> Expected outcome if game is not scaled: http://jsfiddle.net/encznmqq/1/

Is this a bug? Am I missing anything? Basically, the rendering of a google fonts when the game is scaled seems off. This happens whether you use a pixel-friendly font like VT323 or a more 'normal' font.
I pressume that if this is a bug, it has to do with how scaling manages text. Perhaps a workaround is using other types of fonts?

**Comment by samme** [comment]
@ldd close pls
