### ISSUE TITLE
resizeWorld doesn't work ES6

### ISSUE THREAD

**Issue by jopcode** [photonstorm/phaser-ce#217]
Hi guys, I have a problem, the function "resizeWorld ()" does not work on my game, I have a map created on tiled and its corresponding spritesheet, but this do not show as should on my game.

**My map on tiled:**
![inmap](https://cloud.githubusercontent.com/assets/16161754/26033642/d4ab71f6-38af-11e7-9d74-0ea7aebd817e.PNG)

**And my game running:**
![ingame](https://cloud.githubusercontent.com/assets/16161754/26033643/e042da04-38af-11e7-88e1-bb2fa0f0f266.PNG)

**Index Code:**
```
import Boot from 'states/Boot';
import Preload from 'states/Preload';
import Main from 'states/Main';
import GameOver from 'states/GameOver';

class Game extends Phaser.Game {

	constructor() {
		super(800, 600, Phaser.AUTO, 'content', null);
		
		this.state.add('Boot', Boot, false);
		this.state.add('Preload', Preload, false);
		this.state.add('Main', Main, false);
		this.state.add('GameOver', GameOver, false);

		this.state.start('Boot');
	}

}

new Game();

```
**Main code:**
```
class Main extends Phaser.State {

    create() {
        this.game.physics.startSystem(Phaser.Physics.ARCADE);

        //this.game.add.sprite(0, 0, 'Sky');

        this.map = this.game.add.tilemap('tilemap');
        this.map.addTilesetImage('Tiles', 'tileset');


        this.platforms = this.map.createLayer('Platforms');
        this.platforms.resizeWorld();
        this.platforms.wrap = true;
        this.cursors = this.game.input.keyboard.createCursorKeys();

    }

    update() {
        if (this.cursors.left.isDown) {
            this.game.camera.x -= 8;
        }
        else if (this.cursors.right.isDown) {
            this.game.camera.x += 8;
        }

        if (this.cursors.up.isDown) {
            this.game.camera.y -= 8;
        }
        else if (this.cursors.down.isDown) {
            this.game.camera.y += 8;
        }
    }

}

export default Main;

````

**Preload code:**
```
class Preload extends Phaser.State {

	preload() {
		this.game.load.image('Sky', 'assets/Sky.png');
		this.game.load.tilemap('tilemap', 'assets/Tilemap.json', null, Phaser.Tilemap.TILED_JSON);
		this.game.load.image('tileset', 'assets/Tileset.png');
	}

	create() {
		this.game.state.start("Main");
	}

}

export default Preload;

```

I don' know what happend, any idea? :/ (Sorry for my bad english)

**Comment by samme** [comment]
resizeWorld() resizes `game.world.bounds` to match the layer dimensions. You can check with

    console.log(this.world.bounds);

Can you move the camera around to show the rest of the map?

**Comment by jopcode** [comment]
yes I can, and i can see the rest of the map and `this.world.bounds` gives me this: `Object { x: 0, y: 0, width: 3200, height: 1600, type: 22 }` .

**Comment by samme** [comment]
I think it's working correctly then. You just have a very large map.

You can try

    this.platforms.scale.set(0.25)

to scale it down.

**Comment by jopcode** [comment]
@samme Now it does not show nothing until I move the camera down.

Nothing show:
![nothing](https://cloud.githubusercontent.com/assets/16161754/26037616/31ed1530-38f7-11e7-8617-57c71bbef91f.PNG)

And if I move the camera down:
![someone](https://cloud.githubusercontent.com/assets/16161754/26037615/31bdc276-38f7-11e7-8f54-067033fe98f7.PNG)


The console:
![image](https://cloud.githubusercontent.com/assets/16161754/26037633/6dad180e-38f7-11e7-8099-22cd3f947c0c.png)

**Comment by samme** [comment]
Make sure `scale.set` is before `resizeWorld`.

**Comment by jopcode** [comment]
@samme  ocurrs the same

**Comment by jopcode** [comment]
someone any idea or solution?

**Comment by samme** [comment]
It's possible that scaling TilemapLayers doesn't completely work.

But if your map's pixel dimensions are 3200 × 1600, then resizeWorld() is working correctly.

If you still think it's a bug, please post a working example and explain **exactly** what you think is wrong.
