### ISSUE TITLE
Phaser.Utils.getProperty can return either null or undefined for missing properties

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#218]
getProperty() claims to return null for missing properties but the actual result depends on the chain depth:

```javascript
Phaser.Utils.getProperty({}, 'x');     //-> undefined
Phaser.Utils.getProperty({}, 'x.y');   //-> undefined
Phaser.Utils.getProperty({}, 'x.y.z'); //-> null
```

* A bug in the API:
  * Phaser version(s): 2.7.9 and earlier

**Comment by jbpuryear** [comment]
This function also doesn't work for nested properties that exist.

    var obj = { x: { y: { z: 'foo' } } };

    Phaser.Utils.getProperty(obj, 'x');             //-> Object { y: Object }, This works.
    Phaser.Utils.getProperty(obj, 'x.y');           //-> undefined
    Phaser.Utils.getProperty(obj, 'x.y.z');         //-> undefined
    Phaser.Utils.getProperty(obj, 'x.y.z.j.k.l');    //-> null
