### ISSUE TITLE
Warnings Offscreen-For-WebGL

### ISSUE THREAD

**Issue by Gurigraphics** [photonstorm/phaser-ce#221]
* Phaser version(s): v2.2.2, (...) v2.7.9 
  * Live example: http://codepen.io/photonstorm/pen/VYWZwE
 * Tested in: Google Chrome - Version: 58.0.3029.96 (64-bit)
 
###  Phaser.CANVAS

> [.Offscreen-For-WebGL-0000000005D50740]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command VM161 phaser.min.js:10 
> [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

###  Phaser.AUTO

> [Violation] 'DOMContentLoaded' handler took 269ms
> 2index.html:1 
> [.Offscreen-For-WebGL-00000000072DC4D0]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
> 2index.html:1 
> [.Offscreen-For-WebGL-0000000005D6CD40]GL ERROR :GL_INVALID_ENUM : GetIntegerv: <- error from previous GL command
> index.html:1 
> [.Offscreen-For-WebGL-0000000005D6CD40]GL ERROR :GL_INVALID_ENUM : GetShaderiv: <- error from previous GL command
> 

**Phaser CE v2.7.9 also show this Warnings**

**Comment by samme** [comment]
Check <http://codepen.io/samme/pen/dWjZeL>?

I don't get any WebGL warnings in my Chrome (v58.0.3029.110).

**Comment by Gurigraphics** [comment]
So is Graphics Card?

Firefox 53.0.2 (32-bit)
http://imgur.com/aDRL7OJ.png

Chrome 58.0.3029.96 (64-bit)
http://imgur.com/cZ0XZb6.png

Similar issues:
https://github.com/melonjs/melonJS/issues/827
https://github.com/mapbox/mapbox-gl-js/issues/3312

**Comment by Gurigraphics** [comment]
Realized that this does not evolve Phaser because this minimalist example appears the same.
https://mdn.github.io/webgl-examples/tutorial/sample1/
Maybe it's something from WebGL. Thanks.
