### ISSUE TITLE
Layer undefined when defined a few lines before

### ISSUE THREAD

**Issue by chand1012** [photonstorm/phaser-ce#233]
I am working on a multi-stage platformer game in Phaser. When the code for the first level is loaded on its own using `preload`, `create`, and `update` as a standalone game, the level loads and plays fine. However, when the level is loaded using `game.state`, the console claims `layer is undefined`. Here is the snippet of code for just the level and layer handling:
```javascript
var map;
var layer;
Game.prototype = {
    create: function(){
        map = game.add.tilemap('testlevel');
        map.addTilesetImage('grassland');
        map.setCollisionByExclusion([1]);
        layer = map.createLayer('Tile Layer 1');
        layer.resizeWorld();
    };
};
```

**Comment by chand1012** [comment]
So as it seems, `map.createLayer()` is returning `undefined`. Any ideas?

**Comment by samme** [comment]
createLayer exits early only if the named layer doesn't exist, but in that case you should see a `Invalid layer ID` warning in the console.

**Comment by chand1012** [comment]
I am seeing this, though in the map.json file the layer is called "Tile Layer 1", I don't understand why this is happening. This doesn't happen when I am not using game states.

**Comment by rblopes** [comment]
Hi there.

I read your [forum post][0], I [forked][1] and edited your gists ([1][2], [2][3]), I tested them locally and didn't notice anything wrong. Though I believe those are not the actual code you're using, I'm sure it has nothing to do with splitting your code into game states.

@samme The warning message always reads "`Invalid layer ID given: null`". Please, [take a look][4].

[0]: http://www.html5gamedevs.com/topic/30642-mapcreatelayer-returning-undefined/
[1]: https://gist.github.com/rblopes/837bf399739ec64db7546158e33dc2b0
[2]: https://gist.github.com/chand1012/4dfbc922499a3072bdc955a52e87f5de
[3]: https://gist.github.com/chand1012/aa16cab8c5f3beb1babcab4bd5264e51
[4]: https://github.com/photonstorm/phaser-ce/blob/1a603a43bc7acd7dd5bbd7319350eff73f1468af/src/tilemap/Tilemap.js#L588-L599

**Comment by chand1012** [comment]
The thing that confuses me is that the level works fine when on its own, like it runs and everything, [here](https://gist.github.com/chand1012/3665acc15f00ec94a126f8dac0058e06) is the exact code.

**Comment by samme** [comment]
You can verify the layer names with

    console.log(map.layer);
    console.log(map.layers);

**Comment by chand1012** [comment]
For some reason, though in the file the layer name was `Tile Layer 1`, Phaser showed the name being just `layer`, and the map doesn't show up at all, just the background.

**Comment by Nodragem** [comment]
Hello,

Why is that "not a Phaser bug"? 

I am running into the same problem, after I ran `game.add.tilemap(level_key);`, Phaser does not parsed the layers correcly. The only layer in the returned tilemap is the default `layer`, so that when I call `createLayer(layer_name)`, I receive the error: `Invalid layer ID given: null`.

@chand1012 what was your solution?

I am on Phaser 2.6.2, though.

**Comment by Nodragem** [comment]
I found out what was wrong, I forgot to specify `Phaser.Tilemap.TILED_JSON`. I can't believe I wasted 1 hour on such a mistake :D After that, I still had issues, such that I needed to embed the tilesets in the .json, etc... but everything ended up well :)
