### ISSUE TITLE
text style strokeThickness breaks text if entered as a string

### ISSUE THREAD

**Issue by netgfx** [photonstorm/phaser-ce#239]
```var label = this.add.text(0, 0, "Battle type: " + this.battleInfo.type, {
            font: "36px alegreyaregular",
            wordWrap: true,
            wordWrapWidth: 400,
            fill: "#000000",
            stroke: "#f1f1f1",
            strokeThickness: 2
        });
```
this produces a `Phaser.Text` with width: `400` and height: `55` all good
while this:
```var label = this.add.text(0, 0, "Battle type: " + this.battleInfo.type, {
            font: "36px alegreyaregular",
            wordWrap: true,
            wordWrapWidth: 400,
            fill: "#000000",
            stroke: "#f1f1f1",
            **strokeThickness: "2"**
        });
```
produces a Phaser.Text with width: `20000` and height: `4000`

I understand that it should be a number, but it fails with no errors or any indication that this is whats causing the issue. Should I make a PR or is it too trivial and should be left to the coder to figure it out?

Thanks.

**Comment by samme** [comment]
I think it's worth a change.

One approach would be

    // @ Phaser.Text#setStyle
    newStyle.strokeThickness = Number(style.strokeThickness) || 0;

    // @ Phaser.Text#strokeThickness
    this.style.strokeThickness = Number(value);

**Comment by netgfx** [comment]
Agreed, how do we proceed?

**Comment by samme** [comment]
You can make a PR, or I can make the change myself later, whichever you prefer.

**Comment by netgfx** [comment]
I'll attempt a PR

**Comment by netgfx** [comment]
did the PR https://github.com/photonstorm/phaser-ce/pull/240

One slight concern I have is how it will handle `NaN`, but that problem pro-exists this issue.
