### ISSUE TITLE
grid creation fails

### ISSUE THREAD

**Issue by shunsei** [photonstorm/phaser-ce#241]
This Issue is about (✏️ delete as applicable)

* A bug in the API:
  * Phaser version(s): 2.7.10
  * Live example: https://codepen.io/anon/pen/MmdPOe?editors=0010
  * What should happen: grid should be created
  * What happens instead:

```
var grid = this.game.create.grid('grid', this.game.width, this.game.height, 32, 32, 'white');
this.add.sprite(0, 0, grid);
```

Results in:

```
Phaser.Cache.addImage: Image "grid" hasn't been retrieved yet
Phaser.Frame: Frame "undefined" has a width or height of zero
```

This seems to work *sometimes* though. In my own code in Firefox it works without console open, whereas in Chromium it works only with console open. May be a timing-related issue.

**Comment by samme** [comment]
This is another consequence of #136. Guess we need to add a callback here as well.

**Comment by samme** [comment]
Also in Phaser.Create#texture.
