### ISSUE TITLE
Camera shake not reset on state change

### ISSUE THREAD

**Issue by jbpuryear** [photonstorm/phaser-ce#246]
* A bug in the API:
  * Phaser version(s): 2.8.0
  * Live example: [https://codepen.io/jbpuryear/pen/KqKxEX?editors=0010](https://codepen.io/jbpuryear/pen/KqKxEX?editors=0010)
  * What should happen: Camera should shake awhile and then reset with red rectangle filling the view.
  * What happens instead: Camera shake doesn't reset on state change and camera stays off center.

Camera's position doesn't get reset if a state change interrupts a camera shake.

**Comment by rblopes** [comment]
A simple workaround is to reset the internal shake property coordinates to zero when the state is starting ─ probably what [`Phaser.Camera#resetFX()`](https://github.com/photonstorm/phaser-ce/blob/0cf388e48e8957eee381aaef4f87465d07c94cda/src/core/Camera.js#L787-L797) implementation is missing.

```javascript
this.camera._shake.x = 0;
this.camera._shake.y = 0;
```

**Comment by jbpuryear** [comment]
camera.fx is where the camera flash lives and doesn't seem to have anything to do with the shake. There's already a line in Camera.reset that sets shake._duration to 0, so I'm submitting a pull request to add those lines there instead.
