### ISSUE TITLE
Mouse button is "down" even after Ctrl+left click is released

### ISSUE THREAD

**Issue by Oli4242** [photonstorm/phaser-ce#250]
To reproduce the bug:
1. go to: https://phaser.io/examples/v2/input/mouse-buttons
2. hold `ctrl` down and left click then release everything
3. Phaser (both 2.7.x and 2.8.0) acts as if right click was held down until you move the mouse outside the canvas

I've tried only with Firefox and Opera on Windows 10.

**Comment by samme** [comment]
I think this may be Phaser's intended behavior for a single-button mouse.

**Comment by photonstorm** [comment]
Yeah, it's how you right-click on OS X trackpads.

**Comment by Oli4242** [comment]
Yeah I know Phaser "convert" ctrl+click to right click. But once the mouse and/or ctrl is released it shouldn't detect a click anymore, right?

**Comment by samme** [comment]
Oh, mine does that two (with `Left Button: true`), but I think that's because the browser context menu appears.

If that happens with yours too, you can try disabling the context menu. I thought Phaser had a way to do that but I don't see it now.

**Comment by Oli4242** [comment]
Actually I get no context menu. I just get `Right Button: true` even after I release the buttons. The only way for me to get it back to `false` is to move the mouse outside the canvas or make a "real" right-click...

It's weird you don't get the same bug as me. Have you tried it on Windows?

I'll try to investigate the source code to see if I can find something...

**Comment by Oli4242** [comment]
I guess I've fond the issue.

In `Phaser.Pointer#updateButtons` ([here](https://github.com/photonstorm/phaser-ce/blob/release-2.8.0/src/input/Pointer.js#L570)):
```js
    if (event.buttons === 1 && event.ctrlKey && this.leftButton.isDown)
    {
        this.leftButton.stop(event);
        this.rightButton.start(event);
    }
```

From what I understand, when both ctrl and the left button are pressed the `leftButton` event is stopped and the `rightButton` event is artifically started instead. So when the left button is released nothing stops the `rightButton` event (on non-OSX platforms at least)

I can't think of an easy solution right now... Any idea?

**Comment by samme** [comment]
It seems Phaser.Pointer#processButtonsUp should catch the button release in any case, I wonder why that's not happening.

**Comment by 2called-chaos** [comment]
@samme #318 will fix that, it seems someone didn't "upgrade" processButtonsUp when that someone gave processButtonsDown a makeover. Note: In order for the fix to work in chrome `game.input.mspointer.capture = false;` must be set as well (other bug).

If you take the pen, use the JS linked in the PR and disable mspointer capture the problem is resolved.
