### ISSUE TITLE
sprite.worldPosition is NaN at the start of the game => game.camera breaks

### ISSUE THREAD

**Issue by saw235** [photonstorm/phaser-ce#254]
* A bug in the API: 
  * Phaser version(s): 2.8.0
  * What should happen: camera.follow() doesn't break like phaser 2.6.2
  * What happens instead:  camera breaks, life is hard

This can be traced all the way back to pt.tx from UpdateTransform, which is NaN for some reason at the start when calling PIXI's matrix() method => causing game.camera.update() to not update properly if camera.follow(target) is called at that time. (at line 27362 camera.update())

        this.displayObject.position.x = -this.view.x;
        this.displayObject.position.y = -this.view.y;
which is dependent on target's worldPosition.x and worldPosition.y

I fixed this by changing the following lines in updateTransform line 14107 

        this.worldPosition.x = wt.tx;
        this.worldPosition.y = wt.ty;
to

        this.worldPosition.set(wt.tx, wt.ty);

which is what is used in Phaser 2.6.2. This prevents worldPosition.x and worldPosition.y from being set to NaN

Broke my game  :(

**Comment by samme** [comment]
Can you post a runnable example?

[camera/basic follow](https://samme.github.io/phaser-examples-mirror/camera/basic%20follow.html) seems to work correctly.

**Comment by samme** [comment]
Can't reproduce this one. 🙁
