### ISSUE TITLE
how to force render in Landscape mode on Mobile browsers

### ISSUE THREAD

**Issue by sophister** [photonstorm/phaser-ce#256]
This Issue is about (✏️ delete as applicable)

* A problem with my own code

hi, is there any method or config I can use, to force game render in landscape mode, because my game only works in landscape.

I've tried to the following, but NOT work:

* rotate `canvas` element myself
* set `game.world.angle`

is there something I've missed? thx

**Comment by samme** [comment]
Phaser doesn't provide this, but in [supported browsers](http://caniuse.com/#feat=screen-orientation), you can try

    screen.orientation.lock('landscape');

**after** the game has entered fullscreen.

Phaser does provide orientation change signals that you can use to show user hints; see <https://github.com/photonstorm/phaser-ce/blob/master/resources/Project%20Templates/Full%20Screen%20Mobile/src/Boot.js>
