### ISSUE TITLE
Canvas mousemove event no longer firing when mouse is down

### ISSUE THREAD

**Issue by redgetan** [photonstorm/phaser-ce#265]
On version 2.8.0, mousemove event is not being fired when mouse is held down. What I want to do is read a player's mouse-pointer based 'aim target' even when the player is firing bullets (mouse is held down). An live example of the bug can be seen here (https://jsfiddle.net/yr0vco9r/1/). 

You can see the expected correct behavior by switching the javascript include from phaser-ce@2.8.0 to phaser@2.6.2

**Comment by photonstorm** [comment]
Strange, I've not checked your example yet but if that was true then things like dragging sprites would no longer work, and I used that in a game just this week. Maybe implementation specific. Will have a look.

**Comment by photonstorm** [comment]
Ok looked at the example - why are you using an event listener on the canvas as opposed to the move events built in?

**Comment by samme** [comment]
Seems to be Chrome only.

**Comment by redgetan** [comment]
The original reason why i used canvas listener was so that I won't have to do change anything if I don't use phaser (reduce coupling). 

But, I just tried `game.input.addMoveCallback` and it works, so I guess i'll just use that :)

**Comment by 2called-chaos** [comment]
@samme This is related to mspointer and him using mouse events which get captured. Can you add a mspointer tag please? :>

Fix is to use game events or `game.input.mspointer.capture = false;` but the first is better.

**Comment by samme** [comment]
Yes, this is because Phaser.MSPointer suppresses the corresponding `mousemove` event (from `pointermove`) when `capture` is on.

If you want to use a native event, you can do `game.input.mspointer.stop()` and then listen for `mousemove`.
