### ISSUE TITLE
Memory leak in Phaser.Utils.Debug.boot

### ISSUE THREAD

**Issue by johnbuttcoingalt** [photonstorm/phaser-ce#269]
This Issue is about 

* A bug in the API:
  * Phaser version(s): 2.6.x and later, possibly earlier as well
  * What should happen: Canvas added to Phaser.CanvasPool should be reused or deleted
  * What happens instead:  By default a new canvas is created every time a new Phaser.Game instance is created and it is never deleted

A trivial example illustrating the problem is below.  Click on the button to create a new Phaser.Game instance, click again to delete it.  Repeatedly clicking causes memory usage to go up without bound because Phaser.CanvasPool.pool grows without bounds.  This memory is never freed by garbage collection, either by waiting or by manually forcing garbage collection (e.g. by using Chrome's dev tools).

    <!doctype html>
    <html>
    <head>
    <meta charset="UTF-8"/>
    <title>test</title>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/phaser-ce/2.8.1/phaser.js"></script>
    </head>
    <body>
    <button id="button">Click</button>
    <div id="canvas"></div>
    <script>
    window.onload = function() {
        var d, n, game;

        d = document.getElementById('button');
        n = document.getElementById('canvas');

        function preload() {
        }
        function create() {
        }
        function update() {
        }
        function handler() {
                if(game) {
                        game.destroy();
                        game = null;
                } else {
                        game = new Phaser.Game({
                                width:          800,
                                height:         600,
                                renderer:       Phaser.AUTO,
                                parent:         n,
                                state:          {
                                        preload:        preload,
                                        create:         create,
                                        update:         update
                                },
                        });
                }
        }
        d.onclick = handler;
    };
    </script>
    </body>
    </html>

Simply adding enableDebug: false; to the instance configuration prevents the memory leak, as it prevents Phaser.Utils.Debug.boot() from being called.  This works as a crude hack but is presumably not the desired behaviour, particularly since debugging (and therefore the memory leak) is enabled by default.

Problem affects all Phaser.Game instances where debugging is enabled (which is the default) and game.renderType !== Phaser.CANVAS.  Problem will be hidden in usage cases where multiple instances of Phaser.Game aren't created over the lifetime of the document.

**Comment by samme** [comment]
It looks like Debug#destroy is never called: <https://codepen.io/samme/pen/GEyOrL>

For now you can call `game.debug.destroy()` yourself when destroying the game.
