### ISSUE TITLE
Unable to play video inside cordova-android

### ISSUE THREAD

**Issue by math3os** [photonstorm/phaser-ce#271]
I have setup a [test app ](https://github.com/math3os/test_phaser_video_cordova) to confirm this issue. 

I had put a simple call to phaser's video constructor with a video from phaser's example.
It works with cordova-browser but not with android.

There is the content of web console :   

```
deviceready index.js:30
Phaser CE v2.8.1 | Pixi.js | Canvas | HTML Audio     http://phaser.io â™¥â™¥â™¥ phaser.js:34994
Phaser.Frame: Frame "undefined" has a width or height of zero phaser.js:70657
Phaser.Frame: Frame "undefined" has a width or height of zero phaser.js:70657
```

### Edit : 
cocoon.io and crosswalk had been tried and give no success for this bug.  The only thing who work is to put a video canvas over phaser canvas.

**Comment by samme** [comment]
Have you tried tracing backwards from the _Frame "undefined"_ warning?

**Comment by math3os** [comment]
No, finally, we created a <video> tag outside of and moved it over <canvas> at the right position with css.

**Comment by Habared** [comment]
I've got the same problem.

- Cordova Android 6.3.0
- CrossWalk 2.30
- Phaser CE 2.9.3

Video plays with any problems inside <video> tag, inside Phaser I get a black screen and the following javascript error:

Phaser.Frame: Frame "undefined" has a width or height of zero      phaser-ce-2.9.3.js:71811 
Phaser.Frame: Frame "undefined" has a width or height of zero      phaser-ce-2.9.3.js:71811

**Comment by samme** [comment]
> Phaser.Frame: Frame "undefined" has a width or height of zero phaser-ce-2.9.3.js:71811

Can you trace backwards from there?

**Comment by Habared** [comment]
Phaser.Frame (phaser-ce-2.9.3.js:71811)
Phaser.Video (phaser-ce-2.9.3.js:106284)
video (phaser-ce-2.9.3.js:48765)
create (home.js:119)
loadComplete (phaser-ce-2.9.3.js:29322)
preUpdate (phaser-ce-2.9.3.js:29097)
updateLogic (phaser-ce-2.9.3.js:36033)
update (phaser-ce-2.9.3.js:35980)
updateRAF (phaser-ce-2.9.3.js:64075)
Phaser.RequestAnimationFrame.start._onLoop (phaser-ce-2.9.3.js:64058)


@home.js:119
`this.video = game.add.video('myvideo');`

@/build/phaser.js:106284:
`this.textureFrame = new Phaser.Frame(0, 0, 0, this.width, this.height, 'video');`

this.width and this.height are both 0.

@/build/phaser.js:106251-106252
```
this.width = this.video.videoWidth;
this.height = this.video.videoHeight;
```

videoWidth and videoHeight are both 0.

It seems that width and heigth cannot be read from video....

**Comment by samme** [comment]
Can you see what is `video.video.readyState`?

**Comment by Habared** [comment]
@/build/phaser.js:106251-106252
just before this.width = this.video.videoWidth;
this.video.readyState is 4

**Comment by Habared** [comment]
It worth mentioning that inside play() method videoWidth and videoHeight have correct values.

**Comment by samme** [comment]
It's certainly weird.

You could try overwriting Phaser.Video() with a modified version that lets you pass width and height properties.
