### ISSUE TITLE
When using pointer lock, mousedown and mouseup events are triggered double

### ISSUE THREAD

**Issue by rodri042** [photonstorm/phaser-ce#272]
To reproduce this bug:

https://codepen.io/anon/pen/wemJEg
or
```html
<html>

<script src="http://cdn.jsdelivr.net/npm/phaser-ce@2.8.0/build/phaser.js"></script>

<script>
	var game = new Phaser.Game(300, 300, Phaser.CANVAS, 'phaser-example', { create: create, render: render });

	function create() {
		game.input.onDown.add((event) => {
			console.log("DOWN", event);
			if (!game.input.mouse.locked) game.input.mouse.requestPointerLock();
	  	});

		game.input.onUp.add((event) => {
			console.log("UP", event);
		});
	}


	function render() { }
</script>
</html>
```

The callbacks are called twice for every event.

**Comment by samme** [comment]
Does <https://phaser.io/examples/v2/input/pointer-lock> do the same?

**Comment by rodri042** [comment]
@samme No, because the problem is with **game.input.onDown.add** and **game.input.onUp.add**. My game needs to track both key up and downs, and **addMoveCallback** doesn't give that info.

**Comment by samme** [comment]
I get just one event: <https://codepen.io/samme/pen/BZrWZj>

**Comment by rodri042** [comment]
Ok, so the problem is doing `requestPointerLock()` onside `onDown

**Comment by samme** [comment]
I don't know, I used it because <https://phaser.io/examples/v2/input/pointer-lock> does. :)

**Comment by rodri042** [comment]
@samme just double checking...

I couldn't solve this problem yet. Are you sure that your original example from:
> I get just one event: https://codepen.io/samme/pen/BZrWZj

is really **locking the mouse**? I think that the:
```coffee
game.canvas.addEventListener 'mousedown', -> game.input.mouse.requestPointerLock()
```
never gets called.

For what I'm experimenting the bug is: *"When the pointer lock is on, the events are fired by duplicates"*.

---

Also I've found that some mouse events **are wrong**. Here's another repro logging the `button` property: https://codepen.io/anon/pen/eRxWgq

If I do: `left click down - right click down - left click up`, I get an invalid event:
```
down 0
down 0
down 2
down 2
up 2 << this never happened!!
up 0
```

**Comment by samme** [comment]
For me <https://codepen.io/samme/pen/BZrWZj> seems to be locking the mouse (after clicking on the canvas once). The cursor is hidden and I get a browser message.

**Comment by rodri042** [comment]
Ok, in Firefox seems to work but in Chrome (tested in 56 and the last stable 56.0.2924.87 (64-bit)) it does not lock the mouse :no_mouth:

**Comment by samme** [comment]
Aha, use `click` for Chrome: <https://codepen.io/samme/pen/BZrWZj>. Seems it doesn't fire `mousedown`.

**Comment by rodri042** [comment]
But with the link you just sent I get repeated events :cry:

**Comment by rodri042** [comment]
I managed to get rid of the problem, caching the state of the pressed buttons and using `leftButton`, `middleButton` and `rightButton` properties. 

```js
class MouseInput {
	constructor(game, onMouseMove, onMouseDown, onMouseUp) {
		this.game = game;

		this.onMouseMove = onMouseMove;
		this.onMouseDown = onMouseDown;
		this.onMouseUp = onMouseUp;
		this._pressed = [false, false, false];
	}

	listen() {
		const mouse = this.game.input.mouse;

		this.game.input.onDown.add((event) => {
			const wasPressed = this._updatePressedState(event);
			const shouldFireEvent = !wasPressed && this._pressed[event.button];
			if (!shouldFireEvent) return;

			if (!mouse.locked) return mouse.requestPointerLock();
			this.onMouseDown(event.button);
		});

		this.game.input.onUp.add((event) => {
			const wasPressed = this._updatePressedState(event);
			const shouldFireEvent = wasPressed && !this._pressed[event.button];
			if (!shouldFireEvent) return;

			if (!mouse.locked) return;
			this.onMouseUp(event.button);
		});

		this.game.input.addMoveCallback((pointer, x, y, click) => {
			if (click || !mouse.locked) return;
			this.onMouseMove(mouse.event.movementX, mouse.event.movementY);
		});
	}

	_getButton(event) {
		return event.button === 0
			? event.leftButton
			: (
				event.button === 2
					? event.rightButton
					: event.middleButton
			);
	}

	_updatePressedState(event) {
		const wasPressed = this._pressed[event.button];
		this._pressed[event.button] = this._getButton(event).isDown;
		return wasPressed;
	}
}
```
