### ISSUE TITLE
Phaser doesn't load external tilesets (TSX)

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#273]
> [I]f you save the map as JSON and the external tileset you saved was using the TSX format, the JSON map will contain a reference to the TSX file. (bjorn/tiled#1091)

With these maps Phaser.TilemapParser.parseTiledJSON will fail with "Uncaught TypeError: Cannot read property '2' of undefined". The next Phaser CE release will give a more helpful error message.

The solution is to use the **Embed Tileset** button and reexport the map:

![The 'Embed Tileset' button is at the bottom left of the 'Tilesets' panel.](https://user-images.githubusercontent.com/435681/27773861-6bb28e0a-5f38-11e7-8cab-1c009772cc9e.png)

**Comment by samme** [comment]
Addressed in 24086a972e5dc37efd2032045352ea5ac6af6b13.

**Comment by samme** [comment]
In Tiled 1.2 you can also set **Embed tilesets** in [export options](https://doc.mapeditor.org/en/stable/manual/preferences/#export-options).

**Comment by sanket143** [comment]
still facing this issue with `v3.54.0`

**Comment by photonstorm** [comment]
@sanket143 wrong repo, this is for Phaser 2. And this isn't an issue, either. We're never supported external tilesets in the Tiled loader and have no intention of adding it. The workaround is trivial to implement.

**Comment by djfariel** [comment]
@photonstorm So what's the workaround?

**Comment by samme** [comment]
You have to embed the tileset instead (see above).

**Comment by djfariel** [comment]
@samme Not much of a workaround when using multiple tilemaps that share tilesets, at least as far as my rather limited understanding is concerned. 

The tilesets are loaded for each tilemap. We're using a fixed-origin chunk-based system for "infinite expandability" in our map. Our overall map is split in to tilemaps of 64x64 tiles, which are streamed in and out based on player position. There are 9 of these loaded at any given time, thus 9x the tilesets loaded as well. It would be beneficial to have an workaround the doesn't involve copying the embedded tilesets in to every chunk...

Any ideas?

**Comment by madmarcel** [comment]
For anyone googling this error: if you are getting this error (in phaser 2 or 3), it means there is a reference in your tiled map to an unembedded tilemap. 
Either delete the tilemap in Tiled, or find the tiny toggle underneath the tilemap to embed it.
