### ISSUE TITLE
Typescript definitions is not working as it should

### ISSUE THREAD

**Issue by dolanmiu** [photonstorm/phaser-ce#276]
This Issue is about (✏️ delete as applicable)

* An error in the TypeScript defs
  * Phaser version(s): 2.8.1 and below
  * What should happen: Type definitions should just work OOTB without the need of third party libraries (typings)
  * What happens instead: You need to install `typings` and another dependency

From reading the below, its best practice to include a `"types:"` section in the package.json to make it work out of the box:

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

### Including declarations in your npm package
If your package has a main `.js` file, you will need to indicate the main declaration file in your `package.json` file as well. Set the __`types`__ property to point to your bundled declaration file. For example:

```json
{
    "name": "awesome",
    "author": "Vandelay Industries",
    "version": "1.0.0",
    "main": "./lib/main.js",
    "types": "./lib/main.d.ts"
}
```

**Comment by samme** [comment]
@dolanmiu have you noticed any difference since v2.8.2?

**Comment by dolanmiu** [comment]
I will try 2.8.2 tonight, still using 2.8.1
