### ISSUE TITLE
'Default' and 'missing' textures can be missing from cache when game starts  

### ISSUE THREAD

**Issue by johnbuttcoingalt** [photonstorm/phaser-ce#280]
A race condition exists due to how Phaser.Cache.addDefaultImage() creates the special __default image.

This issue appears to affect Chrome but not Firefox.

The __default image is created as a new Image(), and added to the cache in the image's onload() method.  Since this is done completely asynchronously any newly-started game which does something which relies on the __default image existing may throw an error if it executes prior to the image's onload() finishing.

Below is a trivial but complete example illustrating the problem.  Clicking the button creates a new Phaser.Game instance if one doesn't already exist, or destroys the existing instance if there is one.  The first time the game is created it works as expected but subsequent instances immediately fail on the error "Cannot read property base of null" on line 60273 of the uncompressed 2.8.1 phaser.js.  This is because the example in question attempts to create a tile sprite, and Phaser.TileSprite() assumes game.cache.getImage('__default', true) will always return non-null, which it will not be if onload() for the image created by Phaser.Cache.addDefaultImage() hasn't completed.

     <!doctype html>
     <html>
     <head>
     <meta charset="UTF-8"/>
     <title>test</title>
     <script src="http://cdnjs.cloudflare.com/ajax/libs/phaser-ce/2.8.1/phaser.js"></script>
     </head>
     <body>
     <button id="button">Click</button>
     <div id="canvas"></div>
     <script>
     window.onload = function() {
             var d, n, game;
             var imgData = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAABmJLR0QA/wD/AACNv0geAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4AYIFzY3uKzt4gAAAJlJREFUSMftldsKACEIRDX8/1+efViIyM2s7UKQRG+ljp2JiUAzI9DkWJsAYIAnJmDGncH+Icd9VPAFbXsC0UMu4ZYO34+kaJIBLp3vQL1Nog6zyp+pUb5Hxjpow/1O/AVGcZqKuCQfmMDmQIMiTe+kers+mH/67/q8qI+S4Cwz/eyMPrREwelosTkbNC2A/Gd1Kcnaac63igdzJl46JOj1wQAAAABJRU5ErkJggg==';
      
             d = document.getElementById('button');
             n = document.getElementById('canvas');
      
             function preload() {
                      game.load.image('foo', imgData);
             }
             function create() {
                      var sp;
      
                      sp = game.add.tileSprite(0, 0, game.world.width,
                              game.world.height, 'foo');
              }
              function update() {
              }
              function handler() {
                      if(game) {
                             game.destroy();
                             game = null;
                     } else {
                             game = new Phaser.Game({
                                      width:          800,
                                      height:         600,
                                      renderer:       Phaser.AUTO,
                                      parent:         n,
                                      enableDebug:    false,
                                      state:          {
                                              preload:        preload,
                                              create:         create,
                                              update:         update
                                      },
                               });
                     }
             }
             d.onclick = handler;
      };
      </script>
      </body>
      </html>

The race condition can be shown to be the source of the problem by putting the game's create() method in a zero-length setTimeout() wrapper:

             function create() {
                     setTimeout(function() { crudeHack(); }, 0);
             }
             function crudeHack() {
                     var sp;
     
                     sp = game.add.tileSprite(0, 0, game.world.width,
                             game.world.height, 'foo');
             }

There is a similar race condition in Phaser.Cache.addMissingImage() but I don't have a working example to illustrate it.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/GEPLMj?editors=1000>

In #138 `__default` and `__missing` were guaranteed to be in the cache but not necessarily valid. After #140 etc. they're guaranteed to be valid but not necessarily in the cache by the time your state starts.

**Comment by samme** [comment]
A workaround is to wait for these images in a Boot state: <https://codepen.io/samme/pen/QgYbrP>

**Comment by samme** [comment]
Try attached: [phaser-test-v2.8.1-42-g21613be15.zip](https://github.com/photonstorm/phaser-ce/files/1143847/phaser-test-v2.8.1-42-g21613be15.zip)

I'm a little worried about holding up the game boot indefinitely.

**Comment by johnbuttcoingalt** [comment]
That works, but once you're going that route I'm not sure why you're pushing _pendingCount logic into update() instead of splitting the boot process into two stages.  The stuff below is just a untested sketch---untested, undebugged, probably contains errors---but I think it illustrates what I mean.  Instead of manually twiddling a counter you're using a method that handles the bookkeeping and invokes the second stage of the boot process when async loaders are completed.  A watchdog timer makes sure that we don't space out and never finish booting if the loaders get wedged somehow.

I really don't know enough about the Phaser internals to know if this sort of approach makes sense in the bigger picture, but from the standpoint of what I as a developer expect the lifecycle to look like.  That is, all the internal setup nonsense is already taken care of before things are handed off to any of my (as a developer) game-specific code.

    this.asyncTimeout = 2000;
    this._pendingTotal = 0;
    this._pendingCount = 0;

    addImageAsync: function(key, src, callback) {
           ...
           cache.addPending();
           img.onload = function() {
                ...
                cache.clearPending();
           }
           ...
    },
    addPending: function() {
         this._pendingTotal += 1;
    },
    clearPending:  function() {
         this._pendingCount += 1;
         this.checkPending();
     },
     checkPending: function() {
         // We do it this way to prevent a quickly-exiting early async load that finishes before we start
         // a later async load from confusing us into booting early
         if((this._pendingCount === this._pendingTotal) && (Phaser.Game.bootStarted === true)) {
              Phaser.Game.bootReady();
         }
    },
    ...

     boot: function() {
           var that;

           if(this.bootStarted === true) {
                return;
           }

           // start async loaders, do static declarations, and other stuff at the top of the current boot() method

           // IMPORTANT:  set flag *after* async loads have started to prevent race condition with async
           // processes twiddling your pending counter
           this.bootStarted = true;
           // Call checkPending() after setting bootStarted in case we've managed to run all our async
           // loads before we even got here
           this.checkPending();

           // Watchdog for our async loaders.  If everything is working then the isBooted flag
           // will be set before we're called.  If it isn't, scream in panic then punt and hope for
           // the best
           that = this;
           setTimeout(function() {
                   if(that.isBooted !== true) {
                        // There be trouble ahead
                        console.error('Async loading failed');
                        that.bootReady();
                   }
           }, this.asyncTimeout);
     },
     bootReady: function() {
           if((this.bootStarted !== true) || (this.isBooted === true)) {
                return;
           }
           this.isBooted = true;
           // call other components' boot() methods, start RequestAnimationFrame() loop
           // and rest of stuff from the bottom of the current boot() method
     },
