### ISSUE TITLE
cacheAsBitmap / generateTexture offset sprite positions

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser-ce#283]
This is an underlying PIXI issue i believe. However its good to notify in the docs that those methods `cacheAsBitmap / generateTexture` are offsetting sprite positions. The reason is that transparent pixels around graphics are cut automatically, and therefore the sprite positions get shifted. This happens since 2.3 up to 2.8.1

So the docs should give a warning i believe.

**Comment by samme** [comment]
I've noticed this with `graphics.generateTexture()`.

It happens with `group.cacheAsBitmap = true` also?

**Comment by fyyyyy** [comment]
I havent tried with a group but it happens with sprites that have children.
I have seen bug reports of this happening with groups.
https://github.com/photonstorm/phaser/issues/1925
