### ISSUE TITLE
Typescript compilation errors: Cannot find name 'object'

### ISSUE THREAD

**Issue by cloakedninjas** [photonstorm/phaser-ce#285]
This Issue is about
* An error in the TypeScript defs

```
Using tsc v1.8.9
node_modules/phaser-ce/typescript/phaser.comments.d.ts(16076,24): error TS2304: Cannot find name 'object'.
node_modules/phaser-ce/typescript/phaser.comments.d.ts(22150,29): error TS2304: Cannot find name 'object'.
node_modules/phaser-ce/typescript/phaser.comments.d.ts(22163,25): error TS2304: Cannot find name 'object'.
node_modules/phaser-ce/typescript/phaser.comments.d.ts(22163,56): error TS2304: Cannot find name 'object'.
node_modules/phaser-ce/typescript/pixi.comments.d.ts(1787,31): error TS2304: Cannot find name 'object'.
```

Related: https://github.com/Microsoft/TypeScript/issues/14647

Will submit a PR to resolve shortly...

**Comment by cloakedninjas** [comment]
On closer inspection, this isn't a simple case of changing `@param {object}` to `@param {Object}`...

The Typescript version is quite old here, `1.4.1`, bumping to latest version and running `grunt tsdocs` bombs out with 

```
Warning: Cannot read property 'text' of undefined Use --force to continue.
```

Will need a deeper investigation

**Comment by cloakedninjas** [comment]
Upon further investigation the error is cause by:
`IdentifierObject.TokenOrIdentifierObject.getText` in `node_modules/typescript/lib/typescript.js`

Caused by `fullName = node.name.getText();` (and other occurrences) in `/tasks/buildtsdoc.js`

Attempting to fix these to use `node.name.text` and also changing `node.getStart()` to be `node.pos` allowed the Grunt task to run, but the end result was still producing `: object` types and all comments were being stripped out.

I'm wondering if it's best to move to a 3rd-party .d.ts generator, e.g. https://github.com/englercj/tsd-jsdoc

**Comment by samme** [comment]
Can you try 9df3c88 please?

**Comment by samme** [comment]
> The Typescript version is quite old here, 1.4.1, bumping to latest version and running `grunt tsdocs` bombs out with
> 
> Warning: Cannot read property 'text' of undefined Use --force to continue.

See photonstorm/phaser#2198.

**Comment by cloakedninjas** [comment]
Problem with just updating `.d.ts` files is that next time someone runs a build, it will knock out those changes :( But I guess others have already looked at upgrading Typescript and failed
