### ISSUE TITLE
ionic 2 phaser-ce integration problem

### ISSUE THREAD

**Issue by sersaday** [photonstorm/phaser-ce#289]
ionic serve comman result;
Runtime Error
Cannot find module 'pixi'
console result:

 tslint: C:/projects/ionic_projects/phaserionic/src/pages/home/home.ts, line: 5
            'Phaser' is declared but never used.

       L4:  import "p2";
       L5:  import * as Phaser from "phaser-ce";
I did everything but did not
how to import Phaser on ionic2 porject?

**Comment by Dreaded-Gnu** [comment]
The linting error is kind of normal, as tslint within ionic 2 takes care of unused variables. Have you imported pixi before p2? Within your code snippet, you've only imported p2 and phaser.

I need to provide also a pull request, as of the link to the webpack file of the ionic 2 project template has been added wrong by me.

**Comment by samme** [comment]
<https://github.com/photonstorm/phaser-ce/blob/master/README.md#ionic>
