### ISSUE TITLE
P2.Body addPolygon mutates points in point array

### ISSUE THREAD

**Issue by Plukers** [photonstorm/phaser-ce#301]
* A bug in the API:
  * Phaser version(s): 2.8.3
  * What should happen: The coordinates in the point array should not change
  * What happens instead: The values are modified
  * Live example:

``` javascript
const s = game.add.sprite(x, y, 'Sprite');
game.physics.p2.enable(s, false);
s.body.clearShapes();

const points = [[10, 20], [30, 40], [50, 60]];
console.log(points.toString()); // 10,20,30,40,50,60
s.body.addPolygon({}, points);
console.log(points.toString()); // -0.5,-1,-1.5,-2,-2.5,-3
```

I had no chance to take a closer look, but it looks like the mutation happens here [physics/p2/Body.js, line 1180](https://photonstorm.github.io/phaser-ce/src_physics_p2_Body.js.html#sunlight-1-line-1180)

**Comment by samme** [comment]
I don't think it's a bug, but it may be undesirable. We can add a note to the docs.

Can you try passing a flat array? `[10, 20, 30, 40, 50, 60]`

**Comment by Plukers** [comment]
I wrote bug because it was the most fitting option, but you are right, it's not a bug, just unexpected.
So a note in the docs would be great, thank you!

I will try it with the flat array tomorrow at work and post the results.

**Comment by samme** [comment]
Understood, thanks.

**Comment by Plukers** [comment]
It works with the flat array, the array is not changed.
