### ISSUE TITLE
Add TilemapLayer support for overlap method in Arcade Physics

### ISSUE THREAD

**Issue by raphaklaus** [photonstorm/phaser-ce#302]
Hello!

I'm porting this issue right here:
https://github.com/photonstorm/phaser/issues/867

The intent is to make possible detect overlapping for Layer of `TilemapLayer` type.

I'm working on a PR. If someone else is doing so, please comment here thus we can work together.

**Comment by samme** [comment]
[Phaser.Physics.Arcade#overlap](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html#overlap) already works for Sprite vs. TilemapLayer or Group vs. TilemapLayer (as long as you use callbacks). Is that what you want?

> ##### Tilemaps
> 
> Any overlapping tiles, including blank/null tiles, will give a positive result. Tiles marked via [Phaser.Tilemap#setCollision][256] (and similar methods) have no special status, and callbacks added via [Phaser.Tilemap#setTileIndexCallback][258] or [Phaser.Tilemap#setTileLocationCallback][259] are not invoked. So calling this method without any callbacks isn't very useful.
>
> If you're interested only in whether an object overlaps a certain tile or class of tiles, filter the tiles with `processCallback` and then use the result returned by this method. Blank/null tiles can be excluded by their [index][276] (-1).
> 
> If you want to take action on certain overlaps, examine the tiles in `collideCallback` and then handle as you like.

[256]: https://photonstorm.github.io/Phaser.Tilemap.html#setCollision
[257]: https://photonstorm.github.io/Phaser.TilemapLayer.html#debug
[258]: https://photonstorm.github.io/Phaser.Tilemap.html#setTileIndexCallback
[259]: https://photonstorm.github.io/Phaser.Tilemap.html#setTileLocationCallback
[275]: https://photonstorm.github.io/Phaser.Physics.Arcade.html#collide
[276]: https://photonstorm.github.io/Phaser.Tile.html#index

**Comment by raphaklaus** [comment]
From what I've understood it's compatible with `Tilemap` objects but with `TilemapLayer` it doesn't.

The `collide` support it for example [Phaser.Physics.Arcade.html#collide](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html#collide)

For this to work, would be necessary some new methods called `setOverlap` and `setOverlapBetween` which is analogue to `setCollision` family... This way one can detect overlapping for specific tiles by Layer.

**Comment by samme** [comment]
Both [collide](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html#collide) and [overlap](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html#overlap) accept `TilemapLayer` but not `Tilemap`.

There are two ways to do overlap checks:

1. Call **overlap** and use `collideCallback` or `processCallback`. OR
2. 
    - Attach callbacks with [setTileIndexCallback](https://photonstorm.github.io/Phaser.Tilemap.html#setTileIndexCallback) or [setTileLocationCallback](https://photonstorm.github.io/Phaser.Tilemap.html#setTileLocationCallback)
    - Call **collide**
    - Return `false` from the callback

**Comment by PBM42** [comment]
Hello !
I don't know if it is related but it seems that `collideSpriteVsTilemapLayer` doesn't dispatch `body.onCollide` signal. So no signals are dispatched when a sprite collide with a tile.

**Comment by raphaklaus** [comment]
Yes @PBM42! By my tests is exactly this what is happening. Soon I'll update this issues with my considerations.

**Comment by samme** [comment]
Closing this since I think it's already supported. If `body.onCollide` is failing, please open a new issue, thanks.
