### ISSUE TITLE
Remove PIXI namespace?

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#305]
Re. #174, here's an experimental no-PIXI build: [phaser-test.js.zip](https://github.com/photonstorm/phaser-ce/files/1185922/phaser-test.js.zip)

PIXI.Sprite is now Phaser.DisplaySprite and all other properties are moved to Phaser (e.g., Phaser.DisplayObject).

**Comment by Dreaded-Gnu** [comment]
@samme Do you have somewhere the repository or a branch, where you've removed the pixi dependency?

Just wanted to look into the changes you made.

**Comment by samme** [comment]
[phaser-ce/tree/no-PIXI](https://github.com/photonstorm/phaser-ce/tree/no-PIXI)
