### ISSUE TITLE
Angular 2 Router Outlets keeps spawning new Phaser.Game canvas elements

### ISSUE THREAD

**Issue by benlooi** [photonstorm/phaser-ce#307]
A problem with my code....I hope.

I am building a website with Angular 2 and Phaser. The website calls for a menu, with several menu items. Each item loads a route in the router-outlet of the parent component.

The issue I am facing is this: 
One of the menu items loads a Game into the router outlet when clicked.
When I navigate away to another menu item, the Game canvas element does not go away. When I navigate back to the menu item, another canvas element is added, giving me 2 game canvas objects of the same game, and this keeps increasing everytime I click on the menu item.

I did an inspection of the browser, and realise that everytime I click on the menu-item, it adds a canvas element of the same game to the body.

Not sure if it is my routing code error, or something to do with Phaser. 
Quite a bit of code to share, but I don't know what to share here...routing.ts, mainParent.component.ts or gameComponent.ts stuff. 

Can somebody help me understand what happens when a new Phaser.Game is created ? Does it add a canvas element to the parent, regardless if there's already a previously added canvas element? Is there a way to remove all previous canvas elements in the parent before the game is loaded?

**Comment by samme** [comment]
You should call [Game#destroy](https://photonstorm.github.io/phaser-ce/Phaser.Game.html#destroy) to remove the old game.

**Comment by benlooi** [comment]
I think I know how to solve this. Not a Phaser issue, but an Angular 2 routing issue.

**Comment by benlooi** [comment]
Hi. Ok, I tried the game.destroy() method when NavigationStart event happens. 
However, it works for the first time only. When I navigate away, and go back again, it hangs.

I put this in my constructor : 
```
this.router.events.subscribe((event:Event) => {
					if (event instanceof NavigationStart){
						if (this.game){
					this.game.destroy();
					}
					}
				});
```

**Comment by samme** [comment]
Not sure. Try the forum?

**Comment by Dreaded-Gnu** [comment]
@benlooi Can you provide somewhere a simple sample project?
I've addressed a similar kind of issue within ionic in a non game project ( ionic uses also angular ) caused by the hot reload of webpack dev server. Some modules are then initialized/instantiated twice instead of only once as it seems.
