### ISSUE TITLE
Resuming a looped Sound after it has been paused no longer loops 

### ISSUE THREAD

**Issue by NeoHoffa** [photonstorm/phaser-ce#316]
* A bug in the API:
Phaser v2.8.3
 
When I play a sound and set it to loop, it plays and loops just fine. But then when I call pause() on it and then resume(), the sound pauses and resumes as expected. However the sound no longer loops.

**Comment by samme** [comment]
For me, the sound doesn't loop at all unless I set `looped` **before** calling `play` (or use `loopFull` instead): <https://codepen.io/samme/pen/ZJeNbd>

But once it's looping, it keeps looping correctly through pause/resume.

**Comment by 2called-chaos** [comment]
@NeoHoffa Could you maybe provide an example and/or tell us which browser this happened in for you? Samme's example worked for me in current Chrome, Firefox and IE11.

**Comment by samme** [comment]
Is this in IE? [Sound doesn't loop in Internet Explorer](http://www.html5gamedevs.com/topic/28093-sound-doesnt-loop-in-internet-explorer/)
