### ISSUE TITLE
TypeScript misses game.renderer.setTexturePriority type

### ISSUE THREAD

**Issue by letmaik** [photonstorm/phaser-ce#319]
This Issue is about
* An error in the TypeScript definitions

https://phaser.io/tutorials/advanced-rendering-tutorial/part4

**Comment by samme** [comment]
What's the problem?

**Comment by letmaik** [comment]
See the issue title. setTexturePriority is missing in the typescript definitions.

**Comment by samme** [comment]
It should be in <https://github.com/photonstorm/phaser-ce/blob/v2.8.3/typescript/pixi.d.ts#L1270>.

**Comment by samme** [comment]
Seems CanvasRenderer needs it as well.

> error TS2339: Property 'setTexturePriority' does not exist on type 'CanvasRenderer | WebGLRenderer'. Property 'setTexturePriority' does not exist on type 'CanvasRenderer'.
