### ISSUE TITLE
sprite.alpha properties

### ISSUE THREAD

**Issue by Rootar** [photonstorm/phaser-ce#320]
This Issue is about (pick one, ✏️ delete others)

  * Phaser version(s):
Why alpha properties is not public? Now i use tween for edit it. Is there a simpler way to do this without delay? (even if I set tween duration to 0, there is a little smooth transition ).

Thank you for any advice ;)

**Comment by 2called-chaos** [comment]
You sure you are using Phaser CE?

https://codepen.io/anon/pen/rzGqER

**Comment by samme** [comment]
Sprite#alpha is missing from [docs/2.6.2/Phaser.Sprite](https://phaser.io/docs/2.6.2/Phaser.Sprite.html) but the API hasn't changed, you can use it just like before.

[phaser-ce/Phaser.Sprite#alpha](https://photonstorm.github.io/phaser-ce/Phaser.Sprite.html#alpha) is accurate for 2.6.2 as well.
