### ISSUE TITLE
Error making custom buid

### ISSUE THREAD

**Issue by rafelsanso** [photonstorm/phaser-ce#321]
This Issue is about the generation of custom builds.

* Phaser version(s): v2.8.3 

* What should happen:

The following command, used in documentation, should create a custom build.
```
grunt custom --exclude gamepad,keyboard 
```

  * What happens instead:
Instead of this, will appear an error:

```
[...]\phaser-ce>grunt custom --exclude gamepad,keyboard --filename phaser-nokeys
Warning: Task "gamepad,keyboard" not found. Use --force to continue.

Aborted due to warnings.
```` 

I already have installed Grunt globally. In fact, I can use "grunt nophysics", for example, and this command works fine.

**Comment by photonstorm** [comment]
The above works fine for me.

Try this: `grunt custom --exclude="gamepad,keyboard"`

**Comment by samme** [comment]
Yes, use quotes around the module list.

**Comment by samme** [comment]
It needs a `=` before the module list now, so the command promopt is wrong. Sorry about that.

**Comment by samme** [comment]
Documented in 9173f9b.
