### ISSUE TITLE
Looped audiosprite sprites do not loop correctly after a pause and resume (plays extra copy of the audiosprite from the beginning in addition to the loop)

### ISSUE THREAD

**Issue by Tembac** [photonstorm/phaser-ce#323]
I found a bug that was reported but closed that is still happening on CE. I copy the description of the bug that is better than what I can describe:

https://github.com/photonstorm/phaser/issues/2773

A bug in the API
When using looped audiosprite sprites pause and resume the audiosprite seemingly gets confused and will start playing the entire audiosprite in addition to looping (causing overlapping sounds, typically music in our case).

Codepen.io demo here, this demo will always use the most recent build on the dev branch (within a few minutes typically)

Example sequence *in the codepen; which calls this.game.sound.pauseAll() and this.game.sound.resumeAll() in onPause and onResume respectively;

Audiosprite contains 1 music track set to loop *so no real reason to use an audiosprite anyway, but for the purposes of this demo it does
Wait for music to start playing
Then click out of the window pausing Phaser (and pausing all audio)
Then click in the window resuming Phaser (and resuming all audio)
Wait for the track to finish and you should here it start to play again but also have a copy playing over top with a slight offset
or the more realistic example of;

Audiosprite contains 2 music tracks set to loop
Play music track 2, which is second in the audiosprite
Then click out of the window pausing Phaser (and pausing all audio)
Then click in the window resuming Phaser (and resuming all audio)
Wait for the track you played to finish and you should here track 2 start playing again but with track 1 playing on top of it

**Comment by samme** [comment]
Where's the demo?

**Comment by samme** [comment]
<https://codepen.io/samme/pen/GvyovB?editors=0010>

**Comment by pavle-goloskokovic** [comment]
It's an old one and I think a really hard one to fix since it goes really deep inside of audio engine implementation.

One 'solution' could be to mute the looping track instead of pausing it.

Or do nothing because the game does it by itself when is's paused:
https://github.com/photonstorm/phaser-ce/blob/master/src/core/Game.js#L1180

I bet if it was an easy fix 
```js
this.sound.pauseAll();
```
would be called here instead of 
```js
this.sound.setMute();
```

**Comment by samme** [comment]
![Many AudioBufferSource](https://user-images.githubusercontent.com/435681/34859010-861d7030-f708-11e7-8c3f-5683e5362e64.png)

**Comment by samme** [comment]
Maybe try disabling Web Audio.

**Comment by squaresun** [comment]
I was just facing this problem before and fix it by modifying [https://github.com/photonstorm/phaser-ce/blob/3a73a34dd6ef0ceb38535ba6fb61d041d4bb8873/src/sound/Sound.js#L910](@method Phaser.Sound#resume) to this:
```
this._sound.start(0, p, duration);
```

It works with Chrome 64.0.3282.140 (64-bit) but the problem still exists on Mac OS Safari

Here is the example after modified:
https://codepen.io/squaresun/pen/mXrepv

**Comment by squaresun** [comment]
I was just facing this problem before and fix it by modifying [https://github.com/photonstorm/phaser-ce/blob/3a73a34dd6ef0ceb38535ba6fb61d041d4bb8873/src/sound/Sound.js#L910](@method Phaser.Sound#resume) to this:
```
this._sound.start(0, p, duration);
```

It works with Chrome 64.0.3282.140 (64-bit) but the problem still exists on Mac OS Safari

Here is the example after modified:

**Comment by samme** [comment]
Something about this block looks wrong. <https://github.com/photonstorm/phaser-ce/blob/3a73a34dd6ef0ceb38535ba6fb61d041d4bb8873/src/sound/Sound.js#L901-L916>
