### ISSUE TITLE
TextBounds update after parent scale

### ISSUE THREAD

**Issue by reatailret** [photonstorm/phaser-ce#326]
Hello.

How to set correct text bounds after sprite scale?  Example  , [https://phaser.io/sandbox/edit/OvGUDREg](https://phaser.io/sandbox/edit/OvGUDREg), button with label . Text bounds not working after scale parent container.

**Comment by samme** [comment]
I'm not sure. `textBounds` works by altering `pivot`. <https://codepen.io/samme/pen/OWYYEM>

My first guess would be

```javascript
text2.setTextBounds(0, 0, button2.texture.frame.width, button2.texture.frame.height);
```

**Comment by reatailret** [comment]
Not working.
Updated example [https://phaser.io/sandbox/edit/onWWwRUZ](https://phaser.io/sandbox/edit/onWWwRUZ)
If add text to scaled sprite and set corect textBounds.
