### ISSUE TITLE
problems of Ionic with Phaser

### ISSUE THREAD

**Issue by isWalter** [photonstorm/phaser-ce#327]
I followed readme to try incorporating Phaser into Ionic framework. However, I am not sure where should I put this code to:
  import "pixi";
  import "p2";
  import * as Phaser from "phaser-ce";

I am also not sure where should I paste my javascript to. It would be highly appreciated if there can be a demo for the merge of Ionic with Phaser, like putting the tutorial game to Ionic. I am just a amateur coder, so reli need more specific instructions. Sorry about that. Hope you guys may help. Thank you very much!

P.S. I am using Ionic3.

**Comment by samme** [comment]
Did you look at [resources/Project  Templates/ionic-example](https://github.com/photonstorm/phaser-ce/tree/master/resources/Project%20Templates/ionic-example)?

**Comment by isWalter** [comment]
yes, but I have no clues how to implement it still. I dunno where should I put my script to. And readme instructed me to import these

import "pixi";
import "p2";
import * as Phaser from "phaser-ce"

but which script should I put it to? I put it in xxxx.ts but then it returned error. seems that this code looks different from AngularJS...?

**Comment by samme** [comment]
In our template they're in [ionic-example/src/app/main.ts](https://github.com/photonstorm/phaser-ce/blob/master/resources/Project%20Templates/ionic-example/src/app/main.ts). That's all I know though. 🙁

**Comment by isWalter** [comment]
sorry!! I overlooked it. Thank you so much for your reminder. But may I ask where should I paste my javascript to (i mean the script of the game)? it seems to me that it should be pasted on the html of a page. But I saw some websites transform their code to angularjs, which is pretty advanced for me @@

**Comment by samme** [comment]
Maybe in [src/app/app.module.ts](https://github.com/photonstorm/phaser-ce/blob/master/resources/Project%20Templates/ionic-example/src/app/app.module.ts) or imported there. @Dreaded-Gnu ?

**Comment by Dreaded-Gnu** [comment]
Ionic uses angularjs, so you might try to add the root game class into the list of declarations (within src/app/app.module.ts). After that, you can pass the root game instance to constructor of class MyApp ( src/app/app.component.ts ). After that you should be able to call a start method within initializeApp.

I'll try to extend the example a bit more, so that it would be more clear, and the ionic version used there is up to date.

**Comment by Dreaded-Gnu** [comment]
I've updated the project template itself with pull request ( #328 ). There I've added a main game class, used as main entry point of the game instantiated within home page, which is the main view entry for angular here.

The main game class can be used to add game states, and these states there can be kickstarted.

**Comment by isWalter** [comment]
Thank you so much @Dreaded-Gnu  !!!
