### ISSUE TITLE
maxParticles seems to have no effect above 40

### ISSUE THREAD

**Issue by fyyyyy** [photonstorm/phaser-ce#330]
* A bug in the API:
  * Phaser version(s): 2.6.1. to 2.8.4
  * Live example: https://codepen.io/anon/pen/jLpWeY?editors=0010
  * What should happen:
maxParticles should have an effect on how many particles are shown on screen.
Any value above 40 seems to have no effect. I would expect thousands of particles to show up.
Values below 40 will gradually decrease particles on screen as it should. 

  * What happens instead:
Only about 30 particles are rendered on screen
No matter which settings i try for maxParticles or emitter.start, i never get to render more than 30 particles on screen

**Comment by samme** [comment]
See <https://codepen.io/samme/pen/MvBOzb?editors=0010>.

`start(explode=false)` always releases 1 particle per emit, so its maximum flow rate is ~60 particles per second.

Use [Emitter#flow](https://photonstorm.github.io/phaser-ce/Phaser.Particles.Arcade.Emitter.html#flow) instead, which is simpler and also allows quantity > 1.

**Comment by fyyyyy** [comment]
Thanks, thats good news. I guess this is a documentation request then :D 
https://phaser.io/docs/2.6.2/Phaser.Particles.Arcade.Emitter.html#start

**Comment by samme** [comment]
<https://photonstorm.github.io/phaser-ce/Phaser.Particles.Arcade.Emitter.html#start> is a little better.

**Comment by fyyyyy** [comment]
Hmm i see. However, frequency cannot be a float value. As in my example `rain.start(false, 200, 0.01, 0);` i try to lower the frequency to 10 us. However 1 seems to be the lowest value accepted?

**Comment by samme** [comment]
You can even use `frequency=0`, but the release rate is never greater than the game update rate (60 updates per second, 16.66ms).

You need to use [flow](https://photonstorm.github.io/phaser-ce/Phaser.Particles.Arcade.Emitter.html#flow), e.g.,

```javascript
rain.flow(500, (1000/60), 33);
```
