### ISSUE TITLE
the Phaser.Rope can only show black rectangle

### ISSUE THREAD

**Issue by JanusSpark** [photonstorm/phaser-ce#348]
I tryied both in phaser-ce 2.8.5 and 2.8.6 like this.
This is the example [Phaser-examples-rope](http://phaser.io/examples/v2/sprites/rope)

I import Phser like this because I use webpack
`import PIXI from 'expose-loader?PIXI!phaser-ce/build/custom/pixi.js';`
`import p2 from 'expose-loader?p2!phaser-ce/build/custom/p2.js';`
`import Phaser from 'expose-loader?Phaser!phaser-ce/build/custom/phaser-split.js';`
I load the picure like this
`game.load.image('left', .....);
game.load.image('right', .....);`
And when I use the rope in this two way they are all only show black rectangle;
`   var left_points = [];
    left_points.push(new Phaser.Point(0, 0));
    left_points.push(new Phaser.Point(game.width / 2 + 40, 0));

    var _left_door = new Phaser.Sprite(game,0,0,'left');

    var left_door = game.add.rope(0, 0,_left_door.texture, null, left_points);
    left_door.x = 0;
    left_door.y = 200;
    left_door.height = 400;
    left_door.scale.set(1);
    var count = 0;
    left_door.updateAnimation = false;`
or
`var right_points = [];

    right_points.push(new Phaser.Point(0, 0));
    right_points.push(new Phaser.Point(game.width / 2 + 5, 0));

    //when I use the new function like this  it will throw an error at LoadTexture so I change this file one line to down here like

    //var smoothed = !(this.texture.baseTexture && this.texture.baseTexture.scaleMode);

    var right_door = new Phaser.Rope(game, 0, 0, 'right', null, right_points);
    //I also tried to use like this  but it didn't work
    // var _right_door = new Phaser.RenderTexture(game,200,200,'right');
    // var right_door = new Phaser.Rope(game, 0, 0, _right_door.texture, null, right_points);
    right_door.x = game.width / 2 - 5;
    right_door.y = y;
    right_door.height = game.height - y;
    right_door.scale.set(1);
    right_door.updateAnimation = false;
    //And then I add it to the Group like this  I used my own Phaser.Group
    Phaser.World.add(right);`

![image](https://user-images.githubusercontent.com/12661048/30283556-05b56ed8-974b-11e7-90cc-ec4c42bb27fb.png)
the other sprite in the game is OK. And when I add the 'left' picture like a normal Sprite it's OK. Only in rope it's wrong.
![image](https://user-images.githubusercontent.com/12661048/30284394-692811b2-974d-11e7-935e-8344bb46423e.png)
the red streamers at  left  is the real picture 'left'  when I add the normal sprite '_left_door '
How should I use the Rope ?  I used to use the rope in PIXI and it's good. But I can't use it in Phaser now 
Can you help me? Thank you

**Comment by samme** [comment]
I don't know much about Phaser.Rope. Try `game.debug.ropeSegments(left_door)`. You might try the forum as well.

**Comment by JanusSpark** [comment]
![image](https://user-images.githubusercontent.com/12661048/30325837-df5a71a8-97f8-11e7-8417-7bf02895cc8a.png)
I try to use `game.debug.ropeSegments(left_door)` and it looks like this.
I think it's just didn't show the texture or it couldn't find the correct texture

**Comment by samme** [comment]
Can you post your whole script?
