### ISSUE TITLE
Callback Documentation

### ISSUE THREAD

**Issue by HaoboZ** [photonstorm/phaser-ce#353]
This Issue is about
* An error in the documentation

The documentation for buttons, and I think for many other classes that contain callbacks don't show what parameter (if any) are passed in when they are called. This is confusing to me when reading the documentation and trying to figure out which options could be used. 

For example, I don't know if the button click callback already passes an isOver parameter, since it still activates the function even when the pointer leaves the button, and that the onInputUp which is used to call it does pass in that parameter. 

The Signal class documentation puts very little emphasis on callback parameters, but they are pretty important, especially the isOver parameter for onInputUp.

**Comment by samme** [comment]
Agreed, the docs should note that the [Button callback](https://photonstorm.github.io/phaser-ce/Phaser.Button.html#Button) is actually added to [Events#onInputUp](https://photonstorm.github.io/phaser-ce/Phaser.Events.html#onInputUp).

If you find other callbacks with undocumented arguments, please add to this thread.

**Comment by samme** [comment]
It's a pain but you can do `console.log(arguments)` to discover undocumented arguments.

**Comment by samme** [comment]
Closing for 658f68a but please open a new issue if you find any other mystery callbacks.
