### ISSUE TITLE
Text bound to sprite coordinates redraws much later than the sprite

### ISSUE THREAD

**Issue by amorphine** [photonstorm/phaser-ce#357]
This Issue is about a problem with my own code

The text attached to the sprite coordinates is being drawn much later than the sprite. What's the problem?

The code in the [sandbox](https://phaser.io/sandbox/edit/NCSfUkCW)
To make sprite to move we should hold left mouse button. We see that the text moves asynchronously to the sprite like it redraws some time after that.

The used technique was taken from [here](https://phaser.io/examples/v2/text/center-text-on-sprite), but I could see no issue there while sprite is being moved.

**Comment by samme** [comment]
Can you put it in <https://codepen.io/pen?template=pRGPKG> instead? Sandbox can't run ES6 classes.

**Comment by amorphine** [comment]
@samme 
Hello,
Here you are https://codepen.io/anon/pen/YrXNBG

**Comment by Timsonrobl** [comment]
@amorphine 
To move graphical objects synchronously you can add them as children:
https://codepen.io/anon/pen/ZXGojY
So this probably have nothing to do with render.

**Comment by samme** [comment]
Only CodePen transpiles ES6.

Please see the `preRender` method in <https://codepen.io/samme/pen/EwjMbG>.

For this case a child sprite would also work well.
