### ISSUE TITLE
ionic 3 phaser-ce plugin

### ISSUE THREAD

**Issue by sersaday** [photonstorm/phaser-ce#359]
How to insert plugin into ionic 3 phaser-ce application ?

**Comment by samme** [comment]
Not sure. Try the forum?

**Comment by Dreaded-Gnu** [comment]
What are you trying to do? What plugin do you want to add?

**Comment by sersaday** [comment]
I would like to import the VirtualJoystick plugin into the application ionic3-phaser-ce.
ionic-3 phaser-ce project example is here

https://github.com/photonstorm/phaser-ce/tree/master/resources/Project%20Templates/ionic-example

**Comment by sersaday** [comment]
but I can not add plugins

**Comment by Nick-lab** [comment]
re open this

**Comment by samme** [comment]
I don't know the answer, and it's unlikely to get more attention here.

<https://stackoverflow.com/questions/43833895/how-to-include-js-file-in-ionic-3>
