### ISSUE TITLE
p2 collision not work with Polygon after I updated phaser ce from 2.8.3 to 2.8.7

### ISSUE THREAD

**Issue by bobhfut** [photonstorm/phaser-ce#366]
I'am using Polygon, collision works in version 2.8.3 with Polygon, but after I updated to 2.8.7 ,it didn't work .
 [here is the example](https://codepen.io/anon/pen/JrKEmL) 
sprites fall out of the screen ,but if I change setting to 2.8.3 , it will not.

**Comment by samme** [comment]
Guess I can revert #279.

**Comment by samme** [comment]
Please test: [phaser-test.js.zip](https://github.com/photonstorm/phaser-ce/files/1320063/phaser-test.js.zip)

**Comment by bobhfut** [comment]
@samme tested, it did not work, this problem seems to start with version 2.8.4

**Comment by samid737** [comment]
This is indeed due to #279, there is a similar problem: https://github.com/photonstorm/phaser-ce/pull/279#issuecomment-327857356 ... Only reverting will heal the polygon. there are alternatives to consider for #258, details also found in  https://github.com/photonstorm/phaser-ce/pull/279#issuecomment-327857356 .

**Comment by samid737** [comment]
http://www.html5gamedevs.com/topic/33001-collisions-not-working-when-using-phaser-webpack/

I can confirm this happens after 2.8.3. Demo (Move blocks using mouse):

[2.8.3
](https://samid737.github.io/279demo1/) 

[2.8.4](https://samid737.github.io/279demo2/)

**Comment by bobhfut** [comment]
@samid737 Yes , it start with 2.8.4

**Comment by samme** [comment]
OK please test [phaser-test.js.zip](https://github.com/photonstorm/phaser-ce/files/1322530/phaser-test.js.zip).

**Comment by bobhfut** [comment]
@samme Great, It works ok
