### ISSUE TITLE
Problem to load JSON from CDN

### ISSUE THREAD

**Issue by rafelsanso** [photonstorm/phaser-ce#370]
I have an issue loading assets from a CDN.
For the images, I'm using
```javascript
this.game.load.crossOrigin = "Anonymous";
```
But if I try to use method this.game.load.atlasJSONArray, appears an error of cross origin domain for all JSON on the game. There are any method for change the crossOrigin options for assets when are not images?

* A bug in the API:
  * Phaser version(s): 2.6.2

**Comment by samme** [comment]
It should be

```javascript
this.game.load.crossOrigin = "anonymous";
```
