### ISSUE TITLE
Camera bug with tilemap

### ISSUE THREAD

**Issue by JohnyBro** [photonstorm/phaser-ce#378]
This Issue is about a problem with my own code.

Hi guys,
My camera follow bug when I use a tilemap but work great when I simply set a background with a sprite.
Here you can see the bug https://codepen.io/anon/pen/ZXrxLg?editors=0010.
You can switch by commenting lines 34 and 35 and uncomment lines 32 to switch.

Thx for your help.

**Comment by samme** [comment]
What's the problem though?

**Comment by JohnyBro** [comment]
When I use a tilemap and I follow a sprite with the camera the map vibrate it's not smooth.

**Comment by samme** [comment]
See <https://codepen.io/samme/pen/VMdJbZ>.

**Comment by JohnyBro** [comment]
Man thank you very much it's awesome !
