### ISSUE TITLE
Ionic 3 Phaser integration with latest Ionic starter

### ISSUE THREAD

**Issue by mrvipinkashyap** [photonstorm/phaser-ce#381]
* An error in the TypeScript definitions
OR
* A problem with my own code

I am trying to integrate Ionic 3 Phaser with latest Ionic starter but I am not successfully able to do so.

I initially started with following starter project which seemed to be working fine with dependencies in its package.json:
https://github.com/jvaranam/ionic3PhaserDemo

But when I am trying to do the same in latest starter project I am getting this error: `Uncaught Error: Cannot find module "pixi"`
https://drive.google.com/a/sookshum-labs.com/file/d/0B6ZKFOkTWs8DeXowaC1GdGxrWXM/view?usp=drivesdk
Ionic info output can be found in above screenshot.

I have uploaded my current starter project I am trying to integrate to Github:
https://github.com/mrvipinkashyap/Ionic3PhaserParallax

I have followed instructions from https://github.com/photonstorm/phaser-ce#ionic and already checked [Ionic example here](https://github.com/photonstorm/phaser-ce/tree/master/resources/Project%20Templates/ionic-example)

Please feel free to ask any other queries that may help in quick resolution of this issue. 

Thanks

**Comment by Dreaded-Gnu** [comment]
Why is the import of pixi and p2 in game.ts commented out?

**Comment by NimaiMalle** [comment]
I've got the same error message: Cannot find module "pixi"
This, after updating to the latest ionic.  I recall when I set this up a few months ago, there were some special instructions for how to setup webpack merge - which I otherwise know nothing about.  I'll post here if I find anything, though.

**Comment by mrvipinkashyap** [comment]
@Dreaded-Gnu I was trying out several things to get it to work. Uncommenting pixi and p2 in game.ts doesn't have any affect.

**Comment by tgensol** [comment]
It looks like there is an issue with the ionicWebpackConfig on the latest ionic-app-scripts, especially with the --prod flag

**Comment by NimaiMalle** [comment]
I have not tried the --prod flag.  Just using **ionic serve** to build and launch.  Everything builds without error, then the "Cannot find..." error at runtime.

**Comment by Dreaded-Gnu** [comment]
With the latest release of ionic app scripts they changed the webpack config structure. The webpack config is starting with version 3 of ionic app scripts a dictionary of webpack configs. So to get it working, you have to store the webpack extension into a variable and merge it into ionics dev and prod config:

```var webpackExtension = {
  resolve: {
    // alias resolve (begin)
    alias: {
      "pixi": pixi,
      "p2": p2,
      "phaser-ce": phaser
    }
    // alias resolve (end)
  },
  module: {
    loaders: [
      // exposing pixi, correct phaser and p2 into global scope (begin)
      {
        test: /pixi\.js/,
        loader: "expose-loader?PIXI"
      }, {
        test: /phaser-split\.js/,
        loader: "expose-loader?Phaser"
      }, {
        test: /p2\.js/,
        loader: "expose-loader?p2"
      }
      // exposing pixi, correct phaser and p2 into global scope (end)
    ]
  }
};

module.exports = {
  dev: webpackMerge.smart( ionicWebpackConfig.dev, webpackExtension ),
  prod: webpackMerge( ionicWebpackConfig.prod, webpackExtension )
};```

For that release, the starter template in this repo needs to be adjusted also.

**Comment by tgensol** [comment]
@Dreaded-Gnu Thanks it works just fine !

**Comment by Dreaded-Gnu** [comment]
I'll use this issue then for adjusting the starter template and the readme

**Comment by smatthews1999** [comment]
Please update the [Ionic example](https://github.com/photonstorm/phaser-ce/tree/master/resources/Project%20Templates/ionic-example) with this latest webpack.config.js

**Comment by Dreaded-Gnu** [comment]
After a really long abstinence, I've created a pull request to update the template to latest ionic release. :smile:

**Comment by archagy** [comment]
Right now im having the same issue with the latest version of ionic. 

> ionic-cli
> 6.10.1
>ionic version
>5.0.0


package.json
```
{
  "name": "demo-game",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@capacitor/core": "2.3.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "phaser-ce": "^2.16.0",
    "rxjs": "~6.5.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler": "~9.1.6",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@capacitor/cli": "2.3.0",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "expose-loader": "^1.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3",
    "webpack-merge": "^5.0.9"
  },
  "description": "An Ionic project",
  "config": {
    "ionic_webpack": "./webpack.config.js"
  }
}
```




webpack.config.js
```
var path = require( "path" );
var webpackMerge = require( "webpack-merge" );

// root directory ( useful, when config is within a sub folder )
var rootDir = path.resolve( __dirname );

// import webpack config from ionic
var ionicWebpackConfig = require( path.resolve( rootDir, "node_modules", "@ionic", "app-scripts", "config", "webpack.config" ) );

// necessary for expose loader
var phaserModule = path.join(rootDir, "node_modules", "phaser-ce");
var phaser = path.join(phaserModule, "build", "custom", "phaser-split.js");
var pixi = path.join(phaserModule, "build", "custom", "pixi.js");
var p2 = path.join(phaserModule, "build", "custom", "p2.js");

var webpackExtension = {
  resolve: {
    // alias resolve (begin)
    alias: {
      "pixi": pixi,
      "p2": p2,
      "phaser-ce": phaser
    }
    // alias resolve (end)
  },
  module: {
    loaders: [
      // exposing pixi, correct phaser and p2 into global scope (begin)
      {
        test: /pixi\.js/,
        loader: "expose-loader?PIXI"
      }, {
        test: /phaser-split\.js/,
        loader: "expose-loader?Phaser"
      }, {
        test: /p2\.js/,
        loader: "expose-loader?p2"
      }
      // exposing pixi, correct phaser and p2 into global scope (end)
    ]
  }
};

module.exports = {
  dev: webpackMerge.smart( ionicWebpackConfig.dev, webpackExtension ),
  prod: webpackMerge.smart( ionicWebpackConfig.prod, webpackExtension )
};


```
