### ISSUE TITLE
TypeScript defs errors for newly added methods in v2.9.0

### ISSUE THREAD

**Issue by pavle-goloskokovic** [photonstorm/phaser-ce#382]
This Issue is about:
* An error in the TypeScript definitions

> Error:(4637, 9) TS7010:'sample', which lacks return-type annotation, implicitly has an 'any' return type.
> Error:(13734, 16) TS7010:'intersectionWithRectangle', which lacks return-type annotation, implicitly has an 'any' return type.
> Error:(27916, 9) TS7010:'align', which lacks return-type annotation, implicitly has an 'any' return type.
> Error:(32310, 16) TS7010:'updateColor', which lacks return-type annotation, implicitly has an 'any' return type.
> Error:(33070, 16) TS7010:'setProperties', which lacks return-type annotation, implicitly has an 'any' return type.

Related to these newly added methods: 

- [Phaser.Circle#sample](https://photonstorm.github.io/phaser-ce/Phaser.Circle.html#sample)
- [Phaser.Line#intersectionWithRectangle](https://photonstorm.github.io/phaser-ce/Phaser.Line.html#_intersectionWithRectangle)
- [Phaser.ScaleManager#align](https://photonstorm.github.io/phaser-ce/Phaser.ScaleManager.html#align)
- [Phaser.Tween.updateColor](https://photonstorm.github.io/phaser-ce/Phaser.Tween.html#_updateColor)
- [Phaser.Utils.setProperties](https://photonstorm.github.io/phaser-ce/Phaser.Utils.html#_setProperties)

**Comment by samme** [comment]
Pending a fix you can disable strict checks to avoid these.
