### ISSUE TITLE
Does Stop Animation example point to wrong atlas URL?

### ISSUE THREAD

**Issue by notalentgeek** [photonstorm/phaser-ce#383]
This Issue is about (pick one, ✏️ delete others)

* An error in the documentation

I am currently re-learning Phaser back. Got into this example: [https://phaser.io/examples/v2/animation/stop-animation](https://phaser.io/examples/v2/animation/stop-animation). I found that there is actually no ./sprites/seacreatures_json.json. My correction is to have the example written like this.

```markdown
game.load.atlasXML('seacreatures', 'assets/sprites/seacreatures.png', 'assets/sprites/seacreatures.xml');
```

If I am actually missed something, then I am sorry!

**Comment by samme** [comment]
What do you mean by "there is actually no ./sprites/seacreatures_json.json"?

**Comment by photonstorm** [comment]
https://github.com/photonstorm/phaser-examples/blob/master/examples/assets/sprites/seacreatures_json.json
