### ISSUE TITLE
Audio GainNode.gain.value setter smoothing is deprecated

### ISSUE THREAD

**Issue by rmartone** [photonstorm/phaser-ce#385]
Saw the following warning in Chrome Canary using Phaser-CE v2.9.1. Since I was unable to find a pre-existing issue about this, wanted to report it.

> phaser.js:79995 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

**Comment by samme** [comment]
Thinks this means statements like

```javascript
gainNode.gain.value = 0;
```

must be changed to

```javascript
gainNode.gain.setTargetAtTime(0, audioContext.currentTime + 1, 0);
```

**if** smoothing is needed (maybe it sounds weird without).

**Comment by madmicra** [comment]
Any news on a when a release will include a fix for this?

**Comment by samme** [comment]
Can try for the next release.

Nothing's actually wrong yet, since Chrome's behavior won't change for a few months.

**Comment by samme** [comment]
Need to check iOS support: <https://mdn.github.io/webaudio-examples/audio-param/>

**Comment by samme** [comment]
![_setGain smoothes volume changes](https://user-images.githubusercontent.com/435681/32572925-19cd4a5e-c481-11e7-9ac2-20daf2581e67.png)

**Comment by samme** [comment]
<https://codepen.io/samme/pen/MOpzwN>

**Comment by samme** [comment]
I missed the `gain.value` assignments in Phaser.Sound.

**Comment by samme** [comment]
> Webkit has default values of `smoothing_constant` and `snap_threshold` of 0.05 and 0.001 respectively.

<https://github.com/WebAudio/web-audio-api/issues/76#issuecomment-27954865>

**Comment by samme** [comment]
Chrome prints the deprecation notice when `gain.value` is changed even while the sound isn't playing (as in the Phaser.Sound constructor). That seems unnecessary.

**Comment by Mertank** [comment]
Just came across an issue with the setGain call now. If I play a sound with volume 0 to start you can very briefly hear it play as it fades down to 0 over the 0.01 seconds. The chrome notice is really odd. It says "Please use setTargetAtTime() instead if smoothing is needed.", so I guess if you don't want smoothing then using volume is still fine?

**Comment by samme** [comment]
Yes, I just don't know yet how it sounds without dezippering. I'll check Canary. Not clear if Firefox and Safari are still doing automatic dezippering either.

**Comment by Mertank** [comment]
This user https://github.com/WebAudio/web-audio-api/issues/76#issuecomment-352211472 seems to make it sound like Firefox was never doing it.

**Comment by samme** [comment]
In that case, I may just restore the original gain setting method.

**Comment by samme** [comment]
I restored the original gain setting method. We can maybe add an option or extra methods for gain smoothing if authors need them later.

So you'll still see the deprecation notice in Chrome. I still see the notice in my Canary M65, though it says the change is scheduled for M64.

**Comment by samme** [comment]
> This has the potential to break existing apps if they depended on smooth transitions using the value setter.
>
> If dezippering is still needed, the appropriate replacement is to use setTargetAtTime(value, context.currentTime, timeConstant), where timeConstant is probably around 10-20 ms, which was the typical value used in Chrome for dezippering.
>
> If dezippering is not needed, nothing needs to be done,
>
> Deprecation messages will be displayed, stating dezippering will be removed in M66.

<https://www.chromestatus.com/features/5287995770929152>

**Comment by jamesjsewell** [comment]
I'm not using this feature yet but I am getting a dep warning in my console. Should I just ignore that? I'm using the 2.10 version of ce from the cdn

**Comment by samme** [comment]
If you're not using audio at all, you can add

```javascript
window.PhaserGlobal = { disableAudio: true };
```

before you call `new Phaser.Game()`. That should avoid the warning.

And in any case, unless you hear audio problems during volume changes, you can safely ignore the warning.

**Comment by jamesjsewell** [comment]
@samme thanks, if i do encounter what you described I will refer back to this thread

**Comment by kjdion84** [comment]
I'm using 2.10.1 and I want audio in my game.

I still get this message in the console. Will this have any effect on my game when Chrome changes this?

**Comment by samme** [comment]
> Will this have any effect on my game when Chrome changes this?

You can test it now in Chrome Canary or Firefox.

**Comment by samme** [comment]
There are two ways we could provide optional gain smoothing:

1.  Add `smoothMute` and `smoothVolume` setters (matching `mute` and `volume`) for Phaser.Sound and Phaser.SoundManager: 
    
    ```javascript
    sound.smoothMute = false;
    sound.smoothVolume = 0.5;
    ```
    
2.  Add `smoothVolumeChanges` flags to Phaser.Sound and Phaser.SoundManager, affecting `mute` and `volume`:
    
    ```javascript
    sound.smoothVolumeChanges = true;
    sound.mute = false;
    sound.volume = 0.5;
    ```

**Comment by squarecandy** [comment]
BTW, this is the most informative post on the topic (regarding this issue with Web Audio API) I found anywhere. Your research into it is helpful for all Audio API users, not just Phaser-CE users. Thank you!!

**Comment by samme** [comment]
Closing for #534
