### ISSUE TITLE
svg sprite doesn't work in IE11

### ISSUE THREAD

**Issue by ptol** [photonstorm/phaser-ce#388]
* Phaser version(s): 2.9.1
  * Live example: https://codepen.io/anon/pen/bomGZB
  * What should happen: in IE11 svg sprite should work
  * What happens instead: in IE11 svg sprite doesn't work

This example works in FF and Chrome but doesn't work in IE11
and there is a warning in IE
```
Phaser.Frame: Frame "undefined" has a width or height of zero
```
Because when IE load svg in HTMLImageElement the width and height are 0
so in this Phaser code `data.width` and `data.height` are 0
```
    addImage: function (key, url, data) {

       ...

        var img = {
            key: key,
            url: url,
            data: data,
            base: new PIXI.BaseTexture(data, null, this.game.resolution),
            frame: new Phaser.Frame(0, 0, 0, data.width, data.height, key),
            frameData: new Phaser.FrameData()
        };
```
Is there any workaround? I know the sizes of svg sprites, so if only I could pass width and height in `        game.load.image` somehow.

**Comment by samme** [comment]
Try changing

`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1000">`

to

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 1000">`

**Comment by ptol** [comment]
@samme Thanks, but it doesn't help, neither do
```
<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1000" viewBox="0 0 1600 1000">
```

**Comment by samme** [comment]
[Cache#addImage](https://photonstorm.github.io/phaser-ce/Phaser.Cache.html#addImage) has a `data` argument but it's going to be hard to use it.

You may be able to overwrite Loader#image (to add a `properties` argument) and Loader#fileComplete (to modify `file.data`).

**Comment by samme** [comment]
Closing since this seems like an IE11 issue and I can't think of any more workarounds.
