### ISSUE TITLE
GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.

### ISSUE THREAD

**Issue by noseglid** [photonstorm/phaser-ce#39]
I recently switched from `phaser` to `phaser-ce` and everything worked quite nicely except this error.

I've pinpointed it to when I apply a filter to two different sprites using the same texture. That is, something like this:

```javascript
const s1 = this.game.add.sprite(0, 0, 'spriteKey');
const s2 = this.game.add.sprite(20, 20, 'spriteKey');

const filter1 = new Filter(this.game, null, shaderSource);
const filter2 = new Filter(this.game, null, shaderSource);

s1.filters = [ filter1 ];
s2.filters = [ filter2 ];
```

The error looks like this:
![screen shot 2017-02-23 at 12 57 38](https://cloud.githubusercontent.com/assets/933880/23258264/b45a7798-f9c7-11e6-971c-71c8eb484e79.png)

It doesn't occur in `phaser 2.6.2`.

It also messes up some rendering. Sprites which use the same key are flashing and teleporting seemingly at random.

The main difference I have been able to find between `phaser` and `phaser-ce` is the multi texture feature [described in the tutorial](https://phaser.io/tutorials/advanced-rendering-tutorial/part2). It also seems logical as sprites seem to affect each other. I have no idea how though.

How can I further debug this issue?

**Comment by netgfx** [comment]
Same here its related to my filter that looks like this
```
this.fragmentSrc = [
        'precision lowp float;',
        'varying vec2 vTextureCoord;',
        'varying vec4 vColor;',
        'uniform sampler2D uSampler;',

        'void main() {',
            'vec4 sum = vec4(0);',
            'vec2 texcoord = vTextureCoord;',
            'for(int xx = -4; xx <= 4; xx++) {',
                'for(int yy = -3; yy <= 3; yy++) {',
                    'float dist = sqrt(float(xx*xx) + float(yy*yy));',
                    'float factor = 0.0;',
                    'if (dist == 0.0) {',
                        'factor = 2.0;',
                    '} else {',
                        'factor = 2.0/abs(float(dist));',
                    '}',
                    'sum += texture2D(uSampler, texcoord + vec2(xx, yy) * 0.002) * factor;',
                '}',
            '}',
            'gl_FragColor = sum * 0.025 + texture2D(uSampler, texcoord);',
        '}'
    ];
```

any ideas?

**Comment by arovenski** [comment]
I have the same error trying to copy sprite or group more than once using the following method:
* create new Phaser.RenderTexture
* texture.renderXY(someSprite, 0, 0)
* create new image with the given texture
* create another sprite with same texture or another created from same sprites

**Comment by ForgeableSum** [comment]
i'm having this problem - not sure what to do as i use custom textures extensively.

**Comment by noseglid** [comment]
@samme There are a few code examples in this issue. What else do you reckon I must provide?

**Comment by samme** [comment]
Hi @noseglid, these are helpful but we could use a single runnable example (test case). <http://codepen.io/pen?template=vyKJvw>

**Comment by samme** [comment]
> I've pinpointed it to when I apply a filter to two different sprites using the same texture.

<http://codepen.io/samme/pen/jBjzGj>

When I use the Gray filter on one sprite, the others are distorted, and if I use the filter on two, all but the first are hidden. I don't get a GL_INVALID_OPERATION warning (or any other), though.

![One sprite filtered](https://cloud.githubusercontent.com/assets/435681/24834506/b4fc4f4e-1c9c-11e7-8b18-1234370ce3f8.png)

![Two sprites filtered](https://cloud.githubusercontent.com/assets/435681/24834509/bcdb38e2-1c9c-11e7-862b-5c700bc1012a.png)

**Comment by samme** [comment]
> - create new Phaser.RenderTexture
> - texture.renderXY(someSprite, 0, 0)
> - create new image with the given texture
> - create another sprite with same texture or another created from same sprites

@arovenski I can successfully make 2 sprites from the same RenderTexture: <http://codepen.io/samme/pen/oZrrQo?editors=0010>

I'm not sure I'm doing the same as your step 4 though. Do you have an example?

**Comment by samme** [comment]
> When I use the Gray filter on one sprite, the others are distorted, and if I use the filter on two, all but the first are hidden. I don't get a GL_INVALID_OPERATION warning (or any other), though.

Making new issues for these since it's not clear they are the same problem.

**Comment by noseglid** [comment]
Here's a working code example: http://codepen.io/anon/pen/qmdzqJ
(Note that you may need to reload the example after opening dev tools since webgl stops printing after 256 reported errors/warning)

The issue appears for me when I **add filters**, to **two separate sprites**, using the **same base texture**.

**Comment by samme** [comment]
> <http://codepen.io/anon/pen/qmdzqJ>

Thanks. For me the sprites blink red and green and I don't see any console warnings/errors. What happens in yours?

**Comment by noseglid** [comment]
This.
![screen shot 2017-04-17 at 21 27 41](https://cloud.githubusercontent.com/assets/933880/25101471/be8146ea-23b4-11e7-9ece-97165e860024.png)

Did you reload *after* you opened devtools?

**Comment by samme** [comment]
Got it now. Firefox says

> Error: WebGL: texImage2D: Conversion requires pixel reformatting.  phaser.js:17473:5
> Error: WebGL: drawElements: Feedback loop detected between tex target 0x0de1, tex unit 0, levels 0-0; and framebuffer attachment 0x8ce0, level 0.  phaser.js:18892:5 [[WebGLSpriteBatch.js#L709](https://github.com/photonstorm/phaser-ce/blob/29bc2b2d76f432a34fdb36ecc8ee634e0d8fdaf0/src/pixi/renderers/webgl/utils/WebGLSpriteBatch.js#L709)]

Is it rendering correctly or no?

**Comment by noseglid** [comment]
Just tested your fix on my project with latest master from github and it works like charm! Thank you so much for fixing this and all effort you put into `phaser-ce`!

**Comment by samme** [comment]
Thanks @Xan0C
