### ISSUE TITLE
Phaser.PointerMode.TOUCH is undefined

### ISSUE THREAD

**Issue by daniel-nth** [photonstorm/phaser-ce#392]
This Issue is about a bug in the API.

Problem:
There are several references in the code to Phaser.PointerMode.TOUCH (Input.js and Button.js). This mode is undefined in Phaser.PointerMode. (Pointer.js). PointerMode knows CURSOR and CONTACT. This breaks Button.forceOut and Button.justReleasedPreventsOver on touch devices. This problem seems to have existed ever since [PointerMode was introduced](https://github.com/photonstorm/phaser-ce/commit/31e5202effaca20ffe5a3f6f231fb497471068f5). I didn't include sample code, because referencing an undefined constant is obviously a bug, but a can create a pull request if you agree with the proposed solution.

Affects
Phaser version(s): 2.9.1, still broken in b394e06 in master, possibly all versions >=2.4.4 

Proposal:
Change occurrences of Phaser.PointerMode.TOUCH to Phaser.PointerMode.CONTACT. 

Workaround:
// patch PointerMode before creating a game.
Phaser.PointerMode.TOUCH = Phaser.PointerMode.CONTACT;

**Comment by samme** [comment]
Sounds good to me.

**Comment by samme** [comment]
Hi @daniel-nth are you still interested in making a PR?

**Comment by daniel-nth** [comment]
Yeah, sorry. Had a bit on my plate at work.
