### ISSUE TITLE
Blurring tileset image in mobile devices problem

### ISSUE THREAD

**Issue by RenaudROHLINGER** [photonstorm/phaser-ce#394]
Hey ! 
I have an issue only on mobile (S8 so i shouldn't have any lag issue), my game is getting blurry and some offset are appearing when i move the camera (I repeated a jump action to prove it)

My param :
Physics : Arcade
Game width: 800
renderer: Phaser.CANVAS
Game height : 600
Map width: 2100
Map height : 390
scale : SHOW_ALL
antialias : false

I am not the first to have this issue :
--> http://www.html5gamedevs.com/topic/32275-blurring-tileset-image-in-mobile-devices-problem/

  * Live example:
![22286946_10215078333691987_675530959033991168_n](https://user-images.githubusercontent.com/15867665/31867135-f5998250-b757-11e7-84d3-f4e97fd28473.gif)

Have you guys any idea ? Otherwise I'll just go back to 2.6.2, looks like this is an issue of Phaser CE

**Comment by 16patsle** [comment]
I have had issues with blurry stuff on mobile before, with no reason. Would using WebGL be a possibility? That often solves a lot of inconsistencies for me at least.

**Comment by samme** [comment]
Can you compare <https://codepen.io/samme/full/oGreMZ/> on your mobile?

**Comment by RenaudROHLINGER** [comment]
Here a fork of your pen adapted to prove my issue : 
https://codepen.io/yakuno/pen/rYBEwm

With the example : 
![22556529_10215115742387181_5389771296022200320_n](https://user-images.githubusercontent.com/15867665/32112423-46a4e336-bb0b-11e7-9843-85ee88ebad94.gif)

Note :
If you go out of this area of the camera it'll clean all the mess and display it perfectly.

**Comment by samme** [comment]
Thanks. So it only happens on mobile and only after the camera has moved?

**Comment by RenaudROHLINGER** [comment]
Apparently. I cannot reproduce it on desktop.

**Comment by samme** [comment]
And it's not blurred if the camera has never moved?

You can try `forceFullRedraw` to see if it makes any difference: <https://codepen.io/samme/pen/YEzqYQ>.

**Comment by RenaudROHLINGER** [comment]
Indeed, forceFullRedraw fix the problem ! And yes it's not blurred if the camera has never moved

**Comment by RenaudROHLINGER** [comment]
Nevermind, if I set the layer.debug = false the problem will keep going. So basically layer.debug = true fix the issue ? :frowning:

**Comment by samme** [comment]
Well, not really, but it's good to know.

The second thing to try would be

```javascript
layer1.renderSettings.enableScrollDelta = false;
```

**Comment by RenaudROHLINGER** [comment]
Yep. That works !

**Comment by samme** [comment]
Can you check the value of `game.device.this.canvasBitBltShift`?

If it's `true` you could also try setting it to `false` before adding the tilemap etc. If it works that fix may be more efficient than disabling `enableScrollDelta`.

**Comment by RenaudROHLINGER** [comment]
game.device.this.canvasBitBltShift was set to false. I tried to set it to toggle the value and nothing changed. Furthemore setting a gravity with Arcade physique upper than 500 is making the camera choppy/flick too while scrolling (not blurred tho). I might have a misconfiguration on my game i guess, but my map is not big at all. Maybe I'll try to do another clean project to test.

**Comment by samme** [comment]
I mistyped, meant `game.device.canvasBitBltShift`.

**Comment by RenaudROHLINGER** [comment]
Yeah, mistyped too I meant "game.device.canvasBitBltShift", I saw you had mistyped and the value was false ^^

**Comment by RenaudROHLINGER** [comment]
renderSettings.enableScrollDelta = true is still an issue on mobile after lots of tests ; map gets blurred if we scroll even with : 
game.device.canvasBitBltShift = false;
layer1.renderSettings.forceFullRedraw = false;

@samme
