### ISSUE TITLE
iOS input causes sound issues?

### ISSUE THREAD

**Issue by DatKenwayGuy** [photonstorm/phaser-ce#395]
* A problem with my own code

Hello everyone, I'm quite new to GitHub and Phaser in general. For the last few months I've been working on a game using Phaser. As usual there are always some bumps in the road and most of the time I've been able to find a work around or a fix, but with this I've been stuck for a week already.

I'm developing an RPG-esque game for iOS and Android and so far I haven't come across any issues I was unable to fix. The issue is that when I want to test the game in iOS the input simply won't work. It works on android and it works via emulation on Google Chrome and Safari but on the actual device I'm using (iPhone 6, latest iOS version) it simply won't work. I keep getting this error 

> Uncaught TypeError: this._unlockSource.noteOn is not a function

I've been looking at many other forums and apparently it has something to do with sound and input on iOS. My game didn't have anything of sound in it so I added a little battle theme to the game to see if that would make a difference but sadly it didn't.

I'll leave a link of my game here and hope anyone could help me.

Ask away for any kind of code you need because I'm not certain which pieces of code I should post.

[https://www.u11377p12499.web0111.zxcs.nl/test/dungeonD.php](url)

**Comment by samme** [comment]
Which Phaser version are you using?

**Comment by DatKenwayGuy** [comment]
I'm currently using Phaser v2.0.1, the min script.
