### ISSUE TITLE
Tween stop → start is ambiguous

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#401]
* A (minor) bug in the API:
  * Phaser version(s): 2.9.2, likely earlier
  * Live example: <https://samme.github.io/phaser-plugin-debug-tween/>
    1. Start the tween.
    2. Stop the tween before it completes.
    3. Start the tween again.
  * What should happen: The tween doesn't run. The tween has `isRunning=false` and TweenData properties doesn't change.
  * What happens instead: The tween doesn't run. The tween has `isRunning=true` and some TweenData properties are reset.

The ambiguity is that Tween#update rejects a stopped tween but Tween#start doesn't. So the tween starts, sort of, but never advances.

[Tween#stop](https://photonstorm.github.io/phaser-ce/Phaser.Tween.html#stop) implies stopped tweens shouldn't be restarted so it seems Tween#start should reject them as well. I favor adding a console warning too but I'm not sure what authors expect here.

**Comment by thomasstark2** [comment]
Isn't the issue to stop the tween after onComplete ?

**Comment by samme** [comment]
There's no need to call `stop` after the tween is completed, and it has no significant effect. It actually doesn't prevent the tween from being started again, as it would in the example sequence.

**Comment by thomasstark2** [comment]
I've tested your live example and it seems indeed that when you stop the tween you can't start it again

**Comment by samme** [comment]
Yes, that seems the intended behavior, but the docs could be improved on that point.

**Comment by samme** [comment]
<https://github.com/photonstorm/phaser/issues/2021>
