### ISSUE TITLE
WebGL Device check doesn't include contextOptions that are used by WebGLRenderer, causing the game to not run in some situation

### ISSUE THREAD

**Issue by AleBles** [photonstorm/phaser-ce#402]
This Issue is about (pick one, ✏️ delete others)

* A bug in the API:
  * Phaser version(s): All
  * Live example: Depends on the setup, but any game will fail on a browser that doesn't support stencilbuffer
  * What should happen: The game should fallback to canvas rendering
  * What happens instead: The game just doesn't run

So basicly [Phaser.Device's webgl check](https://github.com/photonstorm/phaser-ce/blob/master/src/utils/Device.js#L803) Doesn't include the options (like stencil buffer) that are used to create the context in the [webgl renderer](https://github.com/photonstorm/phaser-ce/blob/master/src/pixi/renderers/webgl/WebGLRenderer.js#L220)

Causing it to [throw an error](https://github.com/photonstorm/phaser-ce/blob/master/src/pixi/renderers/webgl/WebGLRenderer.js#L226) that doesn't get [caught](https://github.com/photonstorm/phaser-ce/blob/master/src/core/Game.js#L835).

Ideally it should catch this error and fall back to canvas if the renderType is set to AUTO

**Comment by samme** [comment]
https://github.com/pixijs/pixi.js/issues/1431

**Comment by samme** [comment]
I can add `{stencil: true}` to the check in Phaser.Device.

Want to check <https://www.khronos.org/registry/webgl/sdk/tests/conformance/context/context-attributes-alpha-depth-stencil-antialias.html>?

**Comment by AleBles** [comment]
For me it's fine, I'm not in possession of a device that doesn't support stencil buffer, but I'm seeing these error's being reported in our tools.

I remember the PIXI issue too and assume adding the stencil buffer to the options will fix it. I'm not using CE myself, so I'll be monkey patching it in our games. I'll let you know if that fix is sufficient enough based on the user reports :)

**Comment by samme** [comment]
The other, slightly more complicated change would be to fall back to CANVAS (from AUTO) during the game boot if it fails to create a WebGL context. That would include all the context attributes in use (not just `stencil`).

**Comment by samme** [comment]
@AleBles any results?

**Comment by AleBles** [comment]
The amount of errors happening halved, but they still exist. Perhaps because I create the games with transparency?

Anyway adding the stencil buffer to the device check makes sense anyway, so for now let's just go with that, I guess :)
