### ISSUE TITLE
Remove deprecated things

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#403]
- Phaser.ArrayUtils.rotate → Phaser.ArrayUtils.rotateLeft
- Phaser.Device.isConsoleOpen
- Phaser.Loader#useXDomainRequest (IE9)
- Phaser.Loader#xhrLoadWithXDR (IE9)
- Phaser.Particles#update
- Phaser.Polygon.points (set) → setTo
- Phaser.Touch#addTouchLockCallback → Phaser.Input#addTouchLockCallback
- Phaser.Touch#removeTouchLockCallback → Phaser.Input#removeTouchLockCallback
- PIXI.BaseTexture#updateSourceImage → Phaser.Component.LoadTexture#loadTexture
- RevoluteConstraint#motorIsEnabled → motorEnabled
- Shape.RECTANGLE → Shape.BOX

**Comment by samme** [comment]
If Phaser 3 supports IE9 perhaps we should keep the XDomainRequest?

**Comment by maxp-edcast** [comment]
I'm getting this warning ... not sure if this is covered in the above list but the method `Phaser.Device._readyCheck` is not named ...

```
bundle.js:81143 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
boot @ bundle.js:81143
boot @ bundle.js:40023
Phaser.Device._readyCheck @ bundle.js:64842
```

it's a shame, i just realized phaser 3 was out by seeing this warning message and visiting their repo. Apparently something won't work in just a few days time ..

**Comment by samme** [comment]
See #385.
