### ISSUE TITLE
Problem with Installing Plugin Phaser healthMeter.js

### ISSUE THREAD

**Issue by lastpeony** [photonstorm/phaser-ce#404]
* An error in the TypeScript definitions ? 
* A problem with my own code ?

I am trying to install this plugin :

https://github.com/matthiaswh/phaser-health-meter

I put js file into this directory:
[![dir][1]][1]

Included it as : 

    import {HealthMeter} from "phaser-ce/src/plugins/healthMeter"

And as mentioned in documentation:

    this.player.health=50;
      this.player.maxHealth = 100;
    
      this.playerHealthMeter = this.game.add.plugin(Phaser.Plugin.HealthMeter);
        this.playerHealthMeter.bar(
            this.player,
            {x: 20, y: 100, width: 100, height: 20}
        );

This is the error:
[![enter image description here][2]][2]

I guess im putting js file to wrong directory

  [1]: https://i.stack.imgur.com/mxo1R.png
  [2]: https://i.stack.imgur.com/jSiqQ.png

**Comment by andrewjb123** [comment]
it looks like that plugin doesnt provide .ts definitions?

you can maybe do game.add.plugin(<any>Phaser.Plugin.HealthMeter);

to just get ts to compile. and if the js is included it should find it?
