### ISSUE TITLE
Dragging sprites that are fixed to camera is broken when camera scaled

### ISSUE THREAD

**Issue by kakaoscsiga** [photonstorm/phaser-ce#405]
* A bug in the API:
  * Phaser version(s): 2.9.2
  * Live example: https://codepen.io/anon/pen/RjJbLo?editors=0010
  * What should happen: The sprite should be dragged by the pointer
  * What happens instead: The sprite is dragged with an increasing offset to the pointer

(Relates to: Issue #297, Pull Request #300)

**Comment by kakaoscsiga** [comment]
https://github.com/photonstorm/phaser-ce/compare/master...kakaoscsiga:master

**Comment by samme** [comment]
<https://codepen.io/samme/pen/rYqYar?editors=0010>
