### ISSUE TITLE
Tween.repeat not working

### ISSUE THREAD

**Issue by husengbatute29** [photonstorm/phaser-ce#408]
* A bug in the API:
  * Phaser version: 2.4.7 and above
  * Live example: https://codepen.io/anon/pen/japGEB
  * What should happen: Tween repeats
  * What happens instead: Tween does not repeat

**Comment by samme** [comment]
This is some quirk of the API, I have to find it …

**Comment by samme** [comment]
<https://codepen.io/samme/pen/qVMobW>
