### ISSUE TITLE
Phaser + p2 issue on example "collide custom bounds"

### ISSUE THREAD

**Issue by Nek-** [photonstorm/phaser-ce#409]
This Issue is about

* A bug in the API: 
  * Phaser version(s): 2.9.2
  * Live example: https://samme.github.io/phaser-examples-mirror/p2%20physics/collide%20custom%20bounds.html
  * What should happen: balls should not go out of the rectangle
  * What happens instead: balls goes out on the left

I have no idea what's wrong but the bug is obvious :/ .

[edit] I'm starting the debug. The bug was not present in the version 2.6.2 of phaser but is present in the version 2.7.3

**Comment by samid737** [comment]
https://github.com/photonstorm/phaser-ce/pull/411#issuecomment-350672823

**Comment by samme** [comment]
Why did it change after v2.6.2 though?

**Comment by Nek-** [comment]
@samme it's a p2.js upgrade to last version. I still think it's broken but I can't provide a correct fix, and it works with a simple workaround.
