### ISSUE TITLE
TweenManager.isTweening() should check tween.pendingDelete

### ISSUE THREAD

**Issue by mblais** [photonstorm/phaser-ce#414]
This Issue is about
* A bug in the API:
  * Phaser version(s): Phaser CE v2.9.1 
  * What should happen: `TweenManager.isTweening()` should return false when testing a sprite that has no uncompleted tweens
  * What happens instead: `TweenManager.isTweening()` returns true when testing a sprite that has only completed tweens (i.e. with `pendingDelete`===true)

`TweenManager.isTweening()` only checks if any tween exists in `_tweens`, but it does not test whether these tweens are already completed (i.e., `pendingDelete`===true).

Thus e.g., when `myTween.onComplete()` is dispatched for a sprite, `isTweening()` is not useful to check whether any (other) uncompleted tweens still remain on the sprite.

**Comment by samme** [comment]
Would the result be correct during the next frame/update? The tween should be removed from `_tweens` then, right?

**Comment by samme** [comment]
I'll add a second argument.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/xpxbgV>

**Comment by mblais** [comment]
Thanks @samme - that will make my code much simpler in the case where tweens are removed, and this must be detectable within the same update processing.

**Comment by mblais** [comment]
You actually need another set of parens in this change  - the line should be:

`            return (tween.target === object) && (!checkIsRunning || (tween.isRunning && !tween.pendingDelete));`
