### ISSUE TITLE
style parameter in Phaser.Text constructor no longer optional

### ISSUE THREAD

**Issue by naglfar** [photonstorm/phaser-ce#415]
This Issue is about

* A bug in the API:
  * Phaser version: 2.9.3
  * Live example: game.add.text(0, 100, 'text')
  * What should happen: text object should be created with an empty style
  * What happens instead: an error is thrown due to style being undefined

Due to the change in [https://github.com/photonstorm/phaser-ce/commit/c26267d60fcfd503dd80a1622c886da3d435ded4](https://github.com/photonstorm/phaser-ce/commit/c26267d60fcfd503dd80a1622c886da3d435ded4) our project crashes when trying to create text objects without / with the default style. According to the documentation the style parameter should be optional.

**Comment by samme** [comment]
You can work around this by passing `{}` for now.
