### ISSUE TITLE
Sprite.body.position.x/y doesn't update after setting Sprite.x/y until next frame

### ISSUE THREAD

**Issue by hedgehog125** [photonstorm/phaser-ce#417]
[AABB error demo.zip](https://github.com/photonstorm/phaser-ce/files/1565606/AABB.error.demo.zip)
Hello.

I've been developing a game in Phaser but I've hit a problem. I've been trying to make the spaceships move back when they spawn so that they don't spawn inside each other.
I've been using `game.physics.arcade.collide(sprite1, sprite2);` to detect collisions. However, I think I've found an issue in the code for this function. I've managed to deduce the problem, `Sprite.body.position.x/y` doesn't update after setting `Sprite.x/y` until next frame (hence the title).

To demonstrate this problem I've created a small program which has two sprites on top of each other the idea is they move away until they no longer touch, so they aren't on top of each other. (see the attached file) (although, there isn't much to see, so you probably want to look at my code and the comments).
It creates an infinite loop because Phaser is performing collision detection as if the sprite was in the its position at the start of the update function.
However, by the next frame `Sprite.body.position` has updated and it is no longer touching. (except we never see this frame because of the infinite loop)
I know I could probably use the physics to do this for me, but the issue still remains.

One way of fixing the issue would be to update `Sprite.body.position.x` and `Sprite.body.position.y` in the `game.physics.arcade.collide` function (and `game.physics.arcade.overlap` function too).

But, I'm open to suggestions. I'm pretty certain this is a Phaser bug as I've tested and researched it.
Thanks.

**Comment by samme** [comment]
I think you're seeing the normal behavior. It is a little complicated.

Both [Arcade#collide](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html#collide) and [Arcade#overlap](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html#overlap) read `body.position`. **overlap** never updates `body.position` because it only tests for collisions. **collide** updates `body.position` [only if it performs separation](https://gist.github.com/samme/cbb81dd19f564dcfe2232761e575063d).

For that test case this would work:

```javascript
while (Game.physics.arcade.overlap(sp1, sp2)) {
  sp1.body.position.x++ // Move away
}
```

**Comment by hedgehog125** [comment]
Thanks for your response. I've changed my code to set the body position then perform collision detection and then revert it back...

```var xWas = sp1.x
var yWas  = sp1.y
var leftX = getLeftX(sp1)
var topY = getTopY(sp1)
var bodyXWas = sp1.body.x
var bodyYWas = sp1.body.y
sp1.x = 0
sp1.y = 0
sp1.body.x = leftX
sp1.body.y = topY
while (Game.physics.arcade.collide(sp1, sp2)) {
		sp1.x = 0
		sp1.x++ // Move away
		sp1.body.x = sp1.body.x + sp1.x
}
sp1.x = sp1.body.x + (sp1.anchor.x * sp1.width)
sp1.y = sp1.body.y + (sp1.anchor.y * sp1.height)
sp1.body.x = bodyXWas
sp1.body.y = bodyYWas
```
