### ISSUE TITLE
Missing documentation for distanceBetweenCenters?

### ISSUE THREAD

**Issue by bananatron** [photonstorm/phaser-ce#418]
This Issue is about:
* An error in the documentation

In the [CE documentation](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html) (and old phaser docs) a few methods (distanceToPointer & distanceToXY) mention using `distanceBetweenCenters()` instead, but I can't find any documentation for this method, in particular?

**Comment by samme** [comment]
I'm not sure such a method has ever existed. 😄 It definitely doesn't exist now. I can maybe add it as an argument to [distanceBetween](https://photonstorm.github.io/phaser-ce/Phaser.Physics.Arcade.html#distanceBetween).

**Comment by bananatron** [comment]
It's not something I desperately need, I just was poking around for it after I saw the reference.

Regardless, might be worth removing it and/or putting an explanation on how to adjust center points for anchors or whatever?
