### ISSUE TITLE
WebAudio memory never cleaned up

### ISSUE THREAD

**Issue by derekeg** [photonstorm/phaser-ce#427]
The commit https://github.com/photonstorm/phaser-ce/commit/b1c5cd285decf8fe2ba67b741b01efdce6ee018f caused a regression of https://github.com/photonstorm/phaser-ce/issues/64. If you load audio files, they are once again never cleaned up from memory.

This is due to adding the following code back in on lines 927-934 in Sound.js.

```javascript
if (this.externalNode)
{
    this._sound.disconnect(this.externalNode);
}
else if (this.gainNode)
{
    this._sound.disconnect(this.gainNode);
}
```

The original discussion thread can be found here

http://www.html5gamedevs.com/topic/19339-audio-memory-usage-headache/

**Comment by samme** [comment]
Thanks. Can you make a PR? Would it bring back #78?

**Comment by samme** [comment]
@vpmedia thoughts?

**Comment by samme** [comment]
@derekeg how should I reproduce this?

**Comment by derekeg** [comment]
I tried to reproduce it this week and for some reason it isn't happening anymore. Probably okay to close this.

**Comment by samme** [comment]
OK, please reopen if you see it again.
