### ISSUE TITLE
Hand Cursor automatically Changes to Normal cursor on Multiple clicks on Button

### ISSUE THREAD

**Issue by ankush-badyal** [photonstorm/phaser-ce#428]
Hi,
In Chrome, on multiple clicking a button,  the Hand cursor changes from Hand to a normal cursor, And this works Perfectly on IE & Firefox

**Comment by samme** [comment]
I don't see this on my Chrome. I clicked on the button several times and the hand cursor never changed: <https://samme.github.io/phaser-examples-mirror/buttons/action%20on%20click.html>

**Comment by ankush-badyal** [comment]
Hi, 

But I can reproduce the same on you link too. My chrome version is Version 63.0.3239.132.

I running this on a Dell Latitude E5540 having 8 gb ram and Intel HD Graphics 4400.

Please inform me if you need any more information
