### ISSUE TITLE
Buttons states are active.

### ISSUE THREAD

**Issue by ankush-badyal** [photonstorm/phaser-ce#429]
On moving mouse out of the canvas, if the mouse was over a button, the button stays in hover state and if we move the mouse back on canvas at other location then the mouse stays in hand cursor and the button stays in hover state, until you move the mouse over the button again and move out on the canvas.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/zppmZj>

**Comment by ankush-badyal** [comment]
The example you have created is what i wanted to point at.

**Comment by squaresun** [comment]
#439 

I've made a PR trying to fix this.

**Comment by samme** [comment]
Could this be solved by adding

```javascript
input.interactiveItems.callAll('_pointerOutHandler', this);
```

in Phaser.Pointer#stop?

**Comment by squaresun** [comment]
@samme I haven't noticed interactiveItems inside input.
It seems that the Phaser.InputHandler#_pointerOutHandler would be called twice (The mouse goes out of canvas and get back to canvas). 

So I put this
```javascript
this.input.interactiveItems.callAll('_pointerOutHandler', this.input.mousePointer);
```
in Phaser.Mouse#onMouseOut and it seems ok.

**Comment by samme** [comment]
@squaresun can you explain? Thanks.

> It seems that the Phaser.InputHandler#_pointerOutHandler would be called twice (The mouse goes out of canvas and get back to canvas).

**Comment by squaresun** [comment]
@samme 
When the mouse goes out of canvas, _pointerOutHandler called. (That sounds normal)
But when the mouse goes into canvas from outside, _pointerOutHandler called again (Which is not expected)

**Comment by samme** [comment]
That might be OK. I guess I'll have to try it.

**Comment by samme** [comment]
I’m going to move this behavior under [stopOnGameOut](https://photonstorm.github.io/phaser-ce/Phaser.Mouse.html#stopOnGameOut).
