### ISSUE TITLE
Error importing phaser using typescript in Ionic2

### ISSUE THREAD

**Issue by esteban-filardi** [photonstorm/phaser-ce#43]
I was trying to use phaser in a Ionic2 application. 
When I try to import phaser I get the following error:

> File '.../node_modules/phaser-ce/typescript/phaser.comments.d.ts' is not a module.

Even vscode warns me there's something wrong with the import statement.

![2017-03-03 4](https://cloud.githubusercontent.com/assets/1585383/23572238/76be771e-004c-11e7-91af-77369486791b.png)
![capture](https://cloud.githubusercontent.com/assets/1585383/23572239/76c68954-004c-11e7-8951-e07faa7ccc0d.PNG)

Here's the code:

```
import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';

import {Phaser} from 'phaser-ce';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {
    
  }
```
Can anyone help me resolve this issue?

**Comment by smatthews1999** [comment]
Pretty sure that's not how you do it.

Go to your **angular.cli.json** file (or whatever ionic uses for webpack config) and add phaser script...
![image](https://cloud.githubusercontent.com/assets/562964/23661511/f682501c-031a-11e7-9952-b24aadf44a6e.png)

Then in your tsconfig.json file add the reference to the types.
![image](https://cloud.githubusercontent.com/assets/562964/23661585/3f39d000-031b-11e7-8b40-ad20c430c089.png)

This sometimes does not work for me and have to resort to triple slash type reference...
![image](https://cloud.githubusercontent.com/assets/562964/23661721/86087784-031b-11e7-89f7-891d2c4f41fe.png)

**Comment by rpascal** [comment]
I am receiving the same error as you. Were you able to get this working or no?

**Comment by esteban-filardi** [comment]
No, I gave up of trying to use Ionic and Phaser using Typescript. Sorry :-/

**Comment by Dreaded-Gnu** [comment]
I fixed the phaser-ce module name for typescript a while back now, so it should not fail any longer with version 2.7.5.

If it still fails, please provide a sample application, so that the issue can be fixed

**Comment by esteban-filardi** [comment]
I've updated phaser-ce to 2.7.5 and although the error is different, the application still doesn't work.

Importing like this

`import {Phaser} from 'phaser-ce';`

Results in
> Module "phaser-ce" has no exported member 'Phaser'

Importing like this

`import * as Phaser from 'phaser-ce';`

results in

`PIXI is not defined`

I've created a repository in case you want to check it out:

https://github.com/esteban-filardi/phaser-test

I guess you should install ionic globally,

> npm install -g cordova ionic

Then you can run:

> ionic lab

to test the application.

**Comment by Dreaded-Gnu** [comment]
Normally, when using webpack only, the following import should be okay, when correctly configured: `import * as Phaser from 'phaser-ce';`

Ionic2 and webpack is importing the wrong file. You've to extend the webpack configuration:
- Copy following file into your project and extend it: `node_modules/@ionic/app-scripts/config/webpack.config.js`

```
var path = require('path');
var webpack = require('webpack');
var ionicWebpackFactory = require(process.env.IONIC_WEBPACK_FACTORY);

// new, necessary for resolving to correct files (begin)
var rootDir = path.resolve(__dirname),
    phaser_module = path.join(rootDir, "node_modules", "phaser-ce"),
    phaser = path.join(phaser_module, "build", "custom", "phaser-split.js"),
    pixi = path.join(phaser_module, "build", "custom", "pixi.js"),
    p2 = path.join(phaser_module, "build", "custom", "p2.js");
// new, necessary for resolving to correct files (end)

module.exports = {
  entry: process.env.IONIC_APP_ENTRY_POINT,
  output: {
    path: '{{BUILD}}',
    publicPath: 'build/',
    filename: process.env.IONIC_OUTPUT_JS_FILE_NAME,
    devtoolModuleFilenameTemplate: ionicWebpackFactory.getSourceMapperFunction(),
  },
  devtool: process.env.IONIC_SOURCE_MAP_TYPE,

  resolve: {
    extensions: ['.ts', '.js', '.json', '.js'], // <-- extended by considering also extension '.js'
    modules: [path.resolve('node_modules')],
    // new for alias resolve (begin)
    alias: {
      "pixi": pixi,
      "p2": p2,
      "phaser-ce": phaser
    }
    // new for alias resolve (end)
  },

  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      // new for exposing pixi, correct phaser and p2 into global scope (begin)
      {
        test: /pixi\.js/,
        loader: "expose-loader?PIXI"
      },
      {
        test: /phaser-split\.js/,
        loader: "expose-loader?Phaser"
      },
      {
        test: /p2\.js/,
        loader: "expose-loader?p2"
      },
      // new for exposing pixi, correct phaser and p2 into global scope (end)
      {
        test: /\.ts$/,
        loader: process.env.IONIC_WEBPACK_LOADER
      }
    ]
  },

  plugins: [
    ionicWebpackFactory.getIonicEnvironmentPlugin(),
  ],

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
};
```

Then you can easily import phaser ce by using following import statements:
```
import "pixi";
import "p2";
import * as Phaser from "phaser-ce";
```

**We should consider adding it within the readme, or something else.**

**Comment by Dreaded-Gnu** [comment]
When you don't want to copy the webpack file, you could write a partial and use webpack-merge to merge the app scripts webpack config with the partial one of you. 
Then you don't have to check on each update of ionic scripts package the webpack config again.

**Comment by samme** [comment]
Closing for #96

**Comment by archagy** [comment]
Okay I guess is not the best way but I was able to run it with this steps:

- Copy pixi.js and p2.js from node_modules/phaser-ce/build
- Paste them into src/assets/scripts/  (I created scripts folder)
- I added the scripts into index.html from src folder in the following order.

1.  pixi.js
2.  p2.js
3.  main.js

then import it into the project in this way
`import * as Phaser from "phaser-ce";`


Sorry for my bad English and I hope this helps someone.

**Comment by arijitnaskar** [comment]
I did as said by Dreaded-Gnu above.
After doing all the configuration, if I run `ionic lab` its working with no error.
Then I tried to build the apk with `ionic cordova build android --prod`  
this is throwing the following error:

```
Error: ./src/pages/home/home.js
Module not found: Error: Can't resolve 'pixi' in 'D:\PhoneGapProjects\firstgame\src\pages\home'
resolve 'pixi' in 'D:\PhoneGapProjects\firstgame\src\pages\home'
  Parsed request is a module
  using description file: D:\PhoneGapProjects\firstgame\package.json (relative path: ./src/pages/home)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\PhoneGapProjects\firstgame\package.json (relative path: ./src/pages/home)
    resolve as module

```

Please any one help. I am stuck here.
