### ISSUE TITLE
Sound.onMarkerComplete still only apparently fires once and marker looping doesn't work

### ISSUE THREAD

**Issue by WVI** [photonstorm/phaser-ce#430]
Marker stuff on Phaser has been wonky since 2014.

Phaser.Sound.play(marker, position, volume, loop, forceRestart) 
If the play function takes a marker as the first parameter, "loop" won't do anything, true or false. It won't replay the marker. Maybe this is expected behavior, however:

Phaser.Sound.addMarker(name, start, duration, volume, loop)
The "loop" parameter does nothing here either.

Sound.onMarkerComplete.add will fire once, then never again, which is the behavior expected of Sound.onMarkerComplete.addOnce

Here's the sandbox, featuring a cross-origin request: phaser.io/sandbox/wvXXqksn
This sandbox tries three different ways to get marker B to loop and it won't happen.

* A bug in the API:
  * Phaser version(s): CE 2.9.4

**Comment by samme** [comment]
Do you know if markers have ever looped?

You might try [audio sprites](https://photonstorm.github.io/phaser-ce/Phaser.AudioSprite.html) instead.

**Comment by WVI** [comment]
Thanks for the suggestion, but as it stands, my entire game relies on audio markers and I'm dead set on making sure they work the way they're supposed to.

**Comment by samme** [comment]
These seem to loop correctly: <https://codepen.io/samme/pen/wppVmZ>

**Comment by samme** [comment]
So it looks like the problem in <http://phaser.io/sandbox/wvXXqksn> is that a non-looped marker dispatches `onMarkerComplete` from `stop`, and `stop` erases `currentMarker` immediately afterwards: <https://codepen.io/samme/pen/vpdYWy?editors=0010>.

For that case you can actually use the `onStop` signal instead and examine its argument, `prevMarker`.

**Comment by samme** [comment]
`onStop` is dispatched **after** the erasure so you can play a new marker again without any problem.

**Comment by WVI** [comment]
So after reading that, I was still sure there was a use case that wasn't working. I almost put a note in that sandbox like "Try playing marker 'a' with loop set to true",
`game.pokemonThemeBGM.addMarker('a', 0, 4.029, 1.0, true);`
then I went back, and there it is...it's working. So is
`game.pokemonThemeBGM.play('a', 0, 1.0, true);`

I feel like I need to lie down.

**Comment by WVI** [comment]
Just so we know I'm not insane, if I wanted to go with onLoop instead, the following doesn't cause B to play either:

![image](https://user-images.githubusercontent.com/1386475/34725331-8dd9986c-f51e-11e7-8e3f-ab00d4bc3a72.png)

**Comment by samme** [comment]
> Regardless, I'm still not sure how to get the onStop signal to create the behavior I want. I think onStop tends to create an audible silence, whereas with onMarkerComplete you have a shot of the loop being seamless?

Phaser always calls [stop](https://photonstorm.github.io/phaser-ce/Phaser.Sound.html#stop) in this case, no matter how you use the signals. But it sounds fine if you call play via onStop: <https://codepen.io/samme/pen/baLvjL>

**Comment by samme** [comment]
> I get that stop erases currentMarker after firing the signal, but is there any reason that playing the sound after onMarkerComplete shouldn't immediately set currentMarker back to the value set in play()?

It's calling play **within** onMarkerComplete that's the problem, because `currentMarker` is erased immediately after that signal is dispatched.

<https://github.com/photonstorm/phaser-ce/blob/f33d8f9c93af781f964f2138c01d6ab493812716/src/sound/Sound.js#L958-L972>

**Comment by WVI** [comment]
Thanks for the explanation. I don't know if this comes across differently on different browsers' implementations of Web Audio, but personally, calling the loop point from onMarkerComplete tends to sound seamless, whereas calling it from onStop as you've just done consistently has an extremely noticeable hitch, and I want to do everything I can to make that transition inaudible. The looping on the next marker always sounds good, though.

**Comment by samme** [comment]
Hope to add some better docs on this soon.
