### ISSUE TITLE
Add `touchUnlocked` signal to Phaser.SoundManager

### ISSUE THREAD

**Issue by qdrj** [photonstorm/phaser-ce#434]
It's not an issue, more like a feature request.

I think `touchUnlocked` signal will be nice addition to the API.

Thanks in advance!

**Comment by samme** [comment]
I think if you use [addTouchLockCallback](https://photonstorm.github.io/phaser-ce/Phaser.Input.html#addTouchLockCallback) with `onEnd=true` it may be equivalent. You could try it.

**Comment by qdrj** [comment]
Yes, I know about this method. But in case of WebAudio the sound being unlocked during `SoundManager.update` loop. So for consistency signal would be better. Plus we have `touchLocked` field so introducing 'onTouchUnlocked' signal will be logical.

Looks like I finally need to figure out how to contribute properly and do it by myself :)

**Comment by samme** [comment]
I can't decide on `onUnlock` or `onTouchUnlock`.

**Comment by qdrj** [comment]
@samme since there is a `touchLocked` field  than `onTouchUnlock` will be more sensible I think
