### ISSUE TITLE
Mouse/Touch Event cancelling not working

### ISSUE THREAD

**Issue by ankush-badyal** [photonstorm/phaser-ce#441]
Hi,

If a button is pressed and released outside its bounds then the handlers attached to up event or click event should not work where as in current implementation it fire the handler.

https://codepen.io/samme/pen/zppmZj

**Comment by samme** [comment]
I think this is the intended behavior, but you can use the `isOver` argument to [onInputUp](https://photonstorm.github.io/phaser-ce/Phaser.Events.html#onInputUp) (<https://codepen.io/samme/pen/ZvwJgB>) or you can override the default behavior in [Button#onInputUpHandler](https://photonstorm.github.io/phaser-ce/Phaser.Button.html#onInputUpHandler) (<https://codepen.io/samme/pen/eyxELz>).

**Comment by ankush-badyal** [comment]
Hi Samme, 
Can you please update the API documentation with isOVer as this is not mentioned there?
