### ISSUE TITLE
Phaser in/out events not working as expected on mobile. 

### ISSUE THREAD

**Issue by darajava** [photonstorm/phaser-ce#443]
This Issue is about

* A bug in the API:
  * Phaser version: v2.6.2
  * Live example: https://codepen.io/anon/pen/LeqByY (Note, must be opened with mobile)

Hi guys, I had initially posted this as a problem with my code, but I think it's a bug with Phaser.

I have an `onInputOver` and an `onInputOut` on an element, however it doesn't allow the `onInputOver` unless there has been an `onInputOut`, or `onInputOver` hasn't yet been called.

Example:

1) User drags thumb onto element, `onInputOver` event fired

2) User *lifts* thumb, doesn't slide out, `onInputUp` fired

3) User drags thumb in again and `onInputOver` isn't fired until after `onInputOut` is

This works on desktop with the mouse, but not on a phone as the input can be lifted entirely. Is this expected behaviour? If so, are there any workarounds? I've tried removing all events on the button and it still doesn't work

I think a fix should be to allow the onInputOut and onInputOver events to happen as many times as needed.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/KZJLaM>

**Comment by darajava** [comment]
Thank you, yes that demonstrates the issue better. So am I correct in saying that this is a bug? Is there any workaround?

**Comment by samme** [comment]
Maybe. It is inconsistent.

I would either omit the Out/Over callbacks when touch is present (`game.device.touch`) or try to force onInputOut: <https://codepen.io/samme/pen/aEMzvv>.

**Comment by darajava** [comment]
Thank you, that worked for me.
