### ISSUE TITLE
Input Scaling bug when Viewport scaling isn't 1x in Google Chrome 64

### ISSUE THREAD

**Issue by tlhunter** [photonstorm/phaser-ce#450]
I'm having an issue similar to #87. In my application I rely on meta viewport scaling. This is nice because I can get arbitrary scaling levels to get exactly the scale I need without the need to keep track of the ratio in code. Works great with iOS and Android. Why my issue my differ from #87 is that I don't explicitly scale the game world.

The problem is that if I scale the viewport by, say, 2.5x, then I need to scale the input by `1 / 2.5`. If I don't scale the input then clicks don't register in the same place. This bug only seems affects Google Chrome 64. It doesn't affect Mobile Safari, Firefox, or Google Chrome <= 63. UPDATE: Also doesn't affect Google Chrome 65.

I'm seeing the bug with Phaser CE v2.9.4 with either WebGL or 2D.

While experimenting and trying to reproduce the error with raw canvas (to see if the issue is outside of Phaser), I did note that canvas `onclick` events between the two versions of Chrome are identical. The global `screen` object is the same as well.

Currently I use the following hack to fix the issue:

```javascript
const SIZE_OF_TILE = 16;
const SCREEN_WIDTH_IN_TILES = 11;
// How I normally dynamically scale the viewport
function scaleViewport() {
  const scale = (window.innerWidth / SIZE_OF_TILE / SCREEN_WIDTH_IN_TILES).toFixed(2);
  console.log(`Setting viewport scale to ${scale}`);

  // Note that bug will happen if either viewport is scaled dynamically like below or with <meta name="viewport" tag
  const viewport = document.querySelector("meta[name=viewport]");
  viewport.setAttribute('content', `width=device-width, initial-scale=${scale}, maximum-scale=${scale}, user-scalable=0, minimal-ui`);

  // hack
  if (window.chrome) {
    let version = 0;
    try {
      version = Number(navigator.appVersion.match(/.*Chrome\/([0-9\.]+)/)[1].split('.')[0]);
    } catch(e) { }

    if (version === 64) { // Doesn't affect Chrome v63 or v65
      window.game_input_scale_override = 1 / scale;
    }
  }
}

// Later, once game is initialized:
if (window.game_input_scale_override !== 1) {
  console.warn('WARNING: Chrome v64 breaks input scaling with Phaser! Overriding game.input.scale properties!');
  this.game.input.scale.x = window.game_input_scale_override;
  this.game.input.scale.y = window.game_input_scale_override;
  this.game.input.scale = Object.freeze(this.game.input.scale); // value reverts upon re-focusing window
}
```

Sorry that I don't have an actual Phase code example. I'll try to add one when I have more time.

**Comment by samme** [comment]
You can use `game.debug.inputInfo(…)` to verify the input coordinates and `game.debug.scale(…)` to (maybe) verify the viewport dimensions.

**Comment by QuipHop** [comment]
got same issue
Ubuntu/Chrome 64.0.3282.119 (Official Build) (64-bit)/ Phaser CE 2.10.0

**Comment by samme** [comment]
Oddly similar to <http://www.html5gamedevs.com/topic/35619-phaserio-example-behaves-differently-when-self-hosted/?tab=comments#comment-204958>, where `<meta name=viewport>` is absent in Chrome.

**Comment by tlhunter** [comment]
FWIW, this issue no longer applies to Chrome 65.

**Comment by samme** [comment]
I'm betting on a Chrome bug.
