### ISSUE TITLE
error in typescript definition: gamepad.axis is not available

### ISSUE THREAD

**Issue by seiyria** [photonstorm/phaser-ce#452]
* An error in the TypeScript definitions

Here is my code:

```
const KeyToGamepad = {
  Down: (gamepad: Phaser.Gamepad) => {
    return gamepad.isDown(Phaser.Gamepad.XBOX360_DPAD_DOWN)
        || (<any>gamepad).axis(Phaser.Gamepad.XBOX360_STICK_LEFT_Y) >= 0.1;
  }
};
```

I have to <any> to use the axis function.

**Comment by samme** [comment]
What's the error message?

**Comment by seiyria** [comment]
It's something like "gamepad.axis is not a function".

**Comment by samme** [comment]
<https://photonstorm.github.io/phaser-ce/Phaser.SinglePad.html#axis>

**Comment by samme** [comment]
This code works for me:

```typescript
this.input.gamepad.start();
let pad1 = this.input.gamepad.pad1;
pad1.axis(1);
```

See <https://samme.github.io/phaser-examples-mirror/input/gamepad.html>.

**Comment by seiyria** [comment]
Was this fixed in a patch, or did it work before patching for you? Because I haven't updated my local but it still complains about the code in the OP.

**Comment by samme** [comment]
I think it's just an error in your code. Phaser.SinglePad (e.g. `game.input.gamepad.pad1`) has an axis method but Phaser.GamePad (e.g. `game.input.gamepad`) doesn't. It's a little confusing how they're named.
