### ISSUE TITLE
Audio volume variation not working in latest Firefox (58.0.1)

### ISSUE THREAD

**Issue by rafaelferreiraql** [photonstorm/phaser-ce#459]
Now, I don't know if (and I don't even think that) the problem is Phaser itself, but the fact is, since the latest Firefox update (58.0.1), I found myself unable to fade in the volume, be it with fadeIn(), fadeTo() or even tweening the volume from 0 to 1. What happens is that the sound plays in a low volume instead of raising it, snapping to the right value if muted and unmuted (for example by unfocusing).

Could reproduce with the [official fade in example](https://phaser.io/examples/v2/audio/fade-in). The same example worked accurately in Chrome.

**Comment by samme** [comment]
Here's the CE example: <https://samme.github.io/phaser-examples-mirror/audio/fade%20in.html>.

**Comment by samme** [comment]
Volume changes (except 0) don't seem to work: <https://codepen.io/samme/pen/yvaXPO>

**Comment by jaryno** [comment]
Hi,
could you please explain what does "Disconnecting either gain node" mean?
How did you fix this problem?

Thank you!

**Comment by samme** [comment]
I don't quite remember, I have to look it up.

You can set [PhaserGlobal.disableWebAudio](https://photonstorm.github.io/phaser-ce/PhaserGlobal.html) to avoid this in Firefox.

**Comment by pavle-goloskokovic** [comment]
I've tested v3 example that fades sound in and out and fade out seems to work fine but fade in doesn't:
http://labs.phaser.io/view.html?src=src\audio\Web%20Audio\Basic%20Playback%20and%20Events.js

Also, I'm using Firefox 58.0.2. 
It's most definitely a bug with the browser, I suggest reporting it directly to Mozilla.

**Comment by samme** [comment]
This example (2 consecutive gain nodes) seems to work correctly in Firefox: <https://codepen.io/samme/pen/yvZydj>. So I'm not sure what the problem is. 🙁

**Comment by jaryno** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1447273

**Comment by samme** [comment]
Fixed in Firefox 60.
