### ISSUE TITLE
Wrong TS definition in GameObjectFactory for BitmapText

### ISSUE THREAD

**Issue by netdreamer** [photonstorm/phaser-ce#460]
This Issue is about 
* An error in the TypeScript definitions

BitmapText has size and ALIGN properties, but game.add.bitmaptext has size and GROUP

**Comment by netdreamer** [comment]
PR #461

**Comment by B10215029** [comment]
game.add.bitmapText has no ALIGN properties in GameObjectFactory.js

https://github.com/photonstorm/phaser-ce/blob/dc45d8279fd0c0e86577c1e7332d962765c65c55/src/gameobjects/GameObjectFactory.js#L459

GameObjectCreator.bitmapText is in L1594, not L1624

https://github.com/photonstorm/phaser-ce/blob/dc45d8279fd0c0e86577c1e7332d962765c65c55/typescript/phaser.d.ts#L1594

You should not directly modify line 1624 of the TS definition.
