### ISSUE TITLE
Group.forEach() is broken -- `TypeError: callback.apply is not a function`

### ISSUE THREAD

**Issue by ColeWunderlich** [photonstorm/phaser-ce#465]
* A bug in the API:
  * Phaser version(s): 2.10.0
  
When using `group.forEach()` to call one of my globally defined functions, I get the following error message:  `Uncaught TypeError: callback.apply is not a function at Phaser.Group.forEach (phaser.js:33325)`.   Seems like there is a problem with the framework.

This is running on Chrome Version 63.0.3239.132 with JavaScript 1.7

**Comment by photonstorm** [comment]
That error means it hasn't been given a valid function to call.

**Comment by ColeWunderlich** [comment]
Ah, gotcha.  I've been having trouble with figuring out what context to pass in.  Someone on the HTML5 forums recommended defining the function as part of the objects the group contains and that seems to have fixed the problem.

**Comment by samme** [comment]
This can happen if you mistakenly pass `undefined`.
