### ISSUE TITLE
Video "NS_ERROR_NOT_AVAILABLE" firefox android

### ISSUE THREAD

**Issue by hugof** [photonstorm/phaser-ce#466]
* A bug in the API: 
  * Phaser version(s): v 2.10.0 ( and previous version)
  * Live example: - https://phaser.io/examples/v2/video/play-video
                            - https://codepen.io/samme/pen/ddpvdx
  

Video (mp4 or webm) doesn't play on firefox android -> "NS_ERROR_NOT_AVAILABLE"
I use CANVAS mode and I unlock videos before.

`game.input.onTap.add(function(){
	var video = game.add.video('video');
	video.unlock();
        //video.play();
	video.addToWorld();
}, this);`

<img width="867" alt="capture d ecran 2018-02-06 a 17 56 08" src="https://user-images.githubusercontent.com/1511918/35974781-b4d035b0-0cda-11e8-9c81-f34245d416b9.png">

http://www.html5gamedevs.com/topic/35478-video-doesnt-work-on-firefox-android/

**Comment by samme** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=1413222>?

**Comment by samme** [comment]
@hugof could you check <https://developer.mozilla.org/samples/video/chroma-key/index.xhtml> in Firefox Android?

**Comment by suminda-its** [comment]
i'm having the same issue , any one found a solution for this one ?

**Comment by samme** [comment]
Is it still a problem?
