### ISSUE TITLE
loadUpdate is called once when no assets are loaded

### ISSUE THREAD

**Issue by omretterry** [photonstorm/phaser-ce#468]
* An error in the documentation
  * Phaser version(s): v2.9.3

![image](https://user-images.githubusercontent.com/32243578/36058273-ab903ba8-0e56-11e8-9af4-4e0c94d71717.png)
 I log in state for testing state life cycle methods.The document says loadUpdate will call when there is some assets load in preload method. [doc](https://photonstorm.github.io/phaser-ce/Phaser.State.html#loadUpdate)
It calls without assets load in preload.

I thought loadRender will always after loadUpdate. But when i add an asset in preload method it always more once loadUpdate before create method.

**Comment by samme** [comment]
<https://codepen.io/samme/pen/RQVwgK>

Happens via Phaser.StateManager#loadComplete

**Comment by samme** [comment]
@photonstorm do you remember what the "extra" loadUpdate call is for?

<https://github.com/photonstorm/phaser-ce/blob/e08c3119be1db8deb99cda9b4d909578d777852e/src/core/StateManager.js#L601-L605>

**Comment by samme** [comment]
<https://github.com/photonstorm/phaser-ce/commit/1c65c48341d67d490a76fdda21ad2f1c96425125>

I think because Loader#reset is now called earlier, the last loadUpdate call actually receives Loader#progress 0 instead of 100. So maybe I'll just remove it.
