### ISSUE TITLE
Keypress + dead keys not working on Firefox / Linux

### ISSUE THREAD

**Issue by rodri042** [photonstorm/phaser-ce#470]
This Issue is about
* A bug in the API:
  * Phaser version(s): 2.8.1
  * Live example: https://codepen.io/anon/pen/aqWVXO
  * What should happen: Typing the accent key and then "a" should log "á"
  * What happens instead: It logs "a" on Firefox / Linux. On Chrome it logs "á" correctly.

I'm not sure if this is a firefox bug or Phaser's. Can you please verify?
Thanks!

**Comment by samme** [comment]
Try <https://w3c.github.io/uievents/tools/key-event-viewer.html>.

The first argument passed to the keypress callback is `String.fromCharCode(event.charCode)`. So if the browsers report different `charCode` values, then Phaser's behavior would be expected.

<https://codepen.io/samme/pen/ZrKRWK>

**Comment by rodri042** [comment]
It seems it doesn't seems to trigger any `keypress` at all on firefox:
![screenshot77](https://user-images.githubusercontent.com/1631752/36084246-1b78ed2a-0fc4-11e8-899a-614f17d3f01b.png)

...in Chrome:
![screenshot76](https://user-images.githubusercontent.com/1631752/36084251-242f3280-0fc4-11e8-98dd-0bd4303562b5.png)

However, I think it would be great if phaser abstract the user from these browser inconsistencies.
Is there any chances to implement support for `compositionend` events?

**Comment by samme** [comment]
> What should happen: Typing the accent key and then "a" should log "á"

I can't really tell what the correct [event properties](https://developer.mozilla.org/en-US/docs/Web/Events/keypress) should be for this case.

I doubt Phaser will provide a `composition*` interface (it seems more suited for typing than game input), but you could certainly try to use the DOM events directly.
