### ISSUE TITLE
Throws error on sprite drag events, on android devices

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser-ce#473]
* What happens instead:
here is error log, i've more than 140k errors like this, everything is working fine, on desktop and iphone, on some androids too.
```
 this.game.input.maxPointers = 1
    if (this.game.device.touch) {
      this.game.input.mouse.stop()
    }
```
this helped me to fix this kind of errors in 90%, but i still having them, i think the problem is in support for android 6+ versions
2.1.2, os_version:android 7.0, manufacturer:unknown, device:unknown, browser_version:chrome 4, platform:android, session_id:0a39ee37-2cac-40c0-9213-e27352d0b6dc, session_num:1, connection_type:wwan, build:1.0.0-beta.7, category:error, severity:critical, message:r.InputHandler.startDrag()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:259:12885\nr.InputHandler._touchedHandler()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:259:7741\nr.Pointer.start()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:249:4250\nr.Input.startPointer()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:228:4957\nr.MSPointer.onPointerDown()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:238:2082\nHTMLCanvasElement._onMSPointerDown()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:238:560}

**Comment by samme** [comment]
What's the error message?

**Comment by RollinSafary** [comment]
i see this error only on game analytics, here is error message registered in it
`2.1.2, os_version:android 7.0, manufacturer:unknown, device:unknown, browser_version:chrome 4, platform:android, session_id:0a39ee37-2cac-40c0-9213-e27352d0b6dc, session_num:1, connection_type:wwan, build:1.0.0-beta.7, category:error, severity:critical, message:r.InputHandler.startDrag()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:259:12885\nr.InputHandler._touchedHandler()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:259:7741\nr.Pointer.start()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:249:4250\nr.Input.startPointer()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:228:4957\nr.MSPointer.onPointerDown()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:238:2082\nHTMLCanvasElement._onMSPointerDown()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1855556464486312/vendor.d09e4d8f502b892df198.js:238:560}`

and another one

`r.Input.startPointer()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1709445795786062/vendor.45741f19ba18d6474136.js:228:4937
r.MSPointer.onPointerDown()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1709445795786062/vendor.45741f19ba18d6474136.js:238:2082
HTMLCanvasElement._onMSPointerDown()@https://apps-907610622712303.apps.fbsbx.com/instant-bundle/1761454840544880/1709445795786062/vendor.45741f19ba18d6474136.js:238:560`
