### ISSUE TITLE
Null pointer exception when updating P2 body shapes while narrowphase check is running

### ISSUE THREAD

**Issue by flowbytes** [photonstorm/phaser-ce#477]
This Issue is about 

* A bug in the API:
  * Phaser version(s): 2.10.0
  * Live example: tbd
  * What should happen: no crash
  * What happens instead: game crashes

This one is a bit tricky that's why I can't supply a live example yet, but I think I understand whats happening an I'm offering a solution (in case you confirm it as bug and not as my own problem ^^).

What I'am doing:

I'm using Phaser with P2 physics and I'm writing my own network code to make a multiplayer game. In this configuration it can sometimes happen that a P2 body changes it shape and this is broadcasted via the network (e.g. a spaceship looses a part of itself).

What is the issue:

When a P2 body changes it shapes the collision group will be updated. If this happens exactly during a collision check with that shape the shape will be null and the narrowphase collision check throws a nullpointer exception.

Is it a bug or an issue with my code:

I've tried to come up with a solution to check somehow if the narrowphase collision is running to delay the shape update but failed. 
A straight forward fix is to make a shape check before evaluating the collision, e.g.:

line 13008 in p2.js (World.prototype.internalStep, narrowphase check):
```
// Loop over all shapes of body i
        for(var k=0, Nshapesi=bi.shapes.length; k!==Nshapesi; k++){
            var si = bi.shapes[k];
	    if (!si){
		continue;
	    }
            var xi = si.position,
	         ai = si.angle;
```

Possible additional issues:

I'm not sure if the data of the shape can still become null after the check.

Looking forward to hear your opinion on this issue :-)

**Comment by samme** [comment]
How and when are you modifying the P2 body (or collision group)?

**Comment by flowbytes** [comment]
How: the user can switch on/off certain parts of the player sprite. If he does so I need to refresh the collision groups.

When: completely random due to user input

**Comment by flowbytes** [comment]
The error is a null-pointer exception at `si.position` since `si = bi.shapes[k]` is undefined. To give you the exact error message I'd have to revert back to the "original" phaser library because since my suggested changes the error does not happen anymore (actually there are 2 more positions in p2 where the same thing is happening).
I'm calling `removeShape`  and then `setCollisionGroup` on a sprite in a function triggered by a network listener. I agree that if everything was strictly single-threaded this should be executed after the loop inside P2 is complete ... I can't explain why it is still happening, but it must, how else could shapes[k] ever be undefined?

**Comment by flowbytes** [comment]
I'm wondering if this threading issue is coming from WebRTC (that's my network connection), it might well be that this uses a worker thread ...

**Comment by samme** [comment]
I don't know P2 Physics at all I'm afraid. 🙁

Have you turned off all the collision checks and confirmed that `removeShape` alone is working correctly?

@samid737 do you have any ideas?

**Comment by samid737** [comment]
Hmm can't exactly tell what is going on. What about setting A flag when listening to make sure addShape is called inside Phaser? Something like: 

```
function changeShape(){ //via network
 allowed = true;
}

function update(){
if(allowed){
 addShape();
}
}
```

**Comment by flowbytes** [comment]
That might work, yes. In my case it would require to queue all shape changes (push to some array maybe) and then execute them at the end of 'update' which makes everything a bit more complicated but I guess it's worth a try :-)
