### ISSUE TITLE
tilemap problems

### ISSUE THREAD

**Issue by jamesjsewell** [photonstorm/phaser-ce#483]
* A problem with my own code ( i think )

when I switch out tilemaps / tilelayers, they update visually, but not if i begin to move tiles around.
basically i am trying to switch out tilemaps or tilemap layers for different levels of the game. 
It's just not working as expected, I will be happy to give more detail if needed

also the shuffle method on the tilemap isn't working properly, it swaps the tiles around visually but doesn't retain their properties

**Comment by jamesjsewell** [comment]
I have been destroying/creating new layers. Maybe I should create all of the layers, and switch between them by changing opacity/bring to front, something like that?

**Comment by jamesjsewell** [comment]
a layer seems to only work as long as it is first in the array of layers

**Comment by jamesjsewell** [comment]
update: i got everything working except for shuffle, described here by someone with the same question, they never got an answer http://www.html5gamedevs.com/topic/12946-tilemap-shuffle/

**Comment by samme** [comment]
I think you should be able to switch TilemapLayers on and off with [exists](https://photonstorm.github.io/phaser-ce/Phaser.TilemapLayer.html#exists).

**Comment by jamesjsewell** [comment]
@samme thanks if i run into any more problems I will try exists, i've got everything working now though
