### ISSUE TITLE
shuffle method doesn't preserve unique properties

### ISSUE THREAD

**Issue by jamesjsewell** [photonstorm/phaser-ce#484]
* A bug in the API: maybe

the issue is described here by someone, they never got an answer 
http://www.html5gamedevs.com/topic/12946-tilemap-shuffle/

"I'm having trouble using Phaser's TileMap.shuffle. When I use it, it shuffles the area of tiles like it should, but the tiles lose their unique properties after being shuffled. Is there some way I can shuffle tiles without losing collision properties? I'm using shuffle like this:

 

myTileMap.setCollision(tileID, true, layer);         // set a few collisions

myTileMap.setTileIndexCallback(tileID, function (player, tile) {     // I have two callbacks
                // do stuff

                myTileMap.shuffle(tile.x, tile.y, 5, 5, layer);            // call shuffle
            }, game, walls);

 

When the callback runs, the 5x5 area on the map loses its specific tile properties. Inside the callback, I can re-set the collision tiles, but I can't rewrite the callback I am in. Is there another way I should be going about achieving this? Thank you."

**Comment by samme** [comment]
Try [Tilemap#setPreventRecalculate](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#setPreventRecalculate).

**Comment by jamesjsewell** [comment]
I will try that soon and let you know. Thanks for responding, btw the name samme is familiar, i guess you're pretty active in the phaser community?  @samme

**Comment by jamesjsewell** [comment]
this.theTileMap.setPreventRecalculate(true)
this.theTileMap.shuffle(1, 1, 4, 4, this.currentLayerIndex)
this.theTileMap.setPreventRecalculate(false)

i tried this and it isn't quite working

**Comment by jamesjsewell** [comment]
I tried setting it to true, then shuffle, then set it to false, and the opposite and neither worked

**Comment by samme** [comment]
I tried something similar on <https://samme.github.io/phaser-examples-mirror/tilemaps/shuffle%20tiles.html>:

```javascript
layer.debug = true
map.setCollisionByExclusion([30], true)
```

Then I clicked on the map to shuffle the tiles. The collision faces didn't change. I didn't use the `recalculate` argument or the `setPreventRecalculate` method.

Re. the original post: I haven't tried to reproduce that, but it's possible that calling shuffle **inside** a tile callback might give unexpected results.

**Comment by jamesjsewell** [comment]
@samme im not sure i understand

**Comment by samme** [comment]
Maybe I misunderstood.

In <https://codepen.io/samme/pen/vdzjXy?editors=0010>, after you shuffle tiles, do you want to the collision lines (green) to change or stay the same?

**Comment by jamesjsewell** [comment]
@samme i'll elaborate, I'm using the same shuffle method and arguments. What i'm doing is in tiled, i have set properties on the tiles. like lets say one tile is a goal for the player to reach, before the game starts i can iterate through the tiles and store the tile that has a property of "tile_type: 'goal'" as a variable to reference during the game. when i use the shuffle method, VISUALLY the "goal" tile is in a different location, but, the tile that has that property is still in the original location of the goal tile before the shuffle.

**Comment by jamesjsewell** [comment]
that's an example to illustrate what is happening

**Comment by jamesjsewell** [comment]
https://jamesjsewell.github.io/sifter/ this is the game i'm making, i am trying to shuffle the inner 4 x 4 tiles. I start in tiled by creating a puzzle that is possible, and then have the app shuffle the puzzle for the user to solve

**Comment by samme** [comment]
OK. It looks like [shuffle modifies tile indexes only](https://github.com/photonstorm/phaser-ce/blob/v2.10.1/src/tilemap/Tilemap.js#L1881), it doesn't actually move the tiles around, so that's why the tile data doesn't change as well.

[swap](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#swap) works the same way.

You could try [putTile](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#putTile) and [removeTile](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#removeTile). Unfortunately you have to handle the shuffle part yourself.

**Comment by jamesjsewell** [comment]
@samme interesting, i suppose i could write a function to do that myself, maybe I could make pr? I've never actually made pull request to a project like this though

**Comment by samme** [comment]
If it works, you can make a PR. :)

It seems most of the tile mutators modify `index` only:

- [fill](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#fill)
- [random](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#random)
- [replace](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#replace)
- [shuffle](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#shuffle)
- [swap](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#swap)

[putFile](https://photonstorm.github.io/phaser-ce/Phaser.Tilemap.html#putTile) uses [Tile#copy](https://photonstorm.github.io/phaser-ce/Phaser.Tile.html#copy) so it modifies all the data as well.

**Comment by samme** [comment]
Clarified the expected behavior in the Tilemap docs.

You can still add a new feature if you like.
