### ISSUE TITLE
[BUG] Cannot pass arguments to my own plugin by using of game.add.plugin() API.

### ISSUE THREAD

**Issue by koalaylj** [photonstorm/phaser-ce#486]
* A bug in the API: game.add.plugin();
  * Phaser version(s): Phaser CE v2.10.1
  * What should happen: we could pass args to my own plugin.
  * What happens instead: we cannot pass args to my own plugin.

Code In My Game Logic(this will invoke GameObjectFactory.plugin)
```javascript
game.add.plugin(PhaserSpine.SpinePlugin, CustomConfig);
```

Code In GameObjectFactory(this will invoke PluginManager.add)
```javascript
plugin: function (plugin) {
    return this.game.plugins.add(plugin);
}
```
We miss the `CustomConfig`  at GameObjectFactory.plugin API.

Code In PluginManager
```javascript
add: function (plugin) {
  //can not get args,we missed it at GameObjectFactory.plugin
  var args = Array.prototype.slice.call(arguments, 1);
   if (typeof plugin['init'] === 'function')
   {
      plugin.init.apply(plugin, args);
   }
}
```

I think `GameObjectFactory.plugin` API should like this
```javascript
plugin: function (plugin, options) {
    return this.game.plugins.add(plugin, options);
}
```

**Comment by samme** [comment]
For now you can use [game.plugins.add](https://photonstorm.github.io/phaser-ce/Phaser.PluginManager.html#add) instead:

```javascript
game.plugins.add(PhaserSpine.SpinePlugin, CustomConfig);
```

I will work.
