### ISSUE TITLE
Docs don't know about width or height properties

### ISSUE THREAD

**Issue by Siri0n** [photonstorm/phaser-ce#488]
* An error in the documentation

https://photonstorm.github.io/phaser-ce/Phaser.Image.html

`height` and `width` aren't listed anywhere on that page, but they apparently remain in the source code.

https://github.com/photonstorm/phaser-ce/blob/v2.10.1/src/pixi/display/Sprite.js#L140

**Comment by samme** [comment]
PIXI.DisplayObjectContainer properties need to be renamed.
