### ISSUE TITLE
wrong result when using tween on "width" and calling "getBounds" in "update" loop

### ISSUE THREAD

**Issue by Aram19** [photonstorm/phaser-ce#489]
A bug in the API:

I have following incorrect working code.

create () {
   this.g = this.game.add.graphics();
   this.g.lineStyle(2,0xff0000, 1);
   this.g.drawRect(50,50,150,150);
   const tw = this.game.add.tween(this.g);
   this.g.width = 1;
   tw.to({width:150}, 1000);
   tw.start();
},
update(){
   this.g.getBounds();
}

After tween ends, I have wrong  "width", "scale.x", also "position.x" values. I found problem in the following. (Situation is presented in common and with not real values).

RAF  first loop
1)
Stage.Update -> g.getBounds() -> g._currentBounds.width = 1;
2)
Tweens.Update -> g.width = 2 -> g.scale.x = (2/g._currentBound.width) = 2
3) 
postUpdate -> g.updateTransform() -> g.worldTransform.a = g.scale.x = 2.

RAF next loop
1)
Stage.Update -> g.getBounds() -> g._currentBounds.width = (worldTransform.a * width) = 2*150 =300
2)
Tweens.Update -> g.width = 3 -> g.scale.x = 3/300 = 0.01
3) 
postUpdate -> g.updateTransform() -> g.worldTransform.a = g.scale.x = 0.01.

RAF next loop
1)
Stage.Update -> g.getBounds() -> g._currentBounds.width = (worldTransform.a * width) = 0.01 * 150 = 1.5
2)
Tweens.Update -> g.width = 4 -> g.scale.x = 4/1.5 = 2.66
3) 
postUpdate -> g.updateTransform()-> g.worldTransform.a = g.scale.x = 2.66.

**Comment by samme** [comment]
I think this is the correct result: <https://codepen.io/samme/pen/paMEeG?editors=0010>.

    width === bounds.width * scale.x
    
    height === bounds.height * scale.y

> #### getBounds()
>
> Retrieves the bounds of the graphic shape as a rectangle object

**Comment by Aram19** [comment]
@samme No. It is wrong. Try without "render" and you will see.

**Comment by samme** [comment]
Tween the scale instead: <https://codepen.io/samme/pen/BYXrXd?editors=0010>

**Comment by Aram19** [comment]
@samme Thank you. I have solution. I solved it. Here I reported bug ("width" calculated based on "scale" and after it "scale" is calculated based on "width") to be fixed.

**Comment by samme** [comment]
I see it now, thanks.
