### ISSUE TITLE
PIXI.Rectangle definition doesn't match Phaser.Rectangle

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#491]
At run-time, PIXI.Rectangle is identical to Phaser.Rectangle, but the TypeScript definitions are distinct. PIXI.Rectangle lacks most of Phaser.Rectangle's properties.

This Issue is about

* An error in the TypeScript definitions

**Comment by samme** [comment]
E.g., Phaser.Sprite#getBounds() → PIXI.Rectangle

**Comment by rpatwariingenuity** [comment]
bhs
