### ISSUE TITLE
Phaser CE does not work with latest CocoonJS

### ISSUE THREAD

**Issue by KIVassilev** [photonstorm/phaser-ce#492]
This Issue is about (pick one, ✏️ delete others)

* A bug in the API:
  * Phaser version(s): v2.10.1
  * Live example: N/A
  * What should happen: Should work in CocoonJS developer app
  * What happens instead: It stops with JS error

With the latest CocoonJS update (https://blog.cocoon.io/cocoon-2-2-0-v8-update-is-here/) phaser games stopped working in CocoonJS developer app.

The issue is here:

    if (this.game.device.cocoonJSApp)
    {
        CocoonJS.App.onSuspended.addEventListener(function () {
            Phaser.Stage.prototype.visibilityChange.call(_this, { type: "pause" });
        });

        CocoonJS.App.onActivated.addEventListener(function () {
            Phaser.Stage.prototype.visibilityChange.call(_this, { type: "resume" });
        });
    }

**CocoonJS.App.onSuspended** seems to be removed from CocoonJS interface

I can try to submit an MR if are ok with that

Thanks in advance :)

**Comment by samme** [comment]
<https://cocoonio.github.io/cocoon-canvasplus/dist/doc/js/Cocoon.App.html#toc16>
