### ISSUE TITLE
OnInputUp triggered twice on android

### ISSUE THREAD

**Issue by Jazcash** [photonstorm/phaser-ce#494]
* A bug in the API:
  * Phaser version(s): 2.10.1
  * Device: Google Pixel 2
  * Android version: 8.1.0
  * Chrome version: 65
  * Live example: https://codepen.io/jazcash/pen/pLjYLX?editors=0010
  * What should happen: Square should become half opacity on first click, then disappear completely on second
  * What happens instead: Square disappears completely on first click

**Comment by samme** [comment]
See #32
