### ISSUE TITLE
Signal#memorized doesn't work when there're no listeners

### ISSUE THREAD

**Issue by Siri0n** [photonstorm/phaser-ce#495]
* A bug in the API:
  * Phaser version(s): 2.10.1
  * Example:
```javascript
var foo = new Phaser.Signal();
foo.memorize = true;
foo.dispatch("bar"); // nothing
foo.add(x => console.log(x));
foo.dispatch("baz");
```
  * What should happen:
"bar" should be printed in the console.
  * What happens instead:
It's not.

https://github.com/photonstorm/phaser-ce/blob/dc45d8279fd0c0e86577c1e7332d962765c65c55/src/core/Signal.js#L411
Here's the source of error (if it isn't desired behaviour, of course). If there's no binding, _prevParams doesn't update.

**Comment by samme** [comment]
Console should print "bar" and "baz" only after `foo.dispatch("baz")`, correct?

Re. <https://photonstorm.github.io/phaser-ce/Phaser.Signal.html#memorize>

**Comment by Siri0n** [comment]
"bar" should be printed on line 4, after foo.add. According to specs, when you add callback, memorised event will be dispatched for it immediately. Compare:
```javascript
var foo = new Phaser.Signal();
foo.memorize = true;
foo.add(() => {}); //here's the trick
foo.dispatch("bar"); 
foo.add(x => console.log(x)); // and we instantly have "bar" printed
foo.dispatch("baz");
```

**Comment by samme** [comment]
OK, so this is the desired behavior:

```javascript
var foo = new Phaser.Signal();
foo.memorize = true;
foo.dispatch("bar");
// (none)
foo.add(x => console.log(x));
// -> 'bar'
foo.dispatch("baz");
// -> 'baz'
```

**Comment by Siri0n** [comment]
Yes, I think so.
