### ISSUE TITLE
120hz monitors makes phaser run strange.

### ISSUE THREAD

**Issue by vantreeseba** [photonstorm/phaser-ce#496]
* A bug in the API:
  * Phaser version(s): Phaser-ce
  * Live example:
  * What should happen: It should cap at 60fps (or whatever desired FPS is)
  * What happens instead: It doesn't. It runs in kind of "slow motion".

**Comment by samme** [comment]
What happens **exactly**, though? ;)

**Comment by vantreeseba** [comment]
Here is a video of the effect, it happens around 1:30/1:40.

The slowdown is when the framerate jumps from 60 to 120

**Comment by samme** [comment]
Can you look at <https://codepen.io/samme/pen/jzrVNP/> on the 120hz monitor? (Click to focus the game.)

Try changing the `forceSingleRender` and `forceSingleUpdate` settings in the GUI panel.

**Comment by goldfire** [comment]
@samme We don't actually have a monitor to test this on, but we just had the player seeing this issue test that codepen. Here are the results he sent us:

![screenshot_1](https://user-images.githubusercontent.com/882005/37482034-42394842-2851-11e8-9975-c3eea57e62bb.jpg)
![screenshot_3](https://user-images.githubusercontent.com/882005/37482036-43d9f41c-2851-11e8-996c-f9eb43a09622.jpg)
![screenshot_4](https://user-images.githubusercontent.com/882005/37482039-4552d796-2851-11e8-8431-d30031a56733.jpg)
![screenshot_5](https://user-images.githubusercontent.com/882005/37482043-47ddbcb0-2851-11e8-99e2-42ee18eb3ba1.jpg)

**Comment by goldfire** [comment]
To add on to this, we disabled forcing both update and render and the player test again. It seemed to make everything run smooth (as you can see in the new video below), but everything seems to be moving in slow motion.

https://streamable.com/163u2

**Comment by samme** [comment]
Try just `forceSingleRender=false`? Assuming you're using the latest CE.

**Comment by goldfire** [comment]
@samme We just tried that with the same result as in the video above, and yes we are using the latest CE version.

**Comment by samme** [comment]
Hm, I didn't expect that. `forceSingleRender` shouldn't directly affect the logic update rate like `forceSingleUpdate` does.

**Comment by vantreeseba** [comment]
Looks like the user did not have a 144hz monitor, but instead had v-sync turned off, which could cause it to run faster than 60fps.  This still shouldn't be an issue but it is "fixed" by asking them to turn on vsync so the GPU runs at 60fps/hz.

**Comment by samme** [comment]
This should be fixed in https://github.com/photonstorm/phaser-ce/releases/tag/v2.17.0
