### ISSUE TITLE
Which files do we need on cdnjs

### ISSUE THREAD

**Issue by kennynaoh** [photonstorm/phaser-ce#5]
Hello @photonstorm , I am the member of cdnjs project. We want to host this library. I think the main file are under `build/`. Could help me mention the files we need? Thanks for your help.

https://github.com/cdnjs/cdnjs/issues/10227

**Comment by photonstorm** [comment]
Hi - yes, the only files you need are in the `build` folder - and you don't even need _all_ of those (just `phaser.js` and `phaser.min.js` would do).

**Comment by kennynaoh** [comment]
@photonstorm what about the `phaser.map`?

**Comment by photonstorm** [comment]
If you can include it then go for it, but it's not as essential.

**Comment by kennynaoh** [comment]
Thanks @photonstorm
