### ISSUE TITLE
Should the Weapon plugin be calling updateTransform for its trackedSprite?

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser-ce#50]
* A -potential- bug in the API -  Phaser-CE 2.7.3
* A problem with my own code

Hello! I had a question about this line - https://github.com/photonstorm/phaser-ce/blob/master/src/plugins/weapon/WeaponPlugin.js#L636 - why is the weapon calling updateTransform? Won't this incur an additional drawCall/WebGL update? I don't really know how that function works, but it looks out of place in the Weapon Plugin's update function.

**Comment by samme** [comment]
Believe that's to ensure the tracked position is accurate even before the next update. It doesn't do any rendering.

**Comment by JTronLabs** [comment]
Cool thanks!
