### ISSUE TITLE
Loading tileset from atlas

### ISSUE THREAD

**Issue by HaoboZ** [photonstorm/phaser-ce#500]
This Issue is about
A problem with my own code

I'm not too sure how to load a tileset image from an atlas. If you load an atlas, it generates a key for the whole atlas, and all the separate parts are frames. However, the API for Tilemap.addTilesetImage does not include a frame option, which makes it so it can't load from there. Is there an easy way to use it, or otherwise it will just be separately loaded?

**Comment by samme** [comment]
It could be that's not supported. Probably Phaser assumes the tileset is a complete texture with offsets from (0, 0).

You can try copying the the frame to a BitmapData and using that: <https://samme.github.io/phaser-examples-mirror/tilemaps/tileset%20from%20bitmapdata.html>

**Comment by HaoboZ** [comment]
Oh, thanks, didn't see that key could also take a BitmapData as input instead of just a string.
