### ISSUE TITLE
Point.parse rounds to integer

### ISSUE THREAD

**Issue by Siri0n** [photonstorm/phaser-ce#502]
```javascript
var o = {x: 0.5, y: 1.5};
var p = Phaser.Point.parse(o);
console.log(p.x, p.y); //0 1
```

IDK maybe it's intended behaviour. If it is, I think it should be reflected in docs.

**Comment by HaoboZ** [comment]
Intended behavior in source code since it uses parseInt instead of parseFloat.

**Comment by samme** [comment]
That is a little odd.

You can use the copyFrom methods (which don't round) if you need copying only.
