### ISSUE TITLE
ERROR RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by LuisBonsembiante** [photonstorm/phaser-ce#504]
Hi guys ...please help me, I have this error in mobile devices... not in PC browsers... this problem appeared last Friday... I dont know what is the problem.... any idea?.
Regards.

  * Phaser version(s):2.10.2
  * Live example:
  * What should happen: Run the game and canvas.
  * What happens instead:
ccore.js:1448 ERROR RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at new Phaser.BitmapData (scripts.bundle.js:50480)
    at Phaser.Utils.Debug.boot (scripts.bundle.js:83824)
    at Start.boot (scripts.bundle.js:35784)
    at Phaser.Device._readyCheck (scripts.bundle.js:63043)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4736)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)

**Comment by samme** [comment]
What are the game dimensions and resolution?

I would just try to avoid this with [enableDebug: false](https://photonstorm.github.io/phaser-ce/global.html#GameConfig).

**Comment by LuisBonsembiante** [comment]
The problem is the scale...when we try to do:
 const w = (100 * window.devicePixelRatio).toString();
 const h = (100 * window.devicePixelRatio).toString();
 super(w,h, Phaser.AUTO, element, null, true, true);
The mobile device dont support that, but I dont know the solution

**Comment by LuisBonsembiante** [comment]
Ok you solution  enableDebug: false. is working...by why?.... is a correct solution?

**Comment by samme** [comment]
With [enableDebug: false](https://photonstorm.github.io/phaser-ce/global.html#GameConfig) no debug canvas is created.

Probably the game canvas is too large (in memory) for some of those devices. Check the actual game dimensions in `game.width`, `game.height`.

**Comment by LuisBonsembiante** [comment]
Hi @samme  yes is 300% percent but work with enableDebug: false .. I scale the components
