### ISSUE TITLE
Arcade Physics, circle body collide with moving satellite

### ISSUE THREAD

**Issue by xquangdang** [photonstorm/phaser-ce#505]
This Issue is about (pick one, ✏️ delete others)
I have a planet with circle body. When satellite collide with the planet body, I will add the satellite to the planet's satelliteGroup. I all so rotate the planet so the satellite will also move around the planet. I calculate the offset and angle when addChild to planet. The problem is that with different velocity, the satellite position is not correct.
* A bug in the API: 
  * Phaser version(s): CE 2.10.2

Velocity: 500
![29003754_1704604416263782_675977324_n](https://user-images.githubusercontent.com/11795757/37639202-0ce0cc42-2c43-11e8-93c8-5233fcc739e2.png)
Velocity: 800
![29019838_1704604812930409_1841500369_n](https://user-images.githubusercontent.com/11795757/37639217-1a6e0104-2c43-11e8-9789-039af3532d3b.png)

**Comment by samme** [comment]
I don't think you'll be able to use both `addChild` and `velocity` and get the result you want.

**Comment by xquangdang** [comment]
How should I update logic in `arcade.collide` callback?
I get what I want by using setTimeout() inside the callback. But I feel it not the right way to do
