### ISSUE TITLE
Mac OSX 10.13 Safari 11 Text issue

### ISSUE THREAD

**Issue by creole** [photonstorm/phaser-ce#508]
This Issue is about (pick one, ✏️ delete others)

* A bug in the API:
  * Phaser version(s): 2.10.2
  * Live example: https://codepen.io/creole/pen/vRZgOZ
  * What should happen: text displays fine in Chrome, Firefox and Opera (tested on both Windows 10 and Mac OSX 10.13), Edge (tested on Windows 10), and Safari 11 on iOS 11.2.6
  * What happens instead: in Safari 11 on Mac OSX 10.13 the text doesn't render, and the background color isn't set. If, in the constructor, I change `Phaser.AUTO` to `Phaser.CANVAS` the background color is set, but the background of the text becomes opaque, and I haven't found a way to make it transparent again.

**Comment by samme** [comment]
> in Safari 11 on Mac OSX 10.13 the text doesn't render, and the background color isn't set.

Can you screenshot this? Is it just a black canvas then?

It looks correct in my Safari 11.0.3 (WEBGL and CANVAS): black text on white background.

**Comment by creole** [comment]
Yes, it's just a black canvas.

With Phaser.CANVAS it's a black square (since the text background is opaque) on a white background.

**Comment by creole** [comment]
@samme Are you on Mac OSX 10.12 or 10.13? On 10.12 (Sierra) I can now confirm it looks fine. On 10.13 (High Sierra) it's just a black canvas (Phaser.AUTO) or a black rectangle on a white canvas (Phaser.CANVAS).

**Comment by samme** [comment]
Mine is Safari 11.0.3 / MacOS 10.13.3

**Comment by creole** [comment]
Mine too. Exactly the same. Must be something wrong with my configuration then. You can close this if you like.

**Comment by samme** [comment]
You might try 

```javascript
new Phaser.Game({
  renderer: Phaser.WEBGL,
  transparent: 'notMultiplied'
});
```

to see if it makes a difference.

**Comment by creole** [comment]
If I do that, the canvas changes color in Firefox, from white to a darkish brown: https://codepen.io/creole/pen/vRZgOZ

I haven't tested it in other browsers.
