### ISSUE TITLE
Animation onUpdate doesn't include the first frame

### ISSUE THREAD

**Issue by tomcatter** [photonstorm/phaser-ce#509]
hello guys. i meet one problem. when Animation play firstly , the count of frame  doesn't begin with first frame.

**Comment by samme** [comment]
Example?

**Comment by tomcatter** [comment]
`let commends = game.make.sprite(0, 0, animAsset);
 this.addChild(commends);
 let anim = commends.animations.add("commend");
anim.enableUpdate = true;
anim.onUpdate.add(function (sprite, animation) {
     console.log("frame", anim.frame);
}, this);
anim.play(25);
`
This is my code.

**Comment by samme** [comment]
I think this is how it's intended to work.

You can use [onStart](https://photonstorm.github.io/phaser-ce/Phaser.Animation.html#onStart) to capture the first frame.

Or you can do

```javascript
anim.play(25);
anim.frame = 0;
```

<https://samme.github.io/phaser-examples-mirror/animation/frame%20update.html>

**Comment by tomcatter** [comment]
I tried it this way, The same problem exists. The second time, the animation is normal.

**Comment by samme** [comment]
A workaround is to use `updateCurrentFrame(true)`.

<https://codepen.io/samme/pen/MVZKqW>
