### ISSUE TITLE
GRUNT Custom Build No Longer Excludes P2

### ISSUE THREAD

**Issue by B3L7** [photonstorm/phaser-ce#510]
A bug in Grunt Build:
  Phaser version(s): 2.10.1^
  What should happen: p2 should be excluded from custom builds
  What happens instead: p2 is always included in custom builds

Using the example: 
`grunt --exclude=p2,tilemaps,retrofont`

Outputs: 
```
---------------------
Building Phaser 2.10.3
---------------------
Excluding modules:

* ninja - Ninja Physics
* creature - Creature Animation Tool Support

Packaging Globals ...

-> P2.js
-> PIXI

Building ...

```

Tested with 10.0.1 and 10.0.3. Both fail to exclude correctly. 10.0.0 excludes as intended.

Thanks for all your hard work! It's greatly appreciated.

**Comment by samme** [comment]
It just worked correctly for me:

```
$ grunt custom --exclude=p2,tilemaps,retrofont
Running "custom" task
---------------------
Building Phaser 2.10.3
---------------------
Excluding modules:

* p2 - P2 Physics
* tilemaps - Tilemap Support
* retrofont - Retro Fonts Game Object
```

**Comment by B3L7** [comment]
It would help if I typed the right command. I left out custom...

Thanks!
