### ISSUE TITLE
Using skipFrames params in spritesheet not working

### ISSUE THREAD

**Issue by omretterry** [photonstorm/phaser-ce#514]
This Issue is about 
* A bug in the API:
  * Phaser version(s): 2.10.0
  * Live example: [Codepen](https://codepen.io/omretterry/pen/geXRVX?editors=1111)
  * What should happen: screen shows number: 4-17
  * What happens instead: screen shows number: 0-17

Api says skipFrams will skip frames.My understand is animations play will skip the head of frames.

**Comment by samme** [comment]
Agreed, I can't tell what `skipFrames` is trying to do. If it's positive and `maxFrames` is -1, there's no change; and if it's positive and `maxFrames` is positive, frames at the _end_ of the sheet are omitted.

If we change it, it should be in v2.11.0.
