### ISSUE TITLE
 chrome showing blending but not firefox 

### ISSUE THREAD

**Issue by jgarc448** [photonstorm/phaser-ce#515]
This Issue is about 
* A problem with my own code?

Hi,
I wanted to make a very simple game were objects gets destroyed as in worms o scorched. See example (http://jsbin.com/badime/1/edit?js,output)

I notice a simple write above a bitmapData works on chrome but no on firefox nor safari. When you press key 'A' you should see a circle in top left of the windows which only shown in Chrome
Example: (https://codepen.io/MrChef/pen/KooZmo)

First I tried Phaser forum but got no response (http://www.html5gamedevs.com/topic/36608-chrome-showing-blending-but-no-firefox/)) Assets in  forum were my own and then I added a codepen.

Versions used:
- Mac OSX 10.13.3 
- phaser: v2.10.3 "2018-03-22" - Built: Thu Mar 22 2018 10:06:51
- chrome: 65.0.3325.181 (64 bits)
- firefox: 59.0.2 (64 bits)
- safari: 11.0.3

Any idea about why this is happening?
Thank you

**Comment by samme** [comment]
Use `rgba(0, 0, 0, 1)` or `rgb(0, 0, 0)`.
