### ISSUE TITLE
.collide(...) doesn't work!

### ISSUE THREAD

**Issue by ShreerangV** [photonstorm/phaser-ce#516]
* A problem with my own code
- here is the code not working (the player class is just a sprite, mind you); the code displays properly but collision doesn't happen!
+var level1 = {
	
	map:{
	size:60,
	w:15,
	h:15,
	layout:[1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,
			1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,
			0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	},
	create: function(){
		game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
		game.physics.startSystem(Phaser.Physics.ARCADE);
		game.stage.backgroundColor = "#0ff";
		game.renderer.renderSession.roundPixels = true;
		this.background = game.add.tileSprite(0,0,game.world.width,game.world.height,'bg');
		this.background.scale.setTo(5,5);
		this.ost = game.add.audio('music');
		this.ost.loop = true;
		this.ost.play();
		this.tiles = game.add.group();
		this.tiles.enableBody = true;
		game.world.resize(this.map.size*this.map.w, this.map.size*this.map.h);
		for(var i = 0; i < this.map.layout.length; i++){
			if(this.map.layout[i]== 1){
				game.add.sprite((i%this.map.w)*this.map.size,Math.floor(i/this.map.h)*this.map.size,'tile');
			}
		}
		this.tiles.PhysicsBodyType = Phaser.Physics.ARCADE;
		this.tiles.setAll('checkCollision',true);
		this.tiles.setAll('body.immovable',true);
		this.tiles.setAll('width',this.map.size);
		this.tiles.setAll('height',this.map.size);
		console.log('ok');
		player.create();
		game.camera.follow(player.sprite);
	},
	update: function(){
		game.physics.arcade.collide(player.sprite,this.tiles,this.collideTiles,null,this);
		this.orientationChange();
		player.render();
		this.background.tilePosition.y += 0.25;
	},
	orientationChange: function(){
		game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
	},
	collideTiles: function(a,b){
		console.log('no');
	}
}

That's my level.
Why is collision not working?
Please do answer.

**Comment by samme** [comment]
You need to add each "tile" sprite to the tiles group.
