### ISSUE TITLE
issue about BitmapText/Sprite rendering

### ISSUE THREAD

**Issue by scott20145** [photonstorm/phaser-ce#518]
This Issue is about (pick one, ✏️ delete others)

* BitmapText/Sprite performance issue

**Phaser version**: 2.9.2

I created a BitmapText, placing at the center of the mobile screen. But when I updated the text content for example:
`BitmapText.text = "1500"` 
an unexpected  BitmapText '0' would show up at the top-left corner of the screen for about a blink and then disappeared - this issue also happened for images: after I changed the image's position, the image would show up at the top left corner first before displaying at the correct position. 

This usually happened for the first few times I changed the text/image when target is mobile, after several updates of text/image everything went back to normal. I'd greatly appreciate it if you could advise me on handling this issue. Please let me know if you need more specific info. Thank you very much.

**Comment by samme** [comment]
Try <https://samme.github.io/phaser-examples-mirror/text/bitmap%20fonts.html>?

**Comment by scott20145** [comment]
I'm not sure how to make it happen  exactly. In my game, I used dozens of pictures, but only few BitmapText/Sprite has this problem. A workaround solution is to call `object.updateTransform();` after you modify the object's position.
An example as bellow. This is an counting up effect, I had to call `updateTransform()` when a new char created.
```
 this.timer = window.setInterval(() => {
     let update = false;
     if (this.shouldStop || this.curPrize >= to || elapsed >= miliSec) {
         window.clearInterval(this.timer);
         this.text = to.toString();
         this.isRunning = false;
         resolve();
         return;
     }
     this.curPrize = Math.floor(to * elapsed / miliSec);
     if (this.text.length !== this.curPrize.toString().length) {
         update = true;
     }

      this.text = this.curPrize.toString();
     if (update) {
         this.updateTransform();
     }
     elapsed += TIME_TICK;
 }, TIME_TICK);
```

**Comment by samme** [comment]
Try it without `setInterval` etc.

You can use `game.time.events.loop(...)`.

**Comment by lynxaegon** [comment]
I'm having the exact same issue on Phaser 2.6.2.
If i render a new sprite at (150, 150)  for 1 frame the sprite is rendered at (0,0) and after that it's moved where it should be. 

The updateTransform after changing x,y / width,height worked, but i would like to find the issue and fix it so i wouldn't need to call updateTransform manually.

**Comment by samme** [comment]
@lynxaegon try to make an example: <https://codepen.io/pen?template=vyKJvw>

**Comment by lynxaegon** [comment]
@samme It's a bit complicated to create an example, because i'm not sure why it happens :)
I know that it got fixed when i added updateTransform in the function below.
```
PIXI.DisplayObjectContainer.prototype.addChildAt = function (child, index) {

    if (index >= 0 && index <= this.children.length)
    {
        if (child.parent)
        {
            child.parent.removeChild(child);
        }

        child.parent = this;

        this.children.splice(index, 0, child);

		this.updateTransform();

        return child;
    }
    else
    {
        throw new Error(child + 'addChildAt: The index '+ index +' supplied is out of bounds ' + this.children.length);
    }
};
```
Also, #299 is because of Physics bodies, and i'm not using any, but i'm using groups within groups which have children. Maybe it's almost the same thing, and sometimes the updateTransform is skipped on children. 

Will update if i find anything new or a better fix than this one.
