### ISSUE TITLE
animation gets stuck when an low fps causes a frame skip

### ISSUE THREAD

**Issue by mickeyren** [photonstorm/phaser-ce#524]
* A bug in the API:
  * Phaser version(s): 2.10.0

Not sure if this has been fixed but it seems it's still happening. It looks like it's the same issue as some time ago during Phaser 2 - https://github.com/photonstorm/phaser/issues/1628

For reference, the one boxed on this screenshot got stucked in it's animation:

![image](https://user-images.githubusercontent.com/175045/38713480-01b50e9a-3f04-11e8-8f5b-eaf5318a0064.png)

**Comment by samme** [comment]
Solution in <https://github.com/photonstorm/phaser/issues/1628#issuecomment-334590492>.
