### ISSUE TITLE
error in TypeScript definitions: arguments of instance method Phaser.InputHandler.start should be optional

### ISSUE THREAD

**Issue by bseiller** [photonstorm/phaser-ce#537]
An error in the TypeScript definitions:

phaser.comments.d.ts and phaser.d.ts define both parameters of the instance method Phaser.InputHandler.start as not optional.

Thanks for the great work!

**Comment by Weedshaker** [comment]
I assume you just do `start?: number` 
although, I am not sure if that is the right location. I don't have any phaser setup with typescript, but make the change, test it at your setup -> PR.
