### ISSUE TITLE
Phaser CE v2.9.3 game.input.onDown does not work on android device after capture screenshot by 3 fingers

### ISSUE THREAD

**Issue by itsay** [photonstorm/phaser-ce#541]
This Issue is about

* A bug in the API:
  * Phaser version(s): Phaser CE v2.9.3 | Pixi.js | Canvas | WebAudio
  * Live example: https://codepen.io/anon/pen/wjZXpv
  * What should happen: It should show text "tap" on screen when I tap on the screen after I capture screenshot by slide 3 fingers down.
  * What happens instead: application can receive onDown's event 
  * I`m using android device: Xiaomi Redmi 5 Plus, Browser: Chrome version 65.0.3325.109. It works in Firefox version 59.0.2
  
```
<head>
  <meta charset="UTF-8">
  <meta name=viewport content="width=device-width,initial-scale=1">
  <script type="text/javascript" src="https://github.com/photonstorm/phaser-ce/releases/download/v2.9.3/phaser.min.js"></script>
</head>
<body style="height: 100%;">
<div id="game" style="background-color: black; position: absolute; overflow: hidden; width: 360px; height: 640px;"></div>
<script type="text/javascript">
  var game, debug;
  game = new Phaser.Game(640, 1136, Phaser.CANVAS, 'game');
  playGame = new PlayGame(game);
  game.state.add("Play", playGame);
  game.state.start("Play");

  function Debug(_game) {
    const self = {
      label: _game.add.text(0, _game.camera.height - 30, "", {
        font: "18px Arial",
        fill: "#fff8fb",
        align: "center",
        stroke: '#4f1d0f',
        strokeThickness: 8
      }), text: ''
    };
    this.setText = function (text, append) {
      if (append) self.text += text;
      else self.text = text;
      self.label.setText(self.text);
      self.label.bringToTop();
    }
  }

  function PlayGame(_game) {
    var self = {game: _game};
    this.preload = function () {
      self.game.load.image('item', 'http://placekitten.com/g/300/300')
    };
    this.create = function () {
      self.game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
      self.game.scale.pageAlignHorizontally = true;
      self.game.time.advancedTiming = true;
      self.game.input.onDown.add(that.onTap, this); //handle touch
      game.onPause.add(that.onGamePause, this);
      self.game.add.button(0, 0, 'item', that.buttonClick, this);
      debug = new Debug(game);
    };
    this.onTap = function (pointer) {
      console.log('tap');
      debug.setText('tap', true);
    };
    this.onGamePause = function () {
      debug.setText('Pause')
    };
    this.buttonClick = function () {
      console.log('buttonClick');
      debug.setText('buttonClick', true);
    };
    const that = this;
  }
</script>
</body>
```

**Comment by samme** [comment]
Try [debug.pointer(...)](https://samme.github.io/phaser-examples-mirror/debug/debug%20input.html) to see if the game is getting any input at all.

**Comment by itsay** [comment]
I tested with latest Phaser CE: `https://github.com/photonstorm/phaser-ce/releases/download/v2.10.5/phaser.min.js
I added 

`this.render = function(){
      game.debug.pointer( game.input.activePointer );
    };`

After slide 3 fingers down, only the "Duration:" change the miliseconds. Can't tap, click.

**Comment by samme** [comment]
Try

```javascript
game.input.mspointer.capture = false;
```

The game isn't paused after the screenshot gesture, is it?

**Comment by itsay** [comment]
The game still running, it just not receive event tap/click.
After add line `game.input.mspointer.capture = false;`. It works for my demo. Will check it further. 
Thank you samme.

**Comment by itsay** [comment]
Add line `game.input.mspointer.capture = false;`. It works as expected for both version v2.9.3 and v2.10.5.
Thank you so much @samme

**Comment by itsay** [comment]
@samme 
It get another issue. After add line `game.input.mspointer.capture = false;` it receive double tap/click for single tap/click.

**Comment by itsay** [comment]
Instead of using game.input.mspointer.capture = false; I used method game.input.mspointer.stop(); as your suggest at [Issue 265](https://github.com/photonstorm/phaser-ce/issues/265)
