### ISSUE TITLE
sprite dragging don't work on Windows 10 IE11

### ISSUE THREAD

**Issue by Apelmon** [photonstorm/phaser-ce#542]
Hello.

I used phaser 2.6.2 in my project and made draggable button from sprite. Everything worked fine.

Then I updated phaser to version 2.10.5 (to fix issue with Chrome 66).
After that update I got a new issue when the sprite can’t drag on Windows 10 IE 11;

I found that I can drag sprite on Windows 10 IE 11 with phaser 2.8.5. The dragging doesn’t work with version newer than 2.8.5 on Windows 10 IE 11.

I tried to add this.game.input.mspointer.stop(); to the Boot.init();, but it didn't change anything.

Another issue that came after update to 2.10.5 - [#543].

Here is the example where you can check both problems: http://games.apelmongames.com/drag_test/

Thanks.

**Comment by samme** [comment]
Can you check <https://samme.github.io/phaser-examples-mirror/input/drag.html> in your IE 11?

**Comment by Apelmon** [comment]
It works well on Windows 10 IE11.

**Comment by samme** [comment]
I'm not sure of the problem, then. 🙁 

Try adding [debug.spriteInputInfo](https://samme.github.io/phaser-examples-mirror/debug/debug%20input.html) for the dragged sprite in your game.
