### ISSUE TITLE
The property `area` is missing in `Phaser.Particles.Arcade.Emitter` definition

### ISSUE THREAD

**Issue by qdrj** [photonstorm/phaser-ce#544]
This Issue is about
* An error in the TypeScript definitions

The property `area` is missing in `Phaser.Particles.Arcade.Emitter` definition

https://github.com/photonstorm/phaser-ce/blob/master/src/particles/arcade/Emitter.js#L58

**Comment by samme** [comment]
Isn't this it? <https://github.com/photonstorm/phaser-ce/blob/34b78365863ff511ad037fc2ece29b366fc1b54d/typescript/phaser.d.ts#L2942>

**Comment by samme** [comment]
Fixed in ad6ed29. Will be in the next release.
