### ISSUE TITLE
Game.Scale (SHOW_ALL) not working porpely

### ISSUE THREAD

**Issue by cpusam** [photonstorm/phaser-ce#547]
* A bug in the API:
  Phaser CE Typescript

  * Phaser version(s):
  2.10.5

  *Live Example:
//just add this lines to any phaser TS example:
  game.scale.scaleMode = Phaser.ScaleManager.SHOW_ALL;
  game.scale.pageAlignHorizontally = true;
  game.scale.pageAlignVertically = true;
  //game.scale.setShowAll();//there isn't this function in the phaser.d.ts, but it does in phaser 2.10.5 JS
  game.scale.refresh();

  * What should happen:
  The width of canvas/wbgl with the screen size should change but only the height of canvas/webgl changes. Also, the sprites are never scaled to the desired screen size.

  * What happens instead:
The canvas/webgl should resize on diferent sizes with the

**Comment by samme** [comment]
<https://codepen.io/samme/pen/jKWmMb>

**Comment by cpusam** [comment]
Oh my gosh, I found the bug! It was in my game. Before I came here I've tested with my other game and it works fines with phaser, but the current game do not.
Really sorry @samme, and many thank you!
Keep good working.
