### ISSUE TITLE
Visual Studio Code cannot scan for type definition

### ISSUE THREAD

**Issue by imben1109** [photonstorm/phaser-ce#548]
I am using visual studio for TypeScript Application Development. Recently, I try to study Phaser. 

I just install the phaser by yarn. 
```
yarn add phaser-ce
```

I can find the folder phaser-ce in the folder of node_modules and the typescript folder in phaser-ce. However, I found that Visual Studio Code cannot scan the Type Definition. It throw errors when I tried to write a small Phaser Application.

**Comment by albator2018** [comment]
What does it looks with Atom ?

**Comment by imben1109** [comment]
The same

**Comment by samme** [comment]
You might have to add a tsconfig file to your project.

**Comment by imben1109** [comment]
Added . The below is my tsconfig

{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "target",
        "jsx": "react",
        "moduleResolution": "node",
        "allowJs": true
    },
    "include": [
        "src/**/*"
    ]
}

**Comment by samme** [comment]
See <https://github.com/samme/brunch-phaser2/blob/c1e0b8fdb884509ea359e5eb3850617572562811/tsconfig.json#L5>

**Comment by imben1109** [comment]
@samme. Thanks. But it still throws the below exception

[ts] Module '"phaser-ce"' has no exported member 'Phaser'.

```
import { Phaser } from 'phaser-ce';

export default class Test{
    test: Phaser.Game;
}
```

**Comment by samme** [comment]
Try removing 

    import { Phaser } from 'phaser-ce';

**Comment by jdnichollsc** [comment]
Or `import Phaser from 'phaser-ce';`
