### ISSUE TITLE
sprite.getBounds() returns an incorrect value recently after creating sprite

### ISSUE THREAD

**Issue by dylan-chong** [photonstorm/phaser-ce#550]
* A bug in the API:
  * Phaser version(s): 2.10.6
  * Live example: https://codepen.io/anon/pen/rKjMpd
  * What should happen: Correct bounds should be alerted: `{"x":100,"y":200,"width":2=300,"height":400,"type":22}`
  * What happens instead: getBounds() returns `{"x":0,"y":0,"width":27,"height":40,"type":22}`

**Comment by samme** [comment]
You need to call `updateTransform()` on the sprite after scaling: <https://codepen.io/samme/pen/aKpWPO>

I'll update the docs.

> Returns the bounds of the Sprite as a rectangle.
> The bounds calculation takes the worldTransform into account.
> 
> The worldTransform was calculated during the last render pass and is not updated when you call this method. If this Sprite was just created and has never been rendered, you can call `updateTransform` on the Sprite itself. If any of the Sprite's ancestors have been positioned, scaled, or rotated since the last render pass, those changes have not yet have been applied to this Sprite's worldTransform. Call `updateTransform` on the root-most (highest) ancestor that was changed.

**Comment by dylan-chong** [comment]
Thank you!

**Comment by samme** [comment]
For this particular case, `Phaser.Rectangle.clone(sprite)` would also give the same result (without updateTransform).
