### ISSUE TITLE
Camera is smaller than game size when resolution > 1

### ISSUE THREAD

**Issue by thanh-taro** [photonstorm/phaser-ce#552]
I'm writing a game that uses phaser-ce and there is a big problem. When you set resolution > 1 (many mobile devices have resolution greater than 1), camera size is smaller than game view, you can see images below:
[resolution = 1](https://ibb.co/enUKs8)
[resolution > 1](https://ibb.co/mqLg5T)

Any help? :(

**Comment by samme** [comment]
Try <https://photonstorm.github.io/phaser-ce/Phaser.TilemapLayer.html#resize>

**Comment by thanh-taro** [comment]
It works. Thanks a lot.
