### ISSUE TITLE
Issue with WebGL filters on some devices.

### ISSUE THREAD

**Issue by VektreX** [photonstorm/phaser-ce#554]
Hi,
I just ran into a strange issue with using filters.  For some reason if I try to run some code that involves applying a filter to a sprite on my OnePlus 3T (Running Android 8.0.0), the sprite fails to display at all.
The issue only arises on that device; I've tried it with Chrome 67 on Windows 10, Mac OSX High Sierra , as well as my older Android devices which are a Nexus 9 and a Nexus 5, all with no issues.
Here is some basic sample code : 
https://codepen.io/VektreX/pen/ZRMOvm
On the OP3T, the sprite in the corner shows up just fine, but the one in the middle with a filter applied doesn't display at all.
The console also gets flooded in `WebGL: INVALID_VALUE: vertexAttribPointer: index out of range` errors.

**Comment by nazimboudeffa** [comment]
Do you use Cordova to port your code to Android or is it running in the browser ?

**Comment by nazimboudeffa** [comment]
![screenshot_20180713-225932](https://user-images.githubusercontent.com/1375686/42713725-c0a42c30-86f0-11e8-90a8-9c2d4974bb73.png)

**Comment by nazimboudeffa** [comment]
Juste a first question : Can you test please this page [https://phaser.io/examples/v2/filters/blur](https://phaser.io/examples/v2/filters/blur) on your smartphone because it works on mine ?

**Comment by VektreX** [comment]
Yes, the example from the Phaser site does display correctly on Android, but it is using 2.6.2. I forked my pen to use 2.6.2 and filters do work correctly with that version, so there was a regression in Phaser CE that wasn't caught before.
https://codepen.io/VektreX/pen/ZjbqqZ

**Comment by VektreX** [comment]
OK so I have gone through previous versions of Phaser CE and the issue seems to have been introduced with 2.7.0 where it was affecting all platforms, and then was seemingly resolved for most platforms with 2.7.8. I hope this can help to pinpoint the issue.

**Comment by nazimboudeffa** [comment]
Very good point that will help investigate this bug

**Comment by samme** [comment]
Closing, but please reopen if you see this issue again.
