### ISSUE TITLE
 Live example: Rotation Problem

### ISSUE THREAD

**Issue by camoltoni** [photonstorm/phaser-ce#556]
Hello, in the Asteroids Movement example I detected this error. When the UP + RIGHT and SPACE keys are pressed, the shots fire correctly. But if you press UP + LEFT and SPACE, the shots do not come out.
The example code looks correct, I think it's an error in the library.
Thanks for your excellent work.

**Comment by samme** [comment]
It works correctly on mine.

See the notes in <https://photonstorm.github.io/phaser-ce/Phaser.Keyboard.html>.

**Comment by camoltoni** [comment]
Ok, maybe is a problem in linux or kde or firefox, thanks
