### ISSUE TITLE
Input.activePointer position returns (-1, -1)

### ISSUE THREAD

**Issue by HDMemes** [photonstorm/phaser-ce#557]
I'm trying to get the position of the mouse pointer relative to the screen, but when I do `PhaserGame.input.activePointer.clientX` or `PhaserGame.input.activePointer.clientY`, they both return -1, regardless of actual mouse position.

This isn't just the case for `clientX` or `clientY`. `pageX` and `pageY`, and `x` and `y` return -1 as well.

![screenshot 31 _li](https://user-images.githubusercontent.com/31483425/42057075-bebc94cc-7ae1-11e8-89b9-ddffb655493d.jpg)

**Comment by HDMemes** [comment]
I just noticed that `screenX` and `screenY` are also -1. Weird

**Comment by samme** [comment]
Use `game.debug.inputInfo(…)` or `game.debug.pointer(…)`.

Try with no other HTML elements on the page, no CSS, no game parent.

**Comment by HDMemes** [comment]
Still get the same thing :/

**Comment by HDMemes** [comment]
The problem seems to be that there are no active pointers, any ideas on how to fix

**Comment by samme** [comment]
What does `this.game.debug.inputInfo(…)` show?

Verify (in a scene callback)

    this.game === PhaserGame

**Comment by HDMemes** [comment]
X, Y: both 0
World X, Y: both change based on character position, don't change when moving mouse
Scale X, Y: both 1.0
Screen X, Y: both -1

also important to note that button input (e.g. mousePointer.isDown returns false when the mouse button really is down) does not work either.

However, this.game.input.mousePointer.active returns true

this.game === PhaserGame returns true

**Comment by samme** [comment]
Try <https://codepen.io/samme/pen/gKqgbB>.

**Comment by HDMemes** [comment]
This is all I get.

![capture](https://user-images.githubusercontent.com/31483425/44293192-4e9f9f00-a24f-11e8-8187-c05e1d819a17.PNG)

Normal DOM events (such as jQuery .click) are working.

**Comment by HDMemes** [comment]
Nevermind I fixed it, I had to manually set the hitCanvas property of the input object.
