### ISSUE TITLE
Custom text boxes support 

### ISSUE THREAD

**Issue by keshav2010** [photonstorm/phaser-ce#558]
This is a feature request for which I was not able to find any good solution on the web so decided to mention this here, i think it would be great if you guys could implement something like CanvasInput (https://goldfirestudios.com/blog/108/CanvasInput-HTML5-Canvas-Text-Input) for Phaser framework (or simply make it easier to integrate canvasInput). I'm a newbie to phaser and the first and foremost obstacle in front of me is designing custom text boxes, i think it would be great if phaser comes with such APIs that include dedicated Class for these input fields that would simplify a lot of development task

**Comment by Rickrod82** [comment]
Update_payment

**Comment by keshav2010** [comment]
@Rickrod82  sorry, didn't get it..

**Comment by keshav2010** [comment]
just found phaser-input, which satisfies my need , closing this issue
