### ISSUE TITLE
Edge Browser Compatibility

### ISSUE THREAD

**Issue by RemyArmstro** [photonstorm/phaser-ce#56]
Running Phaser in chrome works great, but I am seeing some errors thrown in Edge (syntax errors, inputs not being processed, etc.).  Are there any goals to bring Edge support in line?

**Comment by Dreaded-Gnu** [comment]
Hello @RemyArmstro 
can you provide an example or the error messages thrown in edge.

Just checked out phaser examples repo and tested a bunch of examples with phaser 2.7.5 in edge without any errors.

**Comment by RemyArmstro** [comment]
Closing this. I was testing in Phaser 2.6.2 at the time I wrote this, and most of the examples on the Phaser examples page were throwing errors.  Strangely, I am not seeing those now (even with 2.6.2 - which makes me think I installed an update or something).  I am having some input issues (not errors, but they just aren't triggering my actions like they do in Chrome), but I will open a separate issue if I still have these problems after updating Phaser to latest.
