### ISSUE TITLE
Phaser.LoaderParser.dds and Phaser.LoaderParser.pkm and Phaser.LoaderParser.ktx forget to initialize the property "glExtensionFormat" like pvr does

### ISSUE THREAD

**Issue by zhaxiu3** [photonstorm/phaser-ce#562]
* A bug in the API:  Phaser.LoaderParser.dds and Phaser.LoaderParser.pkm and Phaser.LoaderParser.ktx
  * Phaser version(s): 2.10.3+
  * Live example: 
```     
game.load.image("keyofImage",
        {
             dds: "pathToImage.dds"
        }
     );
```

```  
game.add.image("keyofImage");
```
      
PIXI.WebGLRenderer#updateCompressedTexture calls gl.compressedTexImage2D with parameters which contains textureMetaData.glExtensionFormat.  textureMetaData is returned by Phaser.LoaderParser.dds|pkm|ktx, but none of above three methods return a object with property glExtensionFormat.
  * What should happen: 
    compressed is loaded and upload to GPU by calling 
```
gl.compressedTexImage2D(...
, textureMetaData.glExtensionFormat,
...);
```
  * What happens instead:

```
gl.compressedTexImage2D(...,
textureMetaData.glExtensionFormat,  // is undefined
...);
```

So I think glExtensionFormat should be initialized in three of the methods.

**Comment by samme** [comment]
What happens when running the game?

**Comment by zhaxiu3** [comment]
![image](https://user-images.githubusercontent.com/4149092/42485466-4e12bd9e-842a-11e8-9411-29c1f98a798d.png)

Sorry for not providing enough information.  Above is the screenshot.
No error in the console.
But image is not displayed.

**Comment by zhaxiu3** [comment]
![123](https://user-images.githubusercontent.com/4149092/42485636-144b6b8c-842b-11e8-8643-83cc1d2d2e3c.PNG)


I added the codes at the end of Phaser.LoaderParser#dds and it works.
I guess for pkm and ktx, there would be same problems.

**Comment by samme** [comment]
Want to make a PR?

**Comment by zhaxiu3** [comment]
you mean pull request? 
I'd like to

**Comment by zhaxiu3** [comment]
With my pc and chrome browser I can only test with  "s3tc" format. 
I used compressonator for format converting which can only generate .dds file.
So for now I can only fix .dds with (DTX3 DTX5).
Will the PR accepted?

**Comment by samme** [comment]
You can fix whichever format you can test. Thanks.
