### ISSUE TITLE
What's the difference between 'world' and 'stage'?

### ISSUE THREAD

**Issue by WindsChaser** [photonstorm/phaser-ce#565]
This Issue is about the difference between `world` and `stage`. I found that `game.world.add(sprite)` differs from `game.stage.add(sprite)`--------the 2nd method will not show the sprite on screen, So, what's the difference? I'm confused……

**Comment by samme** [comment]
[Stage](https://photonstorm.github.io/phaser-ce/Phaser.Stage.html) is the root display container. [World](https://photonstorm.github.io/phaser-ce/Phaser.World.html) is the root Group and the first child of the Stage.

Both methods should display the sprite, unless the sprite is offscreen or covered by another object. Only World objects are affected by the camera position.

Use the `game.add.*` methods.
