### ISSUE TITLE
Mistake in documentation on the description of GearConstraints

### ISSUE THREAD

**Issue by foreverip** [photonstorm/phaser-ce#566]
This Issue is about
* An error in the documentation

In the section on [Gear Constraints](https://photonstorm.github.io/phaser-ce/Phaser.Physics.P2.html#createGearConstraint) in the documentation, the description seems to be wrong as it is the same description as the one for Distance Constraints.

**Comment by nazimboudeffa** [comment]
Hi,
I don't undesrtand this error can you explain it with more details please and if there is an error you just have to PR

**Comment by samme** [comment]
<https://samme.github.io/phaser-examples-mirror/p2%20physics/gear%20constraint.html>

**Comment by foreverip** [comment]
Hi, sorry, I'm new to github so I'm not entirely sure how to fix this issue directly.
Anyways, in the Phaser CE documentation, the description of the function createGearConstraint() (link here: https://photonstorm.github.io/phaser-ce/Phaser.Physics.P2.html#createGearConstraint) seems to be incorrectly described as such:
Creates a constraint that tries to keep the distance between two bodies constant.

This is the description for the function createDistanceConstraint() as well, but since these 2 functions do 2 separate things, they should not have the same description. Hopefully someone can fix the docs so the description of createGearConstraint() is correct.

**Comment by samme** [comment]
I can correct it. It looks like a gear constraint locks one body's rotation to another.

**Comment by foreverip** [comment]
It would be great if you corrected it, as I have no idea how to do so myself. Thanks.

**Comment by nazimboudeffa** [comment]
It's a pull request, you fork and clone the repo then make a PR (for short) with explanations on the change you made to the documetion for instance
