### ISSUE TITLE
Typescript does not work, maybe due to duplicate identifier in definition files?

### ISSUE THREAD

**Issue by luckylooke** [photonstorm/phaser-ce#570]
* An error in the TypeScript definitions

**Be nice. We do this for free.** Sure ;)

I cannot make typescript recognise Phaser types, still getting error message "Cannot find namespace 'Phaser'." in VSCODE editor.

So I have put phaser definitions in tsconfig, even the fact that your documentation says that it should be automaticaly included installing phaser by npm ( what I did ).
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "sourceMap": true,
    "types": [
      "node"
    ]
  },
  "files": [
    "./node_modules/phaser-ce/typescript/phaser.comments.d.ts"
  ]
}
```
did, not helped, so I have opened the above mentioned files and find out new error message that `declare class Phaser` and `declare module Phaser` collide and throws another linting error in VSCODE: "Duplicate identifier 'Phaser'." which is true. Or am I doing something wrong?

Many thanks for your time!
Ctibor

**Comment by nazimboudeffa** [comment]
Am not yet a typescript coder so I have just a little question. Which built of Phaser CE are you using ?

**Comment by luckylooke** [comment]
phaser-ce@2.11.0

**Comment by luckylooke** [comment]
I am using typescript in other projects and they just work.. but they usually have libraries which have @types/nameOfLibrary types installed along with the library package.. so as I know the typescript is looking for them in that way.. here is the situation different as I need to provide types to typescript somehow.. which is a new experience for me.

**Comment by luckylooke** [comment]
Another observation, when I create test class:
```
export default class TestClass extends Phaser.Sprite {
  test: string
}
```
Phaser is not found
but when I reference this test class in module which is chained by references to app.js where 
```
import 'phaser'
```
statement is located, it magically works

My project is based on https://github.com/rroylance/phaser-npm-webpack-typescript-starter-project
and the phaser module is there resolved via webpack alias
```
  resolve: {
        extensions: ['.ts', '.js'],
        alias: {
            pixi: path.join(__dirname, 'node_modules/phaser-ce/build/custom/pixi.js'),
            phaser: path.join(__dirname, 'node_modules/phaser-ce/build/custom/phaser-split.js'),
            p2: path.join(__dirname, 'node_modules/phaser-ce/build/custom/p2.js'),
            assets: path.join(__dirname, 'assets/')
        }
    },
```
And then there is also some expose loader in weappack
```
 module: {
        rules: [
            { test: /\.ts$/, enforce: 'pre', loader: 'tslint-loader' },
            { test: /assets(\/|\\)/, loader: 'file-loader?name=assets/[hash].[ext]' },
            { test: /pixi\.js$/, loader: 'expose-loader?PIXI' },
            { test: /phaser-split\.js$/, loader: 'expose-loader?Phaser' },
            { test: /p2\.js$/, loader: 'expose-loader?p2' },
            { test: /\.ts$/, loader: 'ts-loader', exclude: '/node_modules/' }
        ]
    },
```
So I am closing the issue, because I think it is more typescript related and started project related, rather then phaser-ce related

**Comment by samme** [comment]
I believe if you use `import 'phaser-ce'` or such, the types should be found automatically (in node_modules/phaser-ce/…). But `import` is probably not the typical use, so we should probably change the docs on that point.

If you use `files` in tsconfig.json, include phaser.d.ts or phaser.comments.d.ts, but not both. You can try adding `compilerOptions.skipLibCheck = true` as well if you still get duplicate identifier errors.

**Comment by luckylooke** [comment]
Finally I have solved it by putting typeRoots into tsconfig like so:
```
  "typeRoots": [
    "./node_modules/@types",
    "./node_modules/phaser-ce/typescript/"
  ],
```
