### ISSUE TITLE
2.11.0 Phaser.Canvas.setTouchAction is not working?

### ISSUE THREAD

**Issue by halilcakar** [photonstorm/phaser-ce#571]
Hello everyone,

After 2.11.0 release, i just realise that is Phaser.Canvas.setTouchAction is not working.
I downgrade my phaser version to 2.10.6 and it works and its the same code for both.

And now i'm thinking if it wasn't working at all?

on v2.11.0 canvas is preventing the whell scroll event on chrome also not working on Firefox too.

I check the difference but couldn't find anything. Can u please check it up?

    var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'core', { init: init, create: create });
    
    function init() {
        Phaser.Canvas.setTouchAction(game.canvas, 'auto');
        this.input.touch.preventDefault = false;
    }
    
    function create() {
    
        var style = { font: "65px Arial", fill: "#ff0044", align: "center" };
    
        var text = game.add.text(game.world.centerX, game.world.centerY, "- phaser -\nwith a sprinkle of\npixi dust", style);
    
        text.anchor.set(0.5);
    
    }

I'm using this basic example of phaser and also give a 2000px height for page.

**Comment by samme** [comment]
Can you clarify what outcome you're expecting?

setTouchAction() is probably working like before. You can verify that the assigned property is `auto`.

You can disable Phaser's mouse wheel input handler by passing `mouseWheel: false` in the game config or calling

    game.input.mouseWheel.stop()

[debug.inputInfo()](https://codepen.io/samme/pen/gKqgbB) will show you which input handlers are running. On Chrome and Firefox `input.mspointer` is likely active instead of `input.touch`.

**Comment by nazimboudeffa** [comment]
Are you sure you are using it right ? https://phaser.io/docs/2.6.2/Phaser.Canvas.html#.setTouchAction
So when you look at the code it's 
First parameter you set game.canvas so I imagine that the canvas id is 'canvas'
Second parameter default is 'none'

**Comment by halilcakarr** [comment]
@samme im going to try mouseWheel.stop() funciton thanks for advance. I have a scroll bar on my web page and when im on top of with mouse, wheel is not working. That's actually what i want. I wanted to be work :)

@nazimboudeffa i saw the docs on phaser website. Thanks for help, but as i mention i'm trying to make wheel work on phaser canvas :)
