### ISSUE TITLE
SoundManager muteOnPause not working as expected?

### ISSUE THREAD

**Issue by giniwren** [photonstorm/phaser-ce#572]
This Issue is about **a bug in the API** (or possibly unclear documentation).
  * Phaser version(s): 2.11.0, 2.10.3 (version used in codepen)
  * Live example: https://codepen.io/giniwren/pen/WKGrzB
  * What should happen: Setting `game.sound.muteOnPause = false;` should allow sounds to continue playing when the game is paused (via `game.paused = true;`)
  * What happens instead: Sounds stop playing when the game is paused.

Hello again!

Looking through the code, the only place I've found that checks `muteOnPause` is here, which makes some mention of the DOM: https://github.com/photonstorm/phaser-ce/blob/master/src/core/Game.js#L1296

Based on the property description in the docs, it seems like it should still work when I set the paused property of the game myself: https://photonstorm.github.io/phaser-ce/Phaser.SoundManager.html#muteOnPause

I was able to get it working as expected by checking `muteOnPause` around these two lines:
https://github.com/photonstorm/phaser-ce/blob/master/src/core/Game.js#L1428
https://github.com/photonstorm/phaser-ce/blob/master/src/core/Game.js#L1440

My question is: is this not working as intended, or is my expectation wrong based on the variable name/my understanding of the docs?

Thanks for your time, and let me know if I can help with anything.

p.s. Sorry about not posting in the forums first. I can't seem to log in, and it nuked my original post there --  didn't want this to get buried under my to-do list.

**Comment by samme** [comment]
[muteOnPause](https://photonstorm.github.io/phaser-ce/Phaser.SoundManager.html#muteOnPause) actually applies *only* to passive game pauses from losing focus. Setting [game.paused](https://photonstorm.github.io/phaser-ce/Phaser.Game.html#paused) always mutes the sound manager. The docs don't make that especially clear.

It's possible it could be changed to apply to both.

**Comment by samme** [comment]
You can try unmuting the sound immediately after pausing. I can't hear a difference here. <https://codepen.io/samme/pen/Zjpray>

**Comment by giniwren** [comment]
Thanks for the replies and the workaround. Design-wise, should the property only be for passive game pauses, or should it apply for both? Would it be helpful if I make the changes and put together a pull request to make it for both?

**Comment by samme** [comment]
You can certainly make a PR. I don't think the change would cause any problems, but you can test and see.
