### ISSUE TITLE
cant update the lib for 2.11

### ISSUE THREAD

**Issue by vitorregisrr** [photonstorm/phaser-ce#574]
* A bug in the API: texture.source is null
  * Phaser version(s): V2.11

Hi guys! I'm trying to update the phaser lib of my game that is already coded, but i'm having some troubles. 
![43104515-1c9b7c64-8ea8-11e8-9010-1f812d2d752c](https://user-images.githubusercontent.com/9900252/43208615-33557658-9001-11e8-8e10-deb45d3db59a.png)

The rep of the game that im trying to update: https://github.com/vitorregisrr/destruaasmutacoesgame.
When i change the phaser lib im having the error above.

**Comment by samme** [comment]
You're loading a new texture with the key 'logo' at the same time you're displaying a texture with the same key: <https://github.com/vitorregisrr/destruaasmutacoesgame/blob/master/js/preloadState.js#L24>

You need to use a different key for the second one.
