### ISSUE TITLE
Mask in Groups Loses Its Width And Height

### ISSUE THREAD

**Issue by shibekin69** [photonstorm/phaser-ce#578]
This Issue is about a graphic object's properties when turned into a mask and added into an group. I need to get the width and height properties of a graphic object mask that's in a group. It worked in the last version, but it doesn't in the current version.

* A bug in the API:
  * Phaser version(s): 2.11.0
  * Live example:
  * What should happen:

    In version 2.10.0, this is what happens:

```
    mask = this.game.add.graphics(0, 0);
    mask.beginFill(0xFF0000);
    mask.drawRect(0, 0, 200, 400;
    mask.endFill();
    console.log(mask.width) // shows up as 200, correct;
    console.log(mask.height) // shows up as 400, correct;

    newgroup = this.game.add.group();
    newgroup.add(mask);
    console.log(mask.width) // shows up as 200, correct;
    console.log(mask.height) // shows up as 400, correct;
```

  * What happens instead:

    In the current public build of version 2.11.0, this is what happens:

```
    mask = this.game.add.graphics(0, 0);
    mask.beginFill(0xFF0000);
    mask.drawRect(0, 0, 200, 400;
    mask.endFill();
    console.log(mask.width); // shows up as 200, correct
    console.log(mask.height); // shows up as 400, correct

    newgroup = this.game.add.group();
    newgroup.add(mask);
    console.log(mask.width); // shows up as 0, huh?
    console.log(mask.height); // shows up as 0, huh?
```

**Comment by shibekin69** [comment]
I'm not sure where it's coming from, but it seems to be a read-only property. Assigning a new width or height to the mask (that's been added to a group) doesn't change it. It's still 0.

**Comment by samme** [comment]
Graphics used as masks have dimensions 0 × 0. That lets mask containers (in your case, _newgroup_) calculate their own dimensions correctly (#334). 

If you need to know the current drawn area, you can use

```javascript
mask.updateLocalBounds();

var maskBounds = Phaser.Rectangle.Clone(mask._localBounds);
```

Maybe we can add a public method for that.

If the drawing area never changes, it's best to just define it and use it instead:

```javascript
var maskBounds = new Phaser.Rectangle(0, 0, 200, 400);
```

**Comment by shibekin69** [comment]
Oh there it is! Thanks! What I did was take note of the width and height and put those in an object. But I might just use the _localBounds, assuming this won't be changing for a long time.
