### ISSUE TITLE
Error loading audio in Safari

### ISSUE THREAD

**Issue by ferryhalim** [photonstorm/phaser-ce#588]
This Issue is about (pick one, ✏️ delete others)

* A bug in the API:
  * Phaser version(s): 2.11
  * Live example:
  * What should happen: audio loads without error just like on Phaser 2.10
  * What happens instead: Safari throws error. Short audio files seems to load fine. But background music won't load and the game stopped during Preload.

**Comment by samme** [comment]
What's the error?

Are you sure the same example works in v2.10?

**Comment by samme** [comment]
<https://codepen.io/samme/full/PELLvm/>

**Comment by ferryhalim** [comment]
InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.

Forgot to mention, this error appears on mobile Safari (tested on iPod Touch 6, iPad Air 2).

Game works fine before upgrading. And it works fine if I replaced Phaser,js with old version 2.10.
Then I tried using 2.11, but this time I replaced all the audio code with the code from 2.10 and the game works fine. So something in the 2.11 audio code breaks the audio loading for mobile Safari.

**Comment by samme** [comment]
Which v2.10?

**Comment by samme** [comment]
Where does the error come from?

> InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.

**Comment by ferryhalim** [comment]
Grabbing audio code from v2.10.2 and putting it in 2.11 fixed the problem.

I preload all audio files (including the background music) and then do a check in update to make sure all of them are decoded using isSoundDecoded.
When all of them are decoded, I try to play the background music.
That's when the error occured.

**Comment by samme** [comment]
What's the error trace?

**Comment by pieshop** [comment]
Same issue here when building with "phaser-ce": "2.13.2",


Reverting to "phaser-ce": "2.10.5" and the background audio plays fine. Will add more details.

**Comment by SBCGames** [comment]
Same issue with Phaser 2.11.0 here too. Only on iOS + Safari. Error is thrown when I call play on background music (Phaser.Sound loaded in .m4a file format). More, game was tested on various iOS versions with these results:
iOS 8.3, 12.4, 12.4.1 ... all OK,
iOS 9.3.5 ... error (tested on two different devices by two different sponsors with the same result)

It is not easy to get some output from distant testers, but finally I got this (playMusic is where I call play on Phaser.Sound with background music). It is the same as @pieshop 's output.

```
 debug log: [Error] InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
   start (phaser.min.js:3:616567)
   _startSource (phaser.min.js:3:616567)
   play (phaser.min.js:3:612548)
   playMusic (futoshiki.js:3378)
   create (futoshiki.js:8478)
   loadComplete (phaser.min.js:3:249040)
   preUpdate (phaser.min.js:3:246466)
   updateLogic (phaser.min.js:3:292952)
   update (phaser.min.js:3:292377)
   updateRAF (phaser.min.js:3:512405)
   _onLoop (phaser.min.js:3:512284)
```
Now, I will try to upgrade to latest version and also downgrade to 2.10.5. After these variants are tested, I will update comments here.

**Comment by samme** [comment]
I presume this fixes it but I don't have iOS 9 to test: 
[phaser-ce-5565d69854cfebcb2448bd7dcd5051e8666b8b6f.js.zip](https://github.com/photonstorm/phaser-ce/files/3612200/phaser-ce-5565d69854cfebcb2448bd7dcd5051e8666b8b6f.js.zip)

**Comment by SBCGames** [comment]
@samme tested at least on Windows 10 + Lumia (issue https://github.com/photonstorm/phaser-ce/issues/635) and it works well.
 I may get access to iOS 9 device next week. If yes, I will test and report results. At least, my older workaround is currently in process of testing by one of the sponsors, who reported freezes before. If it ends well, it will not test final solution, but will at least confirm, that problem was "undefined".

**Comment by SBCGames** [comment]
@samme I have confirmation, that it now works also on iOS 9 devices.
