### ISSUE TITLE
PIXI is not defined (Ionic 2)

### ISSUE THREAD

**Issue by rpascal** [photonstorm/phaser-ce#59]
Hello, I am trying to create a phaser application using Ionic 2. All that is do is initialize an ionic 2 project using `ionic start` then once that is created I do a `npm install phaser-ce --save` Once that finished I import phaser into one of the auto generated pages like so.
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import Phaser from 'phaser-ce'
@Component({
  selector: 'page-page1',
  templateUrl: 'page1.html'
})
export class Page1 {
  constructor(public navCtrl: NavController) {  }
     ionViewDidLoad(){
        console.log(Phaser)
     }
}
```
Then I simply just try to run the application. When i do i get this error
![pixi erorr](https://cloud.githubusercontent.com/assets/9251639/23835863/1b376518-0745-11e7-940e-2dcff97edecf.PNG)

By going into the developer console on chrome this is where the error is coming from 
![chrome error](https://cloud.githubusercontent.com/assets/9251639/23835878/546df8ba-0745-11e7-9d9f-32a2172b38e7.PNG)

I have tried editing the files to make this work but no matter what i do nothing seems to work. If anyone knows if this is a bug or if I am just doing something wrong that would be great.
Thank you.

**Comment by samme** [comment]
https://github.com/photonstorm/phaser-ce#browserify--cjs

**Comment by Dreaded-Gnu** [comment]
It seems you use webpack for building your project. I got also this issue, but only when using the canvas renderer.

Have you tried setting it up the way mentioned within the webpack section? https://github.com/photonstorm/phaser-ce#webpack

You may also have a look at the following github project: https://github.com/lean/phaser-es6-webpack
With the expose loader, which is also used there, I got rid of the pixi is not defined error within the browser. May be we should extend the webpack section by a hint to expose-loader, when using es6 or typescript.

**Comment by Dreaded-Gnu** [comment]
Maybe also have a look at #43

**Comment by samme** [comment]
Closing for #96
