### ISSUE TITLE
TypeError: this._data is null when using bitmaptext

### ISSUE THREAD

**Issue by vitorregisrr** [photonstorm/phaser-ce#593]
* A bug in the function call:
  * Phaser version(s): Phaser CE v2.11.0

I'm justing calling a simple bitmap text on game, but i'm having the error, i have tested it on Mozila and Chrome.
`TypeError: this._data`

The code that i'm using is 
`game.add.bitmapText(200, 100, 'Arial', 'BitmapText', 64);`

Is that a API BUG or i'm using it wrongly?

**Comment by samme** [comment]
console.log(game.cache.getBitmapFont('Arial'));

**Comment by vitorregisrr** [comment]
edited

**Comment by samme** [comment]
> game.add.bitmapText(200, 100, 'Arial', 'BitmapText', 64);

These arguments look correct, so make sure you're [loading the bitmap font correctly](https://samme.github.io/phaser-examples-mirror/text/bitmap%20fonts.html) and the font data file (.fnt or .xml) is correct.

You can check the game cache contents with

    console.log(game.cache._cache.bitmapFont)

**Comment by vitorregisrr** [comment]
solved, ty
