### ISSUE TITLE
Missing comments in the phaser.comments.d.ts file in release v2.7.3

### ISSUE THREAD

**Issue by atothek1** [photonstorm/phaser-ce#6]
Hi Phaser Team,

I have updated from v2.7.2 to the latest v2.7.3 and detected that the **typescript/phaser.comments.d.ts** has no longer any comments. I find them realy helpfull. I have taken a look into the master branch and it is still without comments.

unfortunately the v2.7.2 tag does not exists here.
I have used npm  for installing it.

best regards
Alex

**Comment by Dreaded-Gnu** [comment]
This issue should also be fixed with pull request #33

**Comment by Dreaded-Gnu** [comment]
@photonstorm this issue can be closed as it has been fixed with pr #33

**Comment by Dreaded-Gnu** [comment]
@samme please close this ticket also
