### ISSUE TITLE
Some bugs in creature.js (and how to fix them)

### ISSUE THREAD

**Issue by lolocaro** [photonstorm/phaser-ce#608]
* Some bugs in **creature.js**:
  * Phaser version(s): probably any
  * What steps produce the bug: try to blend two animations created with Creature
  * What should happen: a blended animation
  * What happens instead: some errors

**Line 7906**
  * Error: target_creature is not defined
  * Fix: line must be `for(var i = 0; i < this.target_creature.total_num_pts * 3; i++)`

**Line 7911**
  * Error: this.blend_render_pts.set is not a function
  * Fix: line must be `this.blend_render_pts[0] = new_vec;`

**Line 7869**
  * Error: blending_factor is not defined
  * Fix: change lines from 76868 to 7870 with this code `this.target_creature.render_pts[set_data_index] =
                ((1.0 - this.blending_factor) * (read_data_1)) +
                (this.blending_factor * (read_data_2));`

**Comment by samme** [comment]
@lolocaro Do these still exist in v2.12.0?

cc. @rroylance

**Comment by rroylance** [comment]
@samme Not sure. I have been using the animation blending with no issues since I updated the runtime and I remember those issues occuring back then. I'll take a look tomorrow when I'm back at work.

**Comment by rroylance** [comment]
@samme @lolocaro Can confirm that these are not issues anymore; they were issues in the previous version of the runtime and were fixed when I updated the runtime. 

I'd call this one safe to close.
