### ISSUE TITLE
When changing the state, the background music of the previous scene does not turn off.Mozilla

### ISSUE THREAD

**Issue by SPavelV** [photonstorm/phaser-ce#618]
* A bug in the API:
  * Phaser version(s): Phaser v2.6.2/
  * Live example: https://picom.ru/19years/
  * What steps produce the bug:  changing the state
  * What should happen:  background music change
  * What happens instead: layering of music from different scenes
  * If there's an error: Firefox Quantum 64.0.2
    * What's the error message? 
sometimes displays -  InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
   
https://picom.ru/19years/
https://github.com/likezninjaz/phaser-rick-and-morty

**Comment by photonstorm** [comment]
Test this with the latest version of Phaser CE, because 2.6.2 is _really_ old now.

**Comment by SPavelV** [comment]
Solved the problem by removing the .loopFull () method.
