### ISSUE TITLE
Chrome 71 (Android) fullscreen mode does not hide Android soft keys

### ISSUE THREAD

**Issue by daniel-nth** [photonstorm/phaser-ce#626]
You may not notice the issue if your Android device has hardware navigation keys. Pixel phones for example have not. [Here's a screenshot of the problem](https://imgur.com/a/CEzHEVU).

This can be solved by passing Fullscreen​Options​.navigationU to the fullscreen request. [MDN
](https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions/navigationUI)

I'll send a pull request in the next couple of days.

**Comment by daniel-nth** [comment]
Not sure if can test for FullscreenOptions support, but I don't think there's any harm in passing it to browsers that don't support it.

**Comment by photonstorm** [comment]
It already passes `navigationUI: hide` to the fullscreen request, so I don't think it's that.

https://github.com/photonstorm/phaser/blob/master/src/scale/ScaleManager.js#L1181-L1183

**Comment by daniel-nth** [comment]
Thanks, but this tickets relates to Phaser CE.
https://github.com/photonstorm/phaser-ce/blob/04204f5180af319e3abdc895190543a9f9f9b7f3/src/core/ScaleManager.js#L1975

**Comment by photonstorm** [comment]
Oops, sorry, yes :) Should be easy enough to add in there.
