### ISSUE TITLE
Combined use of multiple Input Pointers not working

### ISSUE THREAD

**Issue by Weedshaker** [photonstorm/phaser-ce#637]
Android Chrome, PWA, only one Input Pointer works at the same time. More Pointers than one at the same time doe not react. Can anybody reproduce this with their Android device? It works perfectly fine on my Iphone 8, though.

I have been able to (re)produce the bug on Android 8.1.0 Oxygen OS 5.1.4

* A bug in the API:
  * Phaser version(s): v2.13.2
  * Live example: https://tarutarolegends.com (Password: 2014)
  * What steps produce the bug: load the game and start demo
  * What should happen: multiple input pointers should work, resp. should be supported at the same time
  * What happens instead: only one pointer reacts at a time

Cheers

**Comment by Weedshaker** [comment]
https://github.com/photonstorm/phaser-ce/blob/v2.13.2/src/input/Input.js#L413

**Comment by Weedshaker** [comment]
I was able to test it on a different Samsung Android device and it has been no issue there. So, it is device specific! Good to know that this can be an issue... but nothing to do about it.

**Comment by Weedshaker** [comment]
game.input.reset helps!

**Comment by samme** [comment]
Could you try `game.debug.inputInfo(…)` and see what it shows before and after `game.input.reset()`?

**Comment by Weedshaker** [comment]
yeah, thats a bit of a problem, since I don't have an android device on my own. I just borrowed one over the weekend for testing... 

The conclusions I came up with:
1) It happens when interrupting the game, eg. pause, unfocus the app or enter fullscreen...
2) To reset the game.input solves the issue, when done after 1 happens

thank you for your response.
