### ISSUE TITLE
Typo in function prototype

### ISSUE THREAD

**Issue by GregoireDucharme** [photonstorm/phaser-ce#643]
https://github.com/photonstorm/phaser-ce/blob/8eb7a853a28b4faed99049609a632e823b7ba156/typescript/phaser.d.ts#L3140

Hello there ! 

I think there is a mistake in this line.

Thanks !

**Comment by samme** [comment]
Fixed in 7b2856ef3b0fc58838495f10aa6c48e005e2722c
