### ISSUE TITLE
Release v2.13.3 introduced strange image/render batching issues

### ISSUE THREAD

**Issue by Weedshaker** [photonstorm/phaser-ce#644]
The latest release improved performance with https://github.com/photonstorm/phaser-ce/pull/641 but also introduced strange image batching behavior, see screenshot below.

  * Phaser version(s): 2.13.3
  * Live example: 
![Image from iOS](https://user-images.githubusercontent.com/10768924/65830481-37cfd680-e2b0-11e9-824c-f9029eddf486.jpg)
(https://tarutarolegends.com/ but I had to roll it back to version 2.13.2)
  * What steps produce the bug: use game.renderer.setTexturePriority (+ picture atlas) with newest release gives strange batching behaviors
  * What should happen: pictures should not get mangled up
![Image from iOS (1)](https://user-images.githubusercontent.com/10768924/65830561-de1bdc00-e2b0-11e9-8ce6-1233ed2de0c8.jpg)

  * What happens instead: mangling of pictures

Please, have a look, I am also gonna investigate further asap. THX

**Comment by Weedshaker** [comment]
I kept analyzing it and I assume that the whole issue is connected with the pixi warning, expl.: **"pixi.js:3804 setTexturePriority: Image "demo(nov2018)_tileset_levelmap(expanded4)" was given textureIndex=0 because there is no available texture space (-3072)."**

but its funny that this did not have those strange effects before. Now some textures get batched wrongly and mixed up and some texture just don't even bother to appear.

**Comment by Weedshaker** [comment]
@jamieallen1234 I would like to have an exact description why you made the breaking changes at #641  and why the following would have become obsolete: 

https://github.com/photonstorm/phaser-ce/commit/bc4ab92fd3b51b28b75fcd923e8ac494f5248848
`if (PIXI.WebGLRenderer.textureArray[baseTexture.textureIndex] != baseTexture)`
+
`if (PIXI.WebGLRenderer.textureArray[textureIndex] != baseTexture)`

**obviously, this broke my whole texture batching, as you can see above.**
@samme + @photonstorm , I understand that phaser-ce has no priority anymore, but there still are some Patreons like me, who hope that Pull requests are handled with care. THX!

**Comment by samme** [comment]
I had assumed that multi-texture rendering had never worked entirely correctly (#231, #232) and that most authors weren't using it.

#641 solved the outstanding problem of poorer WebGL performance compared to Phaser 2.6.2 (#356). I should have marked it a breaking change.

If we revert #641 then we'll reintroduce some multi-texture bugs (#211, #230, #231, #232).

**Comment by Weedshaker** [comment]
@samme , did you look at the code changes made at #641 and reverted by my PR? Can anybody @photonstorm answer why those two blocks were necessary and why they were there? For me #641 looks just like a hack, removing important stuff for the sake of a little performance and breaking image batching.

**Comment by photonstorm** [comment]
The majority of the changes in #641 looks fine, although I can't see the reason for moving the `FastSpriteBatch` texture index check to outside the children loop. I also can't see why the `if` blocks were removed from the `WebGLSpriteBatch` file. SpriteBatch is a different path entirely to FastSpriteBatch, so removing them literally removes multi-texture support for any sprites using that path.

If someone has a small example I can test with (ideally made using assets from the examples repo), then I can look at this further.

**Comment by samme** [comment]
I don't have an example reproducing the bug. <https://samme.github.io/phaser-examples-mirror/sprites/multi%20texture%20example.html> looks correct.

**Comment by Weedshaker** [comment]
I made a simple example: https://github.com/Weedshaker/phaser-ce_issue-644 the result can be seen here: https://weedshaker.github.io/phaser-ce_issue-644/

As expected the behavior between the two version is different.

**Comment by Weedshaker** [comment]
@photonstorm , do you need anything else?
