### ISSUE TITLE
Update version tag (v2.13.2) in console

### ISSUE THREAD

**Issue by rodri042** [photonstorm/phaser-ce#646]
This Issue is about:
* An error in the documentation

I've downloaded `phaser.min.js` from the `v2.13.3` release, but when using it, the console says:

```
   Phaser CE v2.11.2-dev | Pixi.js | WebGL | WebAudio     http://phaser.io ♥♥♥
```

It should say `v2.13.2`

**Comment by samme** [comment]
I fixed the links. Thanks.

- https://github.com/photonstorm/phaser-ce/releases/download/v2.13.3/phaser.js
- https://github.com/photonstorm/phaser-ce/releases/download/v2.13.3/phaser.min.js
