### ISSUE TITLE
Black screen in mini mode android

### ISSUE THREAD

**Issue by enriqueto** [photonstorm/phaser-ce#647]
Phaser v2.13.2

A black screen is displayed when the game was shifted to mini mode it resumed only after tapping on the game play area.

https://drive.google.com/file/d/19pmoQhvejqbUlcMFuy4wsjRc_cBEaQpg/view

**Comment by samme** [comment]
Can you try the same with this page? 

https://mdn.mozillademos.org/en-US/docs/Web/API/WebGL_API/Basic_2D_animation_example$samples/live-sample
