### ISSUE TITLE
Phaser.Cache.destroy() does not destroy cached items

### ISSUE THREAD

**Issue by andrekampert** [photonstorm/phaser-ce#68]
This Issue is about a bug in the Phaser.Cache API 2.7.3 and below.

In method `Phaser.Cache#destroy` 

```javascript
/**
 * Clears the cache. Removes every local cache object reference.
 * If an object in the cache has a `destroy` method it will also be called.
 *
 * @method Phaser.Cache#destroy
 */
 destroy: function () {
   // ...
}
```

The unexpected behaviour is that most objects that are put in the cache are wrapped in another object, without a `destroy` method.

For example, looking at `BitmapData`, which has a `destroy' method:

- `addBitmapData` stores the actual data in a new object with keys `data` and `frameData`
- `getBitmapData` relies on `getItem` to get the correct data from the cache
- `destroy` does not take the property into account as `getItem` does and therefore does not invoke `destroy` on the `data` and `frameData` objects.

As a result, in this case, canvasses are never returned to the `CanvasPool`, causing a memory leak when loading external image data and relying on the cache to clean up old images.

Suggested solution:

- Update the destroy method to also iterate over the properties in the stored cache object. If a property contains a `destroy` method, invoke it on the property as well.

**Comment by samme** [comment]
Hi @andrekampert, can you test: [phaser-test.js.zip](https://github.com/photonstorm/phaser-ce/files/870523/phaser-test.js.zip)

**Comment by samme** [comment]
https://github.com/samme/phaser-ce/commit/0006372e969d0297eb2c2997f5da170fa7b46a46

**Comment by andrekampert** [comment]
Thank you very much. The change looks good, I'll test it out tomorrow.

**Comment by andrekampert** [comment]
This makes a huge difference. The retained object size in our scenario is reduced to 1/10th of the amount used without the change, mainly due to the canvas pool being cleared correctly now.

Thank you very much!
