### ISSUE TITLE
bad performance in webGL version 2.15+

### ISSUE THREAD

**Issue by drfrankius** [photonstorm/phaser-ce#681]
* Phaser version(s): Phaser CE 2.15 - 2.16.1
Our game is using Phaser CE 2.14.0 right now with WEB GL enabled and the renderer set to high performance. On the project I am working on we have noticed a substantial drop in performance with releases since 2.15 as much as 50% or more on some devices. Switching back to 2.14.0 corrects the performance issue. Is there something that has changed in recent updates that could effect this? 
  
This is the configuration being used for the renderer.

 const config = {
      width: 640,
      height: 960,
      renderer:  Phaser.AUTO,
      transparent: false,
      enableDebug: true,
      powerPreference: 'high-performance',
    };

**Comment by samme** [comment]
Likely that's the #641 / #644 problem.

**Comment by drfrankius** [comment]
It seems like that is what was fixed in 2.15 though? that is the version where we started having issues with slowdowns.
We do not explicitly set multi-texture batch priorities as well.

**Comment by samme** [comment]
#641 improved performance but broke some multitexture batching.

#656 fixed batching but probably reintroduced some performance problems.

Since we don't have a complete fix you might stick to v2.14.0 if that's feasible.

**Comment by drfrankius** [comment]
Ok, thanks for clarifying and the quick replies. I already forked 2.14.0 to pull in fixes for some ios input issues fixed in newer releases.  So for now we are good I guess.
