### ISSUE TITLE
Why was createStaticLayer deprecated?

### ISSUE THREAD

**Issue by ochanje210** [photonstorm/phaser-ce#688]
This Issue is not about a bug but just a question:

Hello! :)
I would like to know why createStaticLayer was deprecated.

<img width="387" alt="Screen Shot 2021-03-22 at 4 26 57 PM" src="https://user-images.githubusercontent.com/16204807/111954469-7e139800-8b2b-11eb-8021-6186ad9cec79.png">

**Comment by photonstorm** [comment]
This is the Phaser CE repo, this question is about Phaser 3. And the answer is that it's no longer required. `createLayer` does everything `createStaticLayer` could do, and more.
