### ISSUE TITLE
2.7.4 ReadMe summary is out of date

### ISSUE THREAD

**Issue by JTronLabs** [photonstorm/phaser-ce#69]
* An error in the documentation

Looks like none of the PRs have updated the ReadMe for a couple of months now. I'm at fault here too. Can we update the summary so everyone can understand what 2.7.4 is changing/fixing? What should go there - author/commit/PR link?

**Comment by photonstorm** [comment]
The README should be updated with every PR, but virtually no-one does (well done to those who remember!). I was going to release 2.7.4 today but I don't have time to go back through all the commits to figure out what is in the version, so have put it off I'm afraid. If someone wants to make the README current then I'll glad publish 2.7.4.

**Comment by JTronLabs** [comment]
Yeah that's what I was thinking. It seems like a good time for 2.7.4, but who knows what exactly is in it. I'll update the Readme for my PRs, and ping everyone else.

Is this a good format for the descriptions (there seems to be some variation)?

`
2.7.4:
short_summary (thanks @contributor #PR_NUMBER)
`

**Comment by photonstorm** [comment]
That is the format I always used, but honestly it doesn't matter what it used for CE as long as it says _something_ :)

**Comment by Dreaded-Gnu** [comment]
Seems like (I did it also) only CHANGELOG.md has been updated with the pull requests.

I'll dive into the changes and provide a pull request with changes.

**Comment by Dreaded-Gnu** [comment]
I dived into the made changes since 2.7.3 and updated changelog and readme markdown files. Further more I've added some missing typescript changes where new functions or new parameters have been added for 2.7.4.

Any reviews of the pull request are appreciated. May be I've missed somewhere something.

**Comment by JTronLabs** [comment]
Damn nice @Dreaded-Gnu ! Thanks much!

**Comment by samme** [comment]
I'd recommend keeping an **Unreleased** heading at the top, as in <https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md#unreleased>.

**Comment by Dreaded-Gnu** [comment]
As far as I understood the process, the `CHANGELOG.md` is for history purposes.

Unreleased changes should be listed above the current release within `README.md`. With a new release, the previous current release is gonna to be moved into the `CHANGELOG.md`.

**Comment by photonstorm** [comment]
Updating just the README is fine re: PRs. When I publish a new version I can easily copy that block over to the change log. Then again, it won't hurt if both are updated. I guess it only becomes an issue if dev A updates the readme and not the change log, but dev B updates the change log and not the readme.

**Comment by samme** [comment]
Addressed in #84
