### ISSUE TITLE
DOCS.md link path error

### ISSUE THREAD

**Issue by xgqfrms** [photonstorm/phaser-ce#726]
* An error in the documentation

# DOCS.md link path error

https://github.com/photonstorm/phaser-ce/blob/master/DOCS.md

> missing `/docs` path

```diff
- https://github.com/photonstorm/phaser-ce/blob/master/Phaser.Game.html
+ https://github.com/photonstorm/phaser-ce/blob/master/docs/Phaser.Game.html
```

**Comment by samme** [comment]
DOCS is the source for <https://github.com/photonstorm/phaser-ce/blob/master/docs/index.html>, where the URLs are correct, so I don't think I can change them. It is inconvenient for browsing on GitHub, though. Maybe I'll move it somewhere less conspicuous.
