### ISSUE TITLE
Display child sprite behind parent sprite

### ISSUE THREAD

**Issue by JarLowrey** [photonstorm/phaser-ce#73]
This Issue is about (delete as applicable)

* A bug in the API - 2.7.3

I'm trying to get some guns to appear behind their parent sprite, and [this thread](http://www.html5gamedevs.com/topic/12338-display-child-sprite-behind-parent-sprite/) leads me to believe it's not possible without a hacky work around. Is this true? If it is, how can we enable support for rendering parent sprite on top of children?

**Comment by samme** [comment]
The current behavior isn't a bug, and it probably won't change in Phaser CE.

The "workaround" is really the best approach for this.
