### ISSUE TITLE
Error TypeScript def getTileX

### ISSUE THREAD

**Issue by nalgorry** [photonstorm/phaser-ce#75]
* An error in the TypeScript defs

in phaser.comments.d.ts 29577:
getTileX(layer: Phaser.TilemapLayer|Phaser.TilemapLayerGL, x: number): number;

in phaser.js line 98574::
Phaser.TilemapLayer.prototype.getTileX = function (x) {

    // var tileWidth = this.tileWidth * this.scale.x;
    return Math.floor(this._fixX(x) / this._mc.tileWidth);

};

same happens for getTileY.

**Comment by Dreaded-Gnu** [comment]
I've fixed the wrong typescript definitions and will provide a pull request, when pr #84 is merged into the repo, to prevent merge issues.
