### ISSUE TITLE
Phaser Sandbox is not available for Phaser-CE

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser-ce#79]
This Issue is about an error on the web site.
[Phaser Sandbox](http://phaser.io/sandbox) is Phaser 2.6.2 only, I cannot find the Phaser-CE version.

**Comment by Dreaded-Gnu** [comment]
@photonstorm How can we achieve a fix for that? Is it the phaser-example repository that needs to be updated? I would provide a pull request, when I know at which repo I've to look into.

**Comment by samme** [comment]
You can try <http://codepen.io/pen?template=vyKJvw> for now.

**Comment by vpmedia** [comment]
Just and idea: maybe the documentation link (https://photonstorm.github.io/phaser-ce/#toc9) should point to the codepen.io template.
