### ISSUE TITLE
Phaser Examples are not running using Phaser-CE

### ISSUE THREAD

**Issue by vpmedia** [photonstorm/phaser-ce#80]
This Issue is about an error in the documentation

For example navigate to page http://phaser.io/examples/v2/loader/load-audio
Try to select Phaser Version 2.7.5 - Phaser CE in dropdown
404 error loading http://examples.phaser.io/_site/phaser/phaser.2.7.5.min.js

**Comment by Dreaded-Gnu** [comment]
@photonstorm How can we achieve a fix for that? Is it the phaser-example repository that needs to be updated? I would provide a pull request, when I know at which repo I've to look into.

**Comment by vpmedia** [comment]
@Dreaded-Gnu I think you are correct and the missing files should be here: https://github.com/photonstorm/phaser-examples/tree/master/examples/_site/phaser

**Comment by vpmedia** [comment]
pull request sent
https://github.com/photonstorm/phaser-examples/pull/160

**Comment by vpmedia** [comment]
I've created a new pull request for 2.7.7 https://github.com/photonstorm/phaser-examples/pull/161
