### ISSUE TITLE
Phaser.Text is using Object.assign, which is an ES6 feature

### ISSUE THREAD

**Issue by kenfoo** [photonstorm/phaser-ce#81]
This Issue is about (delete as applicable)
* Compatibility with older browsers

Without any polyfill, this will fail on some older browsers (e.g. Android 4.4 default browser/webview).

We should change the use of Object.assign to Phaser.Util.extend instead.

**Comment by Dreaded-Gnu** [comment]
As of #83 is merged, this issue can be closed.
