### ISSUE TITLE
BitmapFont from cache.addBitmapFontFromAtlas() does not render well

### ISSUE THREAD

**Issue by crippledcactus** [photonstorm/phaser-ce#86]
This issue is about how BitmapFonts that are created from a texture atlas ( via **cache.addBitmapFontFromAtlas()** ) look very ugly compared to normal BitmapFonts ( **this.load.bitmapFont()** ) that use a separate non-atlas-merged PNG file.

The font PNG and XML are created using Littera. The font PNG is merged with other images into a texture atlas using TexturePacker. I am also using Phaser.CANVAS renderer.

The BitmapFont from the texture atlas is noticeably jagged / cropped on some parts / not smooth.

![bmfont_issue](https://cloud.githubusercontent.com/assets/19533413/24394224/b7b11f1c-13cd-11e7-801f-5d1c90459ab9.png)

**cache.addBitmapFontFromAtlas()** is a very nice and handy feature as I am able to merge all my fonts into one texture atlas, however I currently can't use it in my game because it doesn't render so well. I would appreciate a fix for this. :)

**Comment by crippledcactus** [comment]
sorry for that, this is the code used:

```
export class PreloadState extends Phaser.State
{
    public preload():void
    {
        // set app background color
        this.stage.backgroundColor = 0x0a4770;

        // spriteatlases
        this.load.atlasJSONHash("atlas_1", "assets/visual/temp_ta.png", "assets/visual/temp_ta.json");

        // atlas bm font xml
        this.load.xml("museo_sans_rounded_TA_xml", "assets/visual/museo_sans_rounded_max32.fnt");

        // separate bm font
        this.load.bitmapFont("museo_sans_rounded", "assets/visual/museo_sans_rounded_max32.png", "assets/visual/museo_sans_rounded_max32.fnt", "xml", 0, 0);
    }

    public create():void
    {
        // add bm font from atlas
        this.cache.addBitmapFontFromAtlas("museo_sans_rounded_TA", "atlas_1", "museo_sans_rounded_max32", "museo_sans_rounded_TA_xml", "xml", 0, 0);

        // container for bitmap texts
        let container:Phaser.Group = this.game.add.group();

        // properties
        let theString:string = "hey man wake up and smell the concrete...";
        let maxWidth:number = 200;

        // normal text using a bitmapfont created from a separate png file
        let normalText:Phaser.BitmapText = this.game.make.bitmapText(30, 10, "museo_sans_rounded", theString, 32, "center");
        normalText.maxWidth = maxWidth;
        container.addChild(normalText);

        // text using a bitmapfont created from a texture atlas via cache.addBitmapFontFromAtlas
        let atlasText:Phaser.BitmapText = this.game.make.bitmapText(30, 200, "museo_sans_rounded_TA", theString, 32, "center");
        atlasText.maxWidth = 200;
        container.addChild(atlasText);
    }
}
```

**Comment by samme** [comment]
Hi @crippledcactus, can you attach the atlas files too? Or post a runnable example if you can. Thanks.

**Comment by crippledcactus** [comment]
Hi @samme , I made a very small project to specifically demonstrate this issue.

The zip containing all the files can be downloaded here: https://www.dropbox.com/s/cdsjgc5xpjolq9q/phaser_font_prob.zip?dl=0

I hope this helps. :) All files needed to run are in the "bin" folder.

**Comment by samme** [comment]
This one looks OK: <http://codepen.io/samme/pen/dWbgRL>

![bitmapfont](https://cloud.githubusercontent.com/assets/435681/24933296/7e3a0d54-1eca-11e7-948c-e42c7f5c01b5.png)

Based on <https://github.com/photonstorm/phaser-examples/blob/master/examples/text/bitmap%20font%20from%20texture%20atlas.js>

**Comment by samme** [comment]
Couldn't reproduce.
