### ISSUE TITLE
Is .editorconfig end_of_line = crlf correct?

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#89]
In [Phaser 2.6.2](https://github.com/photonstorm/phaser/blob/v2.6.2/.editorconfig#L7) it's `lf`.

In [Phaser 3](https://github.com/photonstorm/phaser/blob/master/v3/.editorconfig#L7) it's `lf`.

Phaser CE's .editorconfig itself contains only `lf`.

There will be mixed line endings. 😿

**Comment by photonstorm** [comment]
The `.editorconfig` in CE was left over from some v3 work, it isn't used (or rather, isn't adhered to within the code), so change it as needed.

**Comment by Dreaded-Gnu** [comment]
When it is phaser v3 related can it be safely removed here? Or is it really necessary?

**Comment by photonstorm** [comment]
It's not needed, although I would argue it's worth keeping, just editing.
