### ISSUE TITLE
MultiTexturing after 2.7.3.

### ISSUE THREAD

**Issue by Pit-the-Angel** [photonstorm/phaser-ce#90]
Using multiple spritesheets in the game causes too many drawCalls, even having >5 drawCalls means on devices it runs below 30fps.  In phaser 2.7.0 -> 2.7.2, using MultiTexture support fixed this issue on Desktops/Android devices but on iOS, a lot of textures were replaced with solid Magenta.  When 2.7.3 was released, this "fixed" this issue, but now it just doesn't seem to be working on most devices at all.

I've looked through and put console logs into `phaser-ce/src/pixi/renderers/WebGLRenderer.js` to look, and  it seems that on my desktop, the maxTextureSpaceAvailable is more than enough to fit all spritesheets with lots of space leftover, but even on my Samsung S7, the maxTextureSpaceAvailable is at 0 before even getting to adding any spritesheets into the texture cache.  

My first test i attempted was to just remove the limit making sure maxTextureSpaceAvailable  was above 0, and to my surprise, on my S7, the game ran at 60fps with a single draw call, even with this value dropping below zero...

`if (maxTextureAvailableSpace <= 0) {
        base.textureIndex = 0;
    } else {
        base.textureIndex = (1 + (index % (maxTextures - 1)));
    }`

Seems a bit weird that it could drop below zero, i'm not very knowledgeable about working directly with WebGL, but initial thoughts were that maybe the reported value of `var maxTextureSize = gl.getParameter(gl.MAX_TEXTURE_SIZE);` might be incorrect... though i'm honestly not 100% on that.. however my happiness of 'fixing' this was short-lived as the game just doesn't work on iOS now, obviously things are very different between the two.

Even if its something i'm personally doing wrong in my code, it seems wrong that on Android i can add things to the textureCache which exeeds the Max_Texture_Size and it works fine, 60fps.. but not on iOS.  I'll keep looking personally as having a high FPS on devices are very important to my project, and the multiple spritesheets are essential for supporting multiple languages, but potentially something not working right here that someone could take a look at?

**Comment by samme** [comment]
> When 2.7.3 was released, this "fixed" this issue, but now it just doesn't seem to be working on most devices at all.

Hi @Pit-the-Angel, so what do you actually see on those devices now (2.7.5)?

**Comment by Pit-the-Angel** [comment]
Well, on Android S7 the maxTextureSize reports as 4092, since my games canvas is 1335:750 then with the framebuffer and game canvas taken out, then before any spritesheets can get added, it's already set to 0.  (I believe the clampPot function takes out 2048 for both.)

It makes sense using these numbers that multiTexturing of course wouldn't work, but .. it was before 2.7.3, and when i just remove the IF case in Phaser checking that maxTextureSize was above 0, on Android i am not getting any errors, and it works fine (1 draw Call). The only issue then exists on iOS where the textures are corrupted... so i guess something is weird there.  Just seems strange the 'fix' for making it work on iOS is .. making no multiTexturing working on device..

_(On a side note, i am finding it tough to make games run smoothly, if there is there any tips or advice anyone can sprinkle on getting games running on low-end device, would be really appreciated >.<')_

**Comment by samme** [comment]
See `debug.renderer(…)` in <https://codepen.io/samme/pen/MoGJQw>.
