### ISSUE TITLE
Phaser video can't be played in Android Chrome 56

### ISSUE THREAD

**Issue by AnnaHui** [photonstorm/phaser-ce#92]
My android chrome 56 can't play the Phaser video.
It can play in desktop and tablet, not include mobile' chrome56.
But It can play in chrome55....
What can I do for it?
thank you.

**Comment by AnnaHui** [comment]
HI. this is code example.

http://codepen.io/AnnaLiu/pen/EWJNPa?editors=1011

It's can't play in Android chrome56.

IOS chrome56 and safari can play smoothly.

thanks!

**Comment by samme** [comment]
Thanks. Can you check <http://codepen.io/samme/pen/bqJgwb> in Android/Chrome — what does it say in `touchLocked:`?

**Comment by AnnaHui** [comment]
Hi, it show the image in Android.
[http://zealmass.com/demo/demovideo/image.jpg](url)

`touchLocked ` is true in Android mobile.

I try it in IOS, it show the same message, and IOS can play.
[http://zealmass.com/demo/demovideo/ios.jpg](url)

thanks.

**Comment by samme** [comment]
Maybe related to <https://www.chromestatus.com/feature/6131337345892352>.

**Comment by AnnaHui** [comment]
Hi Samme.
Thanks! Do you have any solution ?
I try a lot of code from Phaser ce api, but It still can't run.
thank you.

**Comment by samme** [comment]
I don't. 😞 Does touching the game make any difference?

**Comment by AnnaHui** [comment]
Hi Samme.
I just want to play the video in desktop and mobile.

Not only can't touch the screen, 
if I set a button to play the video and I click it, the video also isn't play. 

Phaser ce api
https://photonstorm.github.io/phaser-ce/Phaser.Video.html

> On some mobile browsers such as iOS Safari, you cannot play a video `until the user has explicitly touched the screen.`
> This works in the same way as audio unlocking. Phaser will handle the touch unlocking for you, however unlike with audio
> it's worth noting that every single Video needs to be touch unlocked, not just the first one. You can use the changeSource
> method to try and work around this limitation, but see the method help for details.


Hoo......., chrome56(now is 57) for Android is a troble.
I have no way to solve the problem.

**Comment by VektreX** [comment]
Hi. I am working on a game that relies a lot on videos, and I can confirm I have the very same issue, videos no longer unlock on Chrome 56+ for Android, probably due to a change in the browser's behavior.

**Comment by AnnaHui** [comment]
Thank @VektreX .

This is the same problem.
https://productforums.google.com/forum/#!topic/chrome/p7Nt5FHqQPI;context-place=starred
https://bugs.chromium.org/p/chromium/issues/detail?id=710299
https://bugs.chromium.org/p/chromium/issues/detail?id=701060

To date, the error can't be solve.

**Comment by samme** [comment]
I wonder if Phaser.Video#setTouchLock should be using `touchend` instead of `touchstart`.

**Comment by samme** [comment]
@AnnaHui Can you test again in the latest Phaser CE?

**Comment by osmanzeki** [comment]
I can confirm that this demo works on mobile. It still throws the DOM Exception, but in the end it works (the video plays in mobile) in Phaser 2.6.2. I see that there was a recent refactor of the touch unlock code. I too think that the touch unlock should probably occur at `touchend` to fix this issue.

This pen is a modified version of this:
https://codepen.io/junov/pen/RgrxOB

(Found in one of the discussion in the links above)

**Comment by osmanzeki** [comment]
Strangely enough, the following lines seem to enable playback without any issues (this is an iOS 10+ oriented fix though).

```javascript
this.video = this.game.add.video('tour_video');
this.videoSprite = this.video.addToWorld(0, 0);

this.video.video.setAttribute('webkit-playsinline', 'webkit-playsinline');
this.video.video.setAttribute('playsinline', 'playsinline');
this.video.play();
```

**Comment by samme** [comment]
Is there any reason **not** to switch to `touchend` to unlock both audio and video?

Right now we use `touchend` for audio on newer Chrome on iOS, `touchstart` for everything else.

**Comment by VektreX** [comment]
The video correctly unlocks on touch on your example. As a side note, do you think there is a way to programmatically re-enable muted autoplay on devices that require touch unlock?

**Comment by samme** [comment]
Assume this is resolved.
