### ISSUE TITLE
Arcade tile collision bug - sprite sometimes passes through tiles 

### ISSUE THREAD

**Issue by grayleonard** [photonstorm/phaser-ce#94]
See for example: https://gfycat.com/PitifulNewDairycow

I'm updating bullets per frame like this:
```javascript
bullets.forEach(function(bullet) {
	game.physics.arcade.collide(bullet,  layer, function(b, l) {
		b.kill(), bullets.remove(b)
	})
	bullet.body.velocity.x = 300
	bullet.body.velocity.y = 0
})
```

As you can see in the video, collision sometimes works and sometimes doesn't.  It seems to happen when the bullet hits the edge of a tile. I've tried setting the bullet's ```tilePadding``` to a large number as well as ensuring the velocity > 0, but at this point I think it's a bug instead of a mistake I'm making :-).

Currently using latest version of Phaser CE.

**Comment by samme** [comment]
Can you try removing `bullets.remove(b)`?

**Comment by grayleonard** [comment]
Still happening: 

<img width="421" alt="screen shot 2017-03-31 at 7 41 38 pm" src="https://cloud.githubusercontent.com/assets/3433280/24572803/2315232e-164a-11e7-9d9a-9e33a46a2923.png">

**Comment by grayleonard** [comment]
Just disabled @hexus's Arcade Slopes plugin and don't seem to have the bug anymore. Will move issue to the Slopes repo.

**Comment by hexus** [comment]
Curious! Those projectiles are pretty small and that's probably why; they will only collide when they're touching the colliding face, not the entire tile. Perhaps I should try to change this in the plugin.

In a future version of the plugin, this will be solved using raytracing, which should solve tunnelling completely.
