### ISSUE TITLE
Update Project Templates/Webpack

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#95]
We should make a simplest possible working Webpack 2 config for Phaser and link to it from README.

<https://github.com/photonstorm/phaser-ce/tree/master/resources/Project%20Templates/Webpack>

**Comment by Dreaded-Gnu** [comment]
If you want, you can assign that issue to me, and I'll take care for adding a bare webpack project template. We could might then remove the webpack part from readme and link to webpack project.

**Comment by samme** [comment]
I'd like just a simple template with `webpack.config.js` and no extra loaders or plugins, and with comments in the config to show what it's doing and why.

You can definitely add a Webpack/Typescript template too if you like.

**Comment by Dreaded-Gnu** [comment]
Also here the question: Can I add a package.json for that project template? Then it might be ready to use from start.

**Comment by samme** [comment]
Sure.
