### ISSUE TITLE
How to use Phaser + Ionic

### ISSUE THREAD

**Issue by samme** [photonstorm/phaser-ce#96]
We should add a note in README (if simple) or a Project Template.

**Comment by Dreaded-Gnu** [comment]
If you want, you can assign that issue to me, and I'll take care for adding an ionic 2 project template.

**Comment by samme** [comment]
Consider yourself assigned! 👑

**Comment by Dreaded-Gnu** [comment]
Shall the example work like it is done at the current webpack example? Or shall the ionic 2 example use a own package.json?

Currently the webpack example doesn't use phaser-ce installed via npm, so the main problem with importing phaser, pixi and p2 correctly won't occur there.

**Comment by samme** [comment]
Probably give it its own package.json if that's the typical use.
